// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: proto/namespace/private/git/manager.proto

package gitv1beta

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GitManagerService_EnsureLfsMirror_FullMethodName          = "/namespace.private.git.v1beta.GitManagerService/EnsureLfsMirror"
	GitManagerService_EnsureGitSnapshotService_FullMethodName = "/namespace.private.git.v1beta.GitManagerService/EnsureGitSnapshotService"
)

// GitManagerServiceClient is the client API for GitManagerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GitManagerServiceClient interface {
	EnsureLfsMirror(ctx context.Context, in *EnsureLfsMirrorRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[EnsureLfsMirrorResponseChunk], error)
	EnsureGitSnapshotService(ctx context.Context, in *EnsureGitSnapshotServiceRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[EnsureGitSnapshotServiceResponse], error)
}

type gitManagerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGitManagerServiceClient(cc grpc.ClientConnInterface) GitManagerServiceClient {
	return &gitManagerServiceClient{cc}
}

func (c *gitManagerServiceClient) EnsureLfsMirror(ctx context.Context, in *EnsureLfsMirrorRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[EnsureLfsMirrorResponseChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &GitManagerService_ServiceDesc.Streams[0], GitManagerService_EnsureLfsMirror_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[EnsureLfsMirrorRequest, EnsureLfsMirrorResponseChunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GitManagerService_EnsureLfsMirrorClient = grpc.ServerStreamingClient[EnsureLfsMirrorResponseChunk]

func (c *gitManagerServiceClient) EnsureGitSnapshotService(ctx context.Context, in *EnsureGitSnapshotServiceRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[EnsureGitSnapshotServiceResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &GitManagerService_ServiceDesc.Streams[1], GitManagerService_EnsureGitSnapshotService_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[EnsureGitSnapshotServiceRequest, EnsureGitSnapshotServiceResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GitManagerService_EnsureGitSnapshotServiceClient = grpc.ServerStreamingClient[EnsureGitSnapshotServiceResponse]

// GitManagerServiceServer is the server API for GitManagerService service.
// All implementations must embed UnimplementedGitManagerServiceServer
// for forward compatibility.
type GitManagerServiceServer interface {
	EnsureLfsMirror(*EnsureLfsMirrorRequest, grpc.ServerStreamingServer[EnsureLfsMirrorResponseChunk]) error
	EnsureGitSnapshotService(*EnsureGitSnapshotServiceRequest, grpc.ServerStreamingServer[EnsureGitSnapshotServiceResponse]) error
	mustEmbedUnimplementedGitManagerServiceServer()
}

// UnimplementedGitManagerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGitManagerServiceServer struct{}

func (UnimplementedGitManagerServiceServer) EnsureLfsMirror(*EnsureLfsMirrorRequest, grpc.ServerStreamingServer[EnsureLfsMirrorResponseChunk]) error {
	return status.Error(codes.Unimplemented, "method EnsureLfsMirror not implemented")
}
func (UnimplementedGitManagerServiceServer) EnsureGitSnapshotService(*EnsureGitSnapshotServiceRequest, grpc.ServerStreamingServer[EnsureGitSnapshotServiceResponse]) error {
	return status.Error(codes.Unimplemented, "method EnsureGitSnapshotService not implemented")
}
func (UnimplementedGitManagerServiceServer) mustEmbedUnimplementedGitManagerServiceServer() {}
func (UnimplementedGitManagerServiceServer) testEmbeddedByValue()                           {}

// UnsafeGitManagerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GitManagerServiceServer will
// result in compilation errors.
type UnsafeGitManagerServiceServer interface {
	mustEmbedUnimplementedGitManagerServiceServer()
}

func RegisterGitManagerServiceServer(s grpc.ServiceRegistrar, srv GitManagerServiceServer) {
	// If the following call panics, it indicates UnimplementedGitManagerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GitManagerService_ServiceDesc, srv)
}

func _GitManagerService_EnsureLfsMirror_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(EnsureLfsMirrorRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(GitManagerServiceServer).EnsureLfsMirror(m, &grpc.GenericServerStream[EnsureLfsMirrorRequest, EnsureLfsMirrorResponseChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GitManagerService_EnsureLfsMirrorServer = grpc.ServerStreamingServer[EnsureLfsMirrorResponseChunk]

func _GitManagerService_EnsureGitSnapshotService_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(EnsureGitSnapshotServiceRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(GitManagerServiceServer).EnsureGitSnapshotService(m, &grpc.GenericServerStream[EnsureGitSnapshotServiceRequest, EnsureGitSnapshotServiceResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GitManagerService_EnsureGitSnapshotServiceServer = grpc.ServerStreamingServer[EnsureGitSnapshotServiceResponse]

// GitManagerService_ServiceDesc is the grpc.ServiceDesc for GitManagerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GitManagerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "namespace.private.git.v1beta.GitManagerService",
	HandlerType: (*GitManagerServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "EnsureLfsMirror",
			Handler:       _GitManagerService_EnsureLfsMirror_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "EnsureGitSnapshotService",
			Handler:       _GitManagerService_EnsureGitSnapshotService_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/namespace/private/git/manager.proto",
}
