// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: proto/namespace/private/instance/instance.proto

package instancev1betaconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	instance "namespacelabs.dev/integrations/proto/namespace/private/instance"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// InstanceServiceName is the fully-qualified name of the InstanceService service.
	InstanceServiceName = "namespace.private.instance.v1beta.InstanceService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// InstanceServiceAddAttachmentProcedure is the fully-qualified name of the InstanceService's
	// AddAttachment RPC.
	InstanceServiceAddAttachmentProcedure = "/namespace.private.instance.v1beta.InstanceService/AddAttachment"
)

// These variables are the protoreflect.Descriptor objects for the RPCs defined in this package.
var (
	instanceServiceServiceDescriptor             = instance.File_proto_namespace_private_instance_instance_proto.Services().ByName("InstanceService")
	instanceServiceAddAttachmentMethodDescriptor = instanceServiceServiceDescriptor.Methods().ByName("AddAttachment")
)

// InstanceServiceClient is a client for the namespace.private.instance.v1beta.InstanceService
// service.
type InstanceServiceClient interface {
	AddAttachment(context.Context, *connect.Request[instance.AddAttachmentRequest]) (*connect.Response[emptypb.Empty], error)
}

// NewInstanceServiceClient constructs a client for the
// namespace.private.instance.v1beta.InstanceService service. By default, it uses the Connect
// protocol with the binary Protobuf Codec, asks for gzipped responses, and sends uncompressed
// requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewInstanceServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) InstanceServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	return &instanceServiceClient{
		addAttachment: connect.NewClient[instance.AddAttachmentRequest, emptypb.Empty](
			httpClient,
			baseURL+InstanceServiceAddAttachmentProcedure,
			connect.WithSchema(instanceServiceAddAttachmentMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
	}
}

// instanceServiceClient implements InstanceServiceClient.
type instanceServiceClient struct {
	addAttachment *connect.Client[instance.AddAttachmentRequest, emptypb.Empty]
}

// AddAttachment calls namespace.private.instance.v1beta.InstanceService.AddAttachment.
func (c *instanceServiceClient) AddAttachment(ctx context.Context, req *connect.Request[instance.AddAttachmentRequest]) (*connect.Response[emptypb.Empty], error) {
	return c.addAttachment.CallUnary(ctx, req)
}

// InstanceServiceHandler is an implementation of the
// namespace.private.instance.v1beta.InstanceService service.
type InstanceServiceHandler interface {
	AddAttachment(context.Context, *connect.Request[instance.AddAttachmentRequest]) (*connect.Response[emptypb.Empty], error)
}

// NewInstanceServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewInstanceServiceHandler(svc InstanceServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	instanceServiceAddAttachmentHandler := connect.NewUnaryHandler(
		InstanceServiceAddAttachmentProcedure,
		svc.AddAttachment,
		connect.WithSchema(instanceServiceAddAttachmentMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	return "/namespace.private.instance.v1beta.InstanceService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case InstanceServiceAddAttachmentProcedure:
			instanceServiceAddAttachmentHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedInstanceServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedInstanceServiceHandler struct{}

func (UnimplementedInstanceServiceHandler) AddAttachment(context.Context, *connect.Request[instance.AddAttachmentRequest]) (*connect.Response[emptypb.Empty], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("namespace.private.instance.v1beta.InstanceService.AddAttachment is not implemented"))
}
