// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: proto/namespace/private/sessions/users.proto

package sessionsv1beta

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListSessionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Session       []*Session             `protobuf:"bytes,1,rep,name=session,proto3" json:"session,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSessionsResponse) Reset() {
	*x = ListSessionsResponse{}
	mi := &file_proto_namespace_private_sessions_users_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSessionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSessionsResponse) ProtoMessage() {}

func (x *ListSessionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_namespace_private_sessions_users_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSessionsResponse.ProtoReflect.Descriptor instead.
func (*ListSessionsResponse) Descriptor() ([]byte, []int) {
	return file_proto_namespace_private_sessions_users_proto_rawDescGZIP(), []int{0}
}

func (x *ListSessionsResponse) GetSession() []*Session {
	if x != nil {
		return x.Session
	}
	return nil
}

type InvalidateSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InvalidateSessionRequest) Reset() {
	*x = InvalidateSessionRequest{}
	mi := &file_proto_namespace_private_sessions_users_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvalidateSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvalidateSessionRequest) ProtoMessage() {}

func (x *InvalidateSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_namespace_private_sessions_users_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvalidateSessionRequest.ProtoReflect.Descriptor instead.
func (*InvalidateSessionRequest) Descriptor() ([]byte, []int) {
	return file_proto_namespace_private_sessions_users_proto_rawDescGZIP(), []int{1}
}

func (x *InvalidateSessionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type InvalidateAllSessionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     []string               `protobuf:"bytes,1,rep,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InvalidateAllSessionsResponse) Reset() {
	*x = InvalidateAllSessionsResponse{}
	mi := &file_proto_namespace_private_sessions_users_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvalidateAllSessionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvalidateAllSessionsResponse) ProtoMessage() {}

func (x *InvalidateAllSessionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_namespace_private_sessions_users_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvalidateAllSessionsResponse.ProtoReflect.Descriptor instead.
func (*InvalidateAllSessionsResponse) Descriptor() ([]byte, []int) {
	return file_proto_namespace_private_sessions_users_proto_rawDescGZIP(), []int{2}
}

func (x *InvalidateAllSessionsResponse) GetSessionId() []string {
	if x != nil {
		return x.SessionId
	}
	return nil
}

type IssueTenantTokenFromSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TokenDuration *durationpb.Duration   `protobuf:"bytes,1,opt,name=token_duration,json=tokenDuration,proto3" json:"token_duration,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IssueTenantTokenFromSessionRequest) Reset() {
	*x = IssueTenantTokenFromSessionRequest{}
	mi := &file_proto_namespace_private_sessions_users_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IssueTenantTokenFromSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IssueTenantTokenFromSessionRequest) ProtoMessage() {}

func (x *IssueTenantTokenFromSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_namespace_private_sessions_users_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IssueTenantTokenFromSessionRequest.ProtoReflect.Descriptor instead.
func (*IssueTenantTokenFromSessionRequest) Descriptor() ([]byte, []int) {
	return file_proto_namespace_private_sessions_users_proto_rawDescGZIP(), []int{3}
}

func (x *IssueTenantTokenFromSessionRequest) GetTokenDuration() *durationpb.Duration {
	if x != nil {
		return x.TokenDuration
	}
	return nil
}

type IssueTenantTokenFromSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantToken   string                 `protobuf:"bytes,1,opt,name=tenant_token,json=tenantToken,proto3" json:"tenant_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IssueTenantTokenFromSessionResponse) Reset() {
	*x = IssueTenantTokenFromSessionResponse{}
	mi := &file_proto_namespace_private_sessions_users_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IssueTenantTokenFromSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IssueTenantTokenFromSessionResponse) ProtoMessage() {}

func (x *IssueTenantTokenFromSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_namespace_private_sessions_users_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IssueTenantTokenFromSessionResponse.ProtoReflect.Descriptor instead.
func (*IssueTenantTokenFromSessionResponse) Descriptor() ([]byte, []int) {
	return file_proto_namespace_private_sessions_users_proto_rawDescGZIP(), []int{4}
}

func (x *IssueTenantTokenFromSessionResponse) GetTenantToken() string {
	if x != nil {
		return x.TenantToken
	}
	return ""
}

var File_proto_namespace_private_sessions_users_proto protoreflect.FileDescriptor

const file_proto_namespace_private_sessions_users_proto_rawDesc = "" +
	"\n" +
	",proto/namespace/private/sessions/users.proto\x12!namespace.private.sessions.v1beta\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1egoogle/protobuf/duration.proto\x1a.proto/namespace/private/sessions/session.proto\"\\\n" +
	"\x14ListSessionsResponse\x12D\n" +
	"\asession\x18\x01 \x03(\v2*.namespace.private.sessions.v1beta.SessionR\asession\"9\n" +
	"\x18InvalidateSessionRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\">\n" +
	"\x1dInvalidateAllSessionsResponse\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x03(\tR\tsessionId\"f\n" +
	"\"IssueTenantTokenFromSessionRequest\x12@\n" +
	"\x0etoken_duration\x18\x01 \x01(\v2\x19.google.protobuf.DurationR\rtokenDuration\"H\n" +
	"#IssueTenantTokenFromSessionResponse\x12!\n" +
	"\ftenant_token\x18\x01 \x01(\tR\vtenantToken2\x82\x04\n" +
	"\x13UserSessionsService\x12_\n" +
	"\fListSessions\x12\x16.google.protobuf.Empty\x1a7.namespace.private.sessions.v1beta.ListSessionsResponse\x12h\n" +
	"\x11InvalidateSession\x12;.namespace.private.sessions.v1beta.InvalidateSessionRequest\x1a\x16.google.protobuf.Empty\x12q\n" +
	"\x15InvalidateAllSessions\x12\x16.google.protobuf.Empty\x1a@.namespace.private.sessions.v1beta.InvalidateAllSessionsResponse\x12\xac\x01\n" +
	"\x1bIssueTenantTokenFromSession\x12E.namespace.private.sessions.v1beta.IssueTenantTokenFromSessionRequest\x1aF.namespace.private.sessions.v1beta.IssueTenantTokenFromSessionResponseB\xae\x02\n" +
	"%com.namespace.private.sessions.v1betaB\n" +
	"UsersProtoP\x01ZNnamespacelabs.dev/integrations/proto/namespace/private/sessions;sessionsv1beta\xa2\x02\x03NPS\xaa\x02!Namespace.Private.Sessions.V1beta\xca\x02#Namespace_\\Private_\\Sessions\\V1beta\xe2\x02/Namespace_\\Private_\\Sessions\\V1beta\\GPBMetadata\xea\x02$Namespace::Private::Sessions::V1betab\x06proto3"

var (
	file_proto_namespace_private_sessions_users_proto_rawDescOnce sync.Once
	file_proto_namespace_private_sessions_users_proto_rawDescData []byte
)

func file_proto_namespace_private_sessions_users_proto_rawDescGZIP() []byte {
	file_proto_namespace_private_sessions_users_proto_rawDescOnce.Do(func() {
		file_proto_namespace_private_sessions_users_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_namespace_private_sessions_users_proto_rawDesc), len(file_proto_namespace_private_sessions_users_proto_rawDesc)))
	})
	return file_proto_namespace_private_sessions_users_proto_rawDescData
}

var file_proto_namespace_private_sessions_users_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_namespace_private_sessions_users_proto_goTypes = []any{
	(*ListSessionsResponse)(nil),                // 0: namespace.private.sessions.v1beta.ListSessionsResponse
	(*InvalidateSessionRequest)(nil),            // 1: namespace.private.sessions.v1beta.InvalidateSessionRequest
	(*InvalidateAllSessionsResponse)(nil),       // 2: namespace.private.sessions.v1beta.InvalidateAllSessionsResponse
	(*IssueTenantTokenFromSessionRequest)(nil),  // 3: namespace.private.sessions.v1beta.IssueTenantTokenFromSessionRequest
	(*IssueTenantTokenFromSessionResponse)(nil), // 4: namespace.private.sessions.v1beta.IssueTenantTokenFromSessionResponse
	(*Session)(nil),                             // 5: namespace.private.sessions.v1beta.Session
	(*durationpb.Duration)(nil),                 // 6: google.protobuf.Duration
	(*emptypb.Empty)(nil),                       // 7: google.protobuf.Empty
}
var file_proto_namespace_private_sessions_users_proto_depIdxs = []int32{
	5, // 0: namespace.private.sessions.v1beta.ListSessionsResponse.session:type_name -> namespace.private.sessions.v1beta.Session
	6, // 1: namespace.private.sessions.v1beta.IssueTenantTokenFromSessionRequest.token_duration:type_name -> google.protobuf.Duration
	7, // 2: namespace.private.sessions.v1beta.UserSessionsService.ListSessions:input_type -> google.protobuf.Empty
	1, // 3: namespace.private.sessions.v1beta.UserSessionsService.InvalidateSession:input_type -> namespace.private.sessions.v1beta.InvalidateSessionRequest
	7, // 4: namespace.private.sessions.v1beta.UserSessionsService.InvalidateAllSessions:input_type -> google.protobuf.Empty
	3, // 5: namespace.private.sessions.v1beta.UserSessionsService.IssueTenantTokenFromSession:input_type -> namespace.private.sessions.v1beta.IssueTenantTokenFromSessionRequest
	0, // 6: namespace.private.sessions.v1beta.UserSessionsService.ListSessions:output_type -> namespace.private.sessions.v1beta.ListSessionsResponse
	7, // 7: namespace.private.sessions.v1beta.UserSessionsService.InvalidateSession:output_type -> google.protobuf.Empty
	2, // 8: namespace.private.sessions.v1beta.UserSessionsService.InvalidateAllSessions:output_type -> namespace.private.sessions.v1beta.InvalidateAllSessionsResponse
	4, // 9: namespace.private.sessions.v1beta.UserSessionsService.IssueTenantTokenFromSession:output_type -> namespace.private.sessions.v1beta.IssueTenantTokenFromSessionResponse
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_namespace_private_sessions_users_proto_init() }
func file_proto_namespace_private_sessions_users_proto_init() {
	if File_proto_namespace_private_sessions_users_proto != nil {
		return
	}
	file_proto_namespace_private_sessions_session_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_namespace_private_sessions_users_proto_rawDesc), len(file_proto_namespace_private_sessions_users_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_namespace_private_sessions_users_proto_goTypes,
		DependencyIndexes: file_proto_namespace_private_sessions_users_proto_depIdxs,
		MessageInfos:      file_proto_namespace_private_sessions_users_proto_msgTypes,
	}.Build()
	File_proto_namespace_private_sessions_users_proto = out.File
	file_proto_namespace_private_sessions_users_proto_goTypes = nil
	file_proto_namespace_private_sessions_users_proto_depIdxs = nil
}
