// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: proto/namespace/cloud/storage/v1beta/artifact.proto

package storagev1betaconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	v1beta "namespacelabs.dev/integrations/proto/namespace/cloud/storage/v1beta"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// ArtifactsServiceName is the fully-qualified name of the ArtifactsService service.
	ArtifactsServiceName = "namespace.cloud.storage.v1beta.ArtifactsService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// ArtifactsServiceCreateArtifactProcedure is the fully-qualified name of the ArtifactsService's
	// CreateArtifact RPC.
	ArtifactsServiceCreateArtifactProcedure = "/namespace.cloud.storage.v1beta.ArtifactsService/CreateArtifact"
	// ArtifactsServiceFinalizeArtifactProcedure is the fully-qualified name of the ArtifactsService's
	// FinalizeArtifact RPC.
	ArtifactsServiceFinalizeArtifactProcedure = "/namespace.cloud.storage.v1beta.ArtifactsService/FinalizeArtifact"
	// ArtifactsServiceResolveArtifactProcedure is the fully-qualified name of the ArtifactsService's
	// ResolveArtifact RPC.
	ArtifactsServiceResolveArtifactProcedure = "/namespace.cloud.storage.v1beta.ArtifactsService/ResolveArtifact"
	// ArtifactsServiceListArtifactsProcedure is the fully-qualified name of the ArtifactsService's
	// ListArtifacts RPC.
	ArtifactsServiceListArtifactsProcedure = "/namespace.cloud.storage.v1beta.ArtifactsService/ListArtifacts"
	// ArtifactsServiceListNamespacesProcedure is the fully-qualified name of the ArtifactsService's
	// ListNamespaces RPC.
	ArtifactsServiceListNamespacesProcedure = "/namespace.cloud.storage.v1beta.ArtifactsService/ListNamespaces"
	// ArtifactsServiceExpireArtifactProcedure is the fully-qualified name of the ArtifactsService's
	// ExpireArtifact RPC.
	ArtifactsServiceExpireArtifactProcedure = "/namespace.cloud.storage.v1beta.ArtifactsService/ExpireArtifact"
	// ArtifactsServiceExtendArtifactProcedure is the fully-qualified name of the ArtifactsService's
	// ExtendArtifact RPC.
	ArtifactsServiceExtendArtifactProcedure = "/namespace.cloud.storage.v1beta.ArtifactsService/ExtendArtifact"
)

// These variables are the protoreflect.Descriptor objects for the RPCs defined in this package.
var (
	artifactsServiceServiceDescriptor                = v1beta.File_proto_namespace_cloud_storage_v1beta_artifact_proto.Services().ByName("ArtifactsService")
	artifactsServiceCreateArtifactMethodDescriptor   = artifactsServiceServiceDescriptor.Methods().ByName("CreateArtifact")
	artifactsServiceFinalizeArtifactMethodDescriptor = artifactsServiceServiceDescriptor.Methods().ByName("FinalizeArtifact")
	artifactsServiceResolveArtifactMethodDescriptor  = artifactsServiceServiceDescriptor.Methods().ByName("ResolveArtifact")
	artifactsServiceListArtifactsMethodDescriptor    = artifactsServiceServiceDescriptor.Methods().ByName("ListArtifacts")
	artifactsServiceListNamespacesMethodDescriptor   = artifactsServiceServiceDescriptor.Methods().ByName("ListNamespaces")
	artifactsServiceExpireArtifactMethodDescriptor   = artifactsServiceServiceDescriptor.Methods().ByName("ExpireArtifact")
	artifactsServiceExtendArtifactMethodDescriptor   = artifactsServiceServiceDescriptor.Methods().ByName("ExtendArtifact")
)

// ArtifactsServiceClient is a client for the namespace.cloud.storage.v1beta.ArtifactsService
// service.
type ArtifactsServiceClient interface {
	// Creates a new artifact and returns a signed upload URL.
	//
	// Artifact creation follows a two-phase commit model:
	// 1. Call CreateArtifact to obtain a `signed_upload_url` and `upload_id`.
	// 2. Upload the artifact data to the signed URL using an HTTP PUT request.
	// 3. Call FinalizeArtifact with the `upload_id` to commit the artifact.
	//
	// The artifact is not accessible for download until finalized.
	CreateArtifact(context.Context, *connect.Request[v1beta.CreateArtifactRequest]) (*connect.Response[v1beta.CreateArtifactResponse], error)
	// Finalize a fully uploaded artifact (making it available for download).
	FinalizeArtifact(context.Context, *connect.Request[v1beta.FinalizeArtifactRequest]) (*connect.Response[v1beta.FinalizeArtifactResponse], error)
	// Resolves a finalized artifact and generates a download URL.
	ResolveArtifact(context.Context, *connect.Request[v1beta.ResolveArtifactRequest]) (*connect.Response[v1beta.ResolveArtifactResponse], error)
	// List finalized artifacts.
	ListArtifacts(context.Context, *connect.Request[v1beta.ListArtifactsRequest]) (*connect.Response[v1beta.ListArtifactsResponse], error)
	// List namespaces with finalized artifacts.
	ListNamespaces(context.Context, *connect.Request[v1beta.ListNamespacesRequest]) (*connect.Response[v1beta.ListNamespacesResponse], error)
	// Mark an artifact as eligible for garbage-collection.
	ExpireArtifact(context.Context, *connect.Request[v1beta.ExpireArtifactRequest]) (*connect.Response[emptypb.Empty], error)
	// Extend the expiration of a finalized artifact.
	//
	// This enables dynamic, access-based retention: create artifacts with a
	// short expiration and push it out whenever they are accessed.
	//
	// ### Errors
	//   - If the artifact does not exist or has already expired, a `NotFound`
	//     status is returned.
	ExtendArtifact(context.Context, *connect.Request[v1beta.ExtendArtifactRequest]) (*connect.Response[v1beta.ExtendArtifactResponse], error)
}

// NewArtifactsServiceClient constructs a client for the
// namespace.cloud.storage.v1beta.ArtifactsService service. By default, it uses the Connect protocol
// with the binary Protobuf Codec, asks for gzipped responses, and sends uncompressed requests. To
// use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or connect.WithGRPCWeb()
// options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewArtifactsServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) ArtifactsServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	return &artifactsServiceClient{
		createArtifact: connect.NewClient[v1beta.CreateArtifactRequest, v1beta.CreateArtifactResponse](
			httpClient,
			baseURL+ArtifactsServiceCreateArtifactProcedure,
			connect.WithSchema(artifactsServiceCreateArtifactMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		finalizeArtifact: connect.NewClient[v1beta.FinalizeArtifactRequest, v1beta.FinalizeArtifactResponse](
			httpClient,
			baseURL+ArtifactsServiceFinalizeArtifactProcedure,
			connect.WithSchema(artifactsServiceFinalizeArtifactMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		resolveArtifact: connect.NewClient[v1beta.ResolveArtifactRequest, v1beta.ResolveArtifactResponse](
			httpClient,
			baseURL+ArtifactsServiceResolveArtifactProcedure,
			connect.WithSchema(artifactsServiceResolveArtifactMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		listArtifacts: connect.NewClient[v1beta.ListArtifactsRequest, v1beta.ListArtifactsResponse](
			httpClient,
			baseURL+ArtifactsServiceListArtifactsProcedure,
			connect.WithSchema(artifactsServiceListArtifactsMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		listNamespaces: connect.NewClient[v1beta.ListNamespacesRequest, v1beta.ListNamespacesResponse](
			httpClient,
			baseURL+ArtifactsServiceListNamespacesProcedure,
			connect.WithSchema(artifactsServiceListNamespacesMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		expireArtifact: connect.NewClient[v1beta.ExpireArtifactRequest, emptypb.Empty](
			httpClient,
			baseURL+ArtifactsServiceExpireArtifactProcedure,
			connect.WithSchema(artifactsServiceExpireArtifactMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		extendArtifact: connect.NewClient[v1beta.ExtendArtifactRequest, v1beta.ExtendArtifactResponse](
			httpClient,
			baseURL+ArtifactsServiceExtendArtifactProcedure,
			connect.WithSchema(artifactsServiceExtendArtifactMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
	}
}

// artifactsServiceClient implements ArtifactsServiceClient.
type artifactsServiceClient struct {
	createArtifact   *connect.Client[v1beta.CreateArtifactRequest, v1beta.CreateArtifactResponse]
	finalizeArtifact *connect.Client[v1beta.FinalizeArtifactRequest, v1beta.FinalizeArtifactResponse]
	resolveArtifact  *connect.Client[v1beta.ResolveArtifactRequest, v1beta.ResolveArtifactResponse]
	listArtifacts    *connect.Client[v1beta.ListArtifactsRequest, v1beta.ListArtifactsResponse]
	listNamespaces   *connect.Client[v1beta.ListNamespacesRequest, v1beta.ListNamespacesResponse]
	expireArtifact   *connect.Client[v1beta.ExpireArtifactRequest, emptypb.Empty]
	extendArtifact   *connect.Client[v1beta.ExtendArtifactRequest, v1beta.ExtendArtifactResponse]
}

// CreateArtifact calls namespace.cloud.storage.v1beta.ArtifactsService.CreateArtifact.
func (c *artifactsServiceClient) CreateArtifact(ctx context.Context, req *connect.Request[v1beta.CreateArtifactRequest]) (*connect.Response[v1beta.CreateArtifactResponse], error) {
	return c.createArtifact.CallUnary(ctx, req)
}

// FinalizeArtifact calls namespace.cloud.storage.v1beta.ArtifactsService.FinalizeArtifact.
func (c *artifactsServiceClient) FinalizeArtifact(ctx context.Context, req *connect.Request[v1beta.FinalizeArtifactRequest]) (*connect.Response[v1beta.FinalizeArtifactResponse], error) {
	return c.finalizeArtifact.CallUnary(ctx, req)
}

// ResolveArtifact calls namespace.cloud.storage.v1beta.ArtifactsService.ResolveArtifact.
func (c *artifactsServiceClient) ResolveArtifact(ctx context.Context, req *connect.Request[v1beta.ResolveArtifactRequest]) (*connect.Response[v1beta.ResolveArtifactResponse], error) {
	return c.resolveArtifact.CallUnary(ctx, req)
}

// ListArtifacts calls namespace.cloud.storage.v1beta.ArtifactsService.ListArtifacts.
func (c *artifactsServiceClient) ListArtifacts(ctx context.Context, req *connect.Request[v1beta.ListArtifactsRequest]) (*connect.Response[v1beta.ListArtifactsResponse], error) {
	return c.listArtifacts.CallUnary(ctx, req)
}

// ListNamespaces calls namespace.cloud.storage.v1beta.ArtifactsService.ListNamespaces.
func (c *artifactsServiceClient) ListNamespaces(ctx context.Context, req *connect.Request[v1beta.ListNamespacesRequest]) (*connect.Response[v1beta.ListNamespacesResponse], error) {
	return c.listNamespaces.CallUnary(ctx, req)
}

// ExpireArtifact calls namespace.cloud.storage.v1beta.ArtifactsService.ExpireArtifact.
func (c *artifactsServiceClient) ExpireArtifact(ctx context.Context, req *connect.Request[v1beta.ExpireArtifactRequest]) (*connect.Response[emptypb.Empty], error) {
	return c.expireArtifact.CallUnary(ctx, req)
}

// ExtendArtifact calls namespace.cloud.storage.v1beta.ArtifactsService.ExtendArtifact.
func (c *artifactsServiceClient) ExtendArtifact(ctx context.Context, req *connect.Request[v1beta.ExtendArtifactRequest]) (*connect.Response[v1beta.ExtendArtifactResponse], error) {
	return c.extendArtifact.CallUnary(ctx, req)
}

// ArtifactsServiceHandler is an implementation of the
// namespace.cloud.storage.v1beta.ArtifactsService service.
type ArtifactsServiceHandler interface {
	// Creates a new artifact and returns a signed upload URL.
	//
	// Artifact creation follows a two-phase commit model:
	// 1. Call CreateArtifact to obtain a `signed_upload_url` and `upload_id`.
	// 2. Upload the artifact data to the signed URL using an HTTP PUT request.
	// 3. Call FinalizeArtifact with the `upload_id` to commit the artifact.
	//
	// The artifact is not accessible for download until finalized.
	CreateArtifact(context.Context, *connect.Request[v1beta.CreateArtifactRequest]) (*connect.Response[v1beta.CreateArtifactResponse], error)
	// Finalize a fully uploaded artifact (making it available for download).
	FinalizeArtifact(context.Context, *connect.Request[v1beta.FinalizeArtifactRequest]) (*connect.Response[v1beta.FinalizeArtifactResponse], error)
	// Resolves a finalized artifact and generates a download URL.
	ResolveArtifact(context.Context, *connect.Request[v1beta.ResolveArtifactRequest]) (*connect.Response[v1beta.ResolveArtifactResponse], error)
	// List finalized artifacts.
	ListArtifacts(context.Context, *connect.Request[v1beta.ListArtifactsRequest]) (*connect.Response[v1beta.ListArtifactsResponse], error)
	// List namespaces with finalized artifacts.
	ListNamespaces(context.Context, *connect.Request[v1beta.ListNamespacesRequest]) (*connect.Response[v1beta.ListNamespacesResponse], error)
	// Mark an artifact as eligible for garbage-collection.
	ExpireArtifact(context.Context, *connect.Request[v1beta.ExpireArtifactRequest]) (*connect.Response[emptypb.Empty], error)
	// Extend the expiration of a finalized artifact.
	//
	// This enables dynamic, access-based retention: create artifacts with a
	// short expiration and push it out whenever they are accessed.
	//
	// ### Errors
	//   - If the artifact does not exist or has already expired, a `NotFound`
	//     status is returned.
	ExtendArtifact(context.Context, *connect.Request[v1beta.ExtendArtifactRequest]) (*connect.Response[v1beta.ExtendArtifactResponse], error)
}

// NewArtifactsServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewArtifactsServiceHandler(svc ArtifactsServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	artifactsServiceCreateArtifactHandler := connect.NewUnaryHandler(
		ArtifactsServiceCreateArtifactProcedure,
		svc.CreateArtifact,
		connect.WithSchema(artifactsServiceCreateArtifactMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	artifactsServiceFinalizeArtifactHandler := connect.NewUnaryHandler(
		ArtifactsServiceFinalizeArtifactProcedure,
		svc.FinalizeArtifact,
		connect.WithSchema(artifactsServiceFinalizeArtifactMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	artifactsServiceResolveArtifactHandler := connect.NewUnaryHandler(
		ArtifactsServiceResolveArtifactProcedure,
		svc.ResolveArtifact,
		connect.WithSchema(artifactsServiceResolveArtifactMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	artifactsServiceListArtifactsHandler := connect.NewUnaryHandler(
		ArtifactsServiceListArtifactsProcedure,
		svc.ListArtifacts,
		connect.WithSchema(artifactsServiceListArtifactsMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	artifactsServiceListNamespacesHandler := connect.NewUnaryHandler(
		ArtifactsServiceListNamespacesProcedure,
		svc.ListNamespaces,
		connect.WithSchema(artifactsServiceListNamespacesMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	artifactsServiceExpireArtifactHandler := connect.NewUnaryHandler(
		ArtifactsServiceExpireArtifactProcedure,
		svc.ExpireArtifact,
		connect.WithSchema(artifactsServiceExpireArtifactMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	artifactsServiceExtendArtifactHandler := connect.NewUnaryHandler(
		ArtifactsServiceExtendArtifactProcedure,
		svc.ExtendArtifact,
		connect.WithSchema(artifactsServiceExtendArtifactMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	return "/namespace.cloud.storage.v1beta.ArtifactsService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case ArtifactsServiceCreateArtifactProcedure:
			artifactsServiceCreateArtifactHandler.ServeHTTP(w, r)
		case ArtifactsServiceFinalizeArtifactProcedure:
			artifactsServiceFinalizeArtifactHandler.ServeHTTP(w, r)
		case ArtifactsServiceResolveArtifactProcedure:
			artifactsServiceResolveArtifactHandler.ServeHTTP(w, r)
		case ArtifactsServiceListArtifactsProcedure:
			artifactsServiceListArtifactsHandler.ServeHTTP(w, r)
		case ArtifactsServiceListNamespacesProcedure:
			artifactsServiceListNamespacesHandler.ServeHTTP(w, r)
		case ArtifactsServiceExpireArtifactProcedure:
			artifactsServiceExpireArtifactHandler.ServeHTTP(w, r)
		case ArtifactsServiceExtendArtifactProcedure:
			artifactsServiceExtendArtifactHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedArtifactsServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedArtifactsServiceHandler struct{}

func (UnimplementedArtifactsServiceHandler) CreateArtifact(context.Context, *connect.Request[v1beta.CreateArtifactRequest]) (*connect.Response[v1beta.CreateArtifactResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("namespace.cloud.storage.v1beta.ArtifactsService.CreateArtifact is not implemented"))
}

func (UnimplementedArtifactsServiceHandler) FinalizeArtifact(context.Context, *connect.Request[v1beta.FinalizeArtifactRequest]) (*connect.Response[v1beta.FinalizeArtifactResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("namespace.cloud.storage.v1beta.ArtifactsService.FinalizeArtifact is not implemented"))
}

func (UnimplementedArtifactsServiceHandler) ResolveArtifact(context.Context, *connect.Request[v1beta.ResolveArtifactRequest]) (*connect.Response[v1beta.ResolveArtifactResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("namespace.cloud.storage.v1beta.ArtifactsService.ResolveArtifact is not implemented"))
}

func (UnimplementedArtifactsServiceHandler) ListArtifacts(context.Context, *connect.Request[v1beta.ListArtifactsRequest]) (*connect.Response[v1beta.ListArtifactsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("namespace.cloud.storage.v1beta.ArtifactsService.ListArtifacts is not implemented"))
}

func (UnimplementedArtifactsServiceHandler) ListNamespaces(context.Context, *connect.Request[v1beta.ListNamespacesRequest]) (*connect.Response[v1beta.ListNamespacesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("namespace.cloud.storage.v1beta.ArtifactsService.ListNamespaces is not implemented"))
}

func (UnimplementedArtifactsServiceHandler) ExpireArtifact(context.Context, *connect.Request[v1beta.ExpireArtifactRequest]) (*connect.Response[emptypb.Empty], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("namespace.cloud.storage.v1beta.ArtifactsService.ExpireArtifact is not implemented"))
}

func (UnimplementedArtifactsServiceHandler) ExtendArtifact(context.Context, *connect.Request[v1beta.ExtendArtifactRequest]) (*connect.Response[v1beta.ExtendArtifactResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("namespace.cloud.storage.v1beta.ArtifactsService.ExtendArtifact is not implemented"))
}
