// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: proto/namespace/private/sessions/users.proto

package sessionsv1betaconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	sessions "namespacelabs.dev/integrations/proto/namespace/private/sessions"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// UserSessionsServiceName is the fully-qualified name of the UserSessionsService service.
	UserSessionsServiceName = "namespace.private.sessions.v1beta.UserSessionsService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// UserSessionsServiceListSessionsProcedure is the fully-qualified name of the UserSessionsService's
	// ListSessions RPC.
	UserSessionsServiceListSessionsProcedure = "/namespace.private.sessions.v1beta.UserSessionsService/ListSessions"
	// UserSessionsServiceInvalidateSessionProcedure is the fully-qualified name of the
	// UserSessionsService's InvalidateSession RPC.
	UserSessionsServiceInvalidateSessionProcedure = "/namespace.private.sessions.v1beta.UserSessionsService/InvalidateSession"
	// UserSessionsServiceInvalidateAllSessionsProcedure is the fully-qualified name of the
	// UserSessionsService's InvalidateAllSessions RPC.
	UserSessionsServiceInvalidateAllSessionsProcedure = "/namespace.private.sessions.v1beta.UserSessionsService/InvalidateAllSessions"
	// UserSessionsServiceIssueTenantTokenFromSessionProcedure is the fully-qualified name of the
	// UserSessionsService's IssueTenantTokenFromSession RPC.
	UserSessionsServiceIssueTenantTokenFromSessionProcedure = "/namespace.private.sessions.v1beta.UserSessionsService/IssueTenantTokenFromSession"
)

// These variables are the protoreflect.Descriptor objects for the RPCs defined in this package.
var (
	userSessionsServiceServiceDescriptor                           = sessions.File_proto_namespace_private_sessions_users_proto.Services().ByName("UserSessionsService")
	userSessionsServiceListSessionsMethodDescriptor                = userSessionsServiceServiceDescriptor.Methods().ByName("ListSessions")
	userSessionsServiceInvalidateSessionMethodDescriptor           = userSessionsServiceServiceDescriptor.Methods().ByName("InvalidateSession")
	userSessionsServiceInvalidateAllSessionsMethodDescriptor       = userSessionsServiceServiceDescriptor.Methods().ByName("InvalidateAllSessions")
	userSessionsServiceIssueTenantTokenFromSessionMethodDescriptor = userSessionsServiceServiceDescriptor.Methods().ByName("IssueTenantTokenFromSession")
)

// UserSessionsServiceClient is a client for the
// namespace.private.sessions.v1beta.UserSessionsService service.
type UserSessionsServiceClient interface {
	ListSessions(context.Context, *connect.Request[emptypb.Empty]) (*connect.Response[sessions.ListSessionsResponse], error)
	InvalidateSession(context.Context, *connect.Request[sessions.InvalidateSessionRequest]) (*connect.Response[emptypb.Empty], error)
	InvalidateAllSessions(context.Context, *connect.Request[emptypb.Empty]) (*connect.Response[sessions.InvalidateAllSessionsResponse], error)
	IssueTenantTokenFromSession(context.Context, *connect.Request[sessions.IssueTenantTokenFromSessionRequest]) (*connect.Response[sessions.IssueTenantTokenFromSessionResponse], error)
}

// NewUserSessionsServiceClient constructs a client for the
// namespace.private.sessions.v1beta.UserSessionsService service. By default, it uses the Connect
// protocol with the binary Protobuf Codec, asks for gzipped responses, and sends uncompressed
// requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewUserSessionsServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) UserSessionsServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	return &userSessionsServiceClient{
		listSessions: connect.NewClient[emptypb.Empty, sessions.ListSessionsResponse](
			httpClient,
			baseURL+UserSessionsServiceListSessionsProcedure,
			connect.WithSchema(userSessionsServiceListSessionsMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		invalidateSession: connect.NewClient[sessions.InvalidateSessionRequest, emptypb.Empty](
			httpClient,
			baseURL+UserSessionsServiceInvalidateSessionProcedure,
			connect.WithSchema(userSessionsServiceInvalidateSessionMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		invalidateAllSessions: connect.NewClient[emptypb.Empty, sessions.InvalidateAllSessionsResponse](
			httpClient,
			baseURL+UserSessionsServiceInvalidateAllSessionsProcedure,
			connect.WithSchema(userSessionsServiceInvalidateAllSessionsMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		issueTenantTokenFromSession: connect.NewClient[sessions.IssueTenantTokenFromSessionRequest, sessions.IssueTenantTokenFromSessionResponse](
			httpClient,
			baseURL+UserSessionsServiceIssueTenantTokenFromSessionProcedure,
			connect.WithSchema(userSessionsServiceIssueTenantTokenFromSessionMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
	}
}

// userSessionsServiceClient implements UserSessionsServiceClient.
type userSessionsServiceClient struct {
	listSessions                *connect.Client[emptypb.Empty, sessions.ListSessionsResponse]
	invalidateSession           *connect.Client[sessions.InvalidateSessionRequest, emptypb.Empty]
	invalidateAllSessions       *connect.Client[emptypb.Empty, sessions.InvalidateAllSessionsResponse]
	issueTenantTokenFromSession *connect.Client[sessions.IssueTenantTokenFromSessionRequest, sessions.IssueTenantTokenFromSessionResponse]
}

// ListSessions calls namespace.private.sessions.v1beta.UserSessionsService.ListSessions.
func (c *userSessionsServiceClient) ListSessions(ctx context.Context, req *connect.Request[emptypb.Empty]) (*connect.Response[sessions.ListSessionsResponse], error) {
	return c.listSessions.CallUnary(ctx, req)
}

// InvalidateSession calls namespace.private.sessions.v1beta.UserSessionsService.InvalidateSession.
func (c *userSessionsServiceClient) InvalidateSession(ctx context.Context, req *connect.Request[sessions.InvalidateSessionRequest]) (*connect.Response[emptypb.Empty], error) {
	return c.invalidateSession.CallUnary(ctx, req)
}

// InvalidateAllSessions calls
// namespace.private.sessions.v1beta.UserSessionsService.InvalidateAllSessions.
func (c *userSessionsServiceClient) InvalidateAllSessions(ctx context.Context, req *connect.Request[emptypb.Empty]) (*connect.Response[sessions.InvalidateAllSessionsResponse], error) {
	return c.invalidateAllSessions.CallUnary(ctx, req)
}

// IssueTenantTokenFromSession calls
// namespace.private.sessions.v1beta.UserSessionsService.IssueTenantTokenFromSession.
func (c *userSessionsServiceClient) IssueTenantTokenFromSession(ctx context.Context, req *connect.Request[sessions.IssueTenantTokenFromSessionRequest]) (*connect.Response[sessions.IssueTenantTokenFromSessionResponse], error) {
	return c.issueTenantTokenFromSession.CallUnary(ctx, req)
}

// UserSessionsServiceHandler is an implementation of the
// namespace.private.sessions.v1beta.UserSessionsService service.
type UserSessionsServiceHandler interface {
	ListSessions(context.Context, *connect.Request[emptypb.Empty]) (*connect.Response[sessions.ListSessionsResponse], error)
	InvalidateSession(context.Context, *connect.Request[sessions.InvalidateSessionRequest]) (*connect.Response[emptypb.Empty], error)
	InvalidateAllSessions(context.Context, *connect.Request[emptypb.Empty]) (*connect.Response[sessions.InvalidateAllSessionsResponse], error)
	IssueTenantTokenFromSession(context.Context, *connect.Request[sessions.IssueTenantTokenFromSessionRequest]) (*connect.Response[sessions.IssueTenantTokenFromSessionResponse], error)
}

// NewUserSessionsServiceHandler builds an HTTP handler from the service implementation. It returns
// the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewUserSessionsServiceHandler(svc UserSessionsServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	userSessionsServiceListSessionsHandler := connect.NewUnaryHandler(
		UserSessionsServiceListSessionsProcedure,
		svc.ListSessions,
		connect.WithSchema(userSessionsServiceListSessionsMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	userSessionsServiceInvalidateSessionHandler := connect.NewUnaryHandler(
		UserSessionsServiceInvalidateSessionProcedure,
		svc.InvalidateSession,
		connect.WithSchema(userSessionsServiceInvalidateSessionMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	userSessionsServiceInvalidateAllSessionsHandler := connect.NewUnaryHandler(
		UserSessionsServiceInvalidateAllSessionsProcedure,
		svc.InvalidateAllSessions,
		connect.WithSchema(userSessionsServiceInvalidateAllSessionsMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	userSessionsServiceIssueTenantTokenFromSessionHandler := connect.NewUnaryHandler(
		UserSessionsServiceIssueTenantTokenFromSessionProcedure,
		svc.IssueTenantTokenFromSession,
		connect.WithSchema(userSessionsServiceIssueTenantTokenFromSessionMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	return "/namespace.private.sessions.v1beta.UserSessionsService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case UserSessionsServiceListSessionsProcedure:
			userSessionsServiceListSessionsHandler.ServeHTTP(w, r)
		case UserSessionsServiceInvalidateSessionProcedure:
			userSessionsServiceInvalidateSessionHandler.ServeHTTP(w, r)
		case UserSessionsServiceInvalidateAllSessionsProcedure:
			userSessionsServiceInvalidateAllSessionsHandler.ServeHTTP(w, r)
		case UserSessionsServiceIssueTenantTokenFromSessionProcedure:
			userSessionsServiceIssueTenantTokenFromSessionHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedUserSessionsServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedUserSessionsServiceHandler struct{}

func (UnimplementedUserSessionsServiceHandler) ListSessions(context.Context, *connect.Request[emptypb.Empty]) (*connect.Response[sessions.ListSessionsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("namespace.private.sessions.v1beta.UserSessionsService.ListSessions is not implemented"))
}

func (UnimplementedUserSessionsServiceHandler) InvalidateSession(context.Context, *connect.Request[sessions.InvalidateSessionRequest]) (*connect.Response[emptypb.Empty], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("namespace.private.sessions.v1beta.UserSessionsService.InvalidateSession is not implemented"))
}

func (UnimplementedUserSessionsServiceHandler) InvalidateAllSessions(context.Context, *connect.Request[emptypb.Empty]) (*connect.Response[sessions.InvalidateAllSessionsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("namespace.private.sessions.v1beta.UserSessionsService.InvalidateAllSessions is not implemented"))
}

func (UnimplementedUserSessionsServiceHandler) IssueTenantTokenFromSession(context.Context, *connect.Request[sessions.IssueTenantTokenFromSessionRequest]) (*connect.Response[sessions.IssueTenantTokenFromSessionResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("namespace.private.sessions.v1beta.UserSessionsService.IssueTenantTokenFromSession is not implemented"))
}
