// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: proto/namespace/private/devbox/extra/extra.proto

package extrav1betaconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	extra "namespacelabs.dev/integrations/proto/namespace/private/devbox/extra"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// DevBoxExtraServiceName is the fully-qualified name of the DevBoxExtraService service.
	DevBoxExtraServiceName = "namespace.private.devbox.extra.v1beta.DevBoxExtraService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// DevBoxExtraServiceEnsureVSCodeProcedure is the fully-qualified name of the DevBoxExtraService's
	// EnsureVSCode RPC.
	DevBoxExtraServiceEnsureVSCodeProcedure = "/namespace.private.devbox.extra.v1beta.DevBoxExtraService/EnsureVSCode"
)

// These variables are the protoreflect.Descriptor objects for the RPCs defined in this package.
var (
	devBoxExtraServiceServiceDescriptor            = extra.File_proto_namespace_private_devbox_extra_extra_proto.Services().ByName("DevBoxExtraService")
	devBoxExtraServiceEnsureVSCodeMethodDescriptor = devBoxExtraServiceServiceDescriptor.Methods().ByName("EnsureVSCode")
)

// DevBoxExtraServiceClient is a client for the
// namespace.private.devbox.extra.v1beta.DevBoxExtraService service.
type DevBoxExtraServiceClient interface {
	EnsureVSCode(context.Context, *connect.Request[extra.EnsureVSCodeRequest]) (*connect.Response[extra.EnsureVSCodeResponse], error)
}

// NewDevBoxExtraServiceClient constructs a client for the
// namespace.private.devbox.extra.v1beta.DevBoxExtraService service. By default, it uses the Connect
// protocol with the binary Protobuf Codec, asks for gzipped responses, and sends uncompressed
// requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewDevBoxExtraServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) DevBoxExtraServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	return &devBoxExtraServiceClient{
		ensureVSCode: connect.NewClient[extra.EnsureVSCodeRequest, extra.EnsureVSCodeResponse](
			httpClient,
			baseURL+DevBoxExtraServiceEnsureVSCodeProcedure,
			connect.WithSchema(devBoxExtraServiceEnsureVSCodeMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
	}
}

// devBoxExtraServiceClient implements DevBoxExtraServiceClient.
type devBoxExtraServiceClient struct {
	ensureVSCode *connect.Client[extra.EnsureVSCodeRequest, extra.EnsureVSCodeResponse]
}

// EnsureVSCode calls namespace.private.devbox.extra.v1beta.DevBoxExtraService.EnsureVSCode.
func (c *devBoxExtraServiceClient) EnsureVSCode(ctx context.Context, req *connect.Request[extra.EnsureVSCodeRequest]) (*connect.Response[extra.EnsureVSCodeResponse], error) {
	return c.ensureVSCode.CallUnary(ctx, req)
}

// DevBoxExtraServiceHandler is an implementation of the
// namespace.private.devbox.extra.v1beta.DevBoxExtraService service.
type DevBoxExtraServiceHandler interface {
	EnsureVSCode(context.Context, *connect.Request[extra.EnsureVSCodeRequest]) (*connect.Response[extra.EnsureVSCodeResponse], error)
}

// NewDevBoxExtraServiceHandler builds an HTTP handler from the service implementation. It returns
// the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewDevBoxExtraServiceHandler(svc DevBoxExtraServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	devBoxExtraServiceEnsureVSCodeHandler := connect.NewUnaryHandler(
		DevBoxExtraServiceEnsureVSCodeProcedure,
		svc.EnsureVSCode,
		connect.WithSchema(devBoxExtraServiceEnsureVSCodeMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	return "/namespace.private.devbox.extra.v1beta.DevBoxExtraService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case DevBoxExtraServiceEnsureVSCodeProcedure:
			devBoxExtraServiceEnsureVSCodeHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedDevBoxExtraServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedDevBoxExtraServiceHandler struct{}

func (UnimplementedDevBoxExtraServiceHandler) EnsureVSCode(context.Context, *connect.Request[extra.EnsureVSCodeRequest]) (*connect.Response[extra.EnsureVSCodeResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("namespace.private.devbox.extra.v1beta.DevBoxExtraService.EnsureVSCode is not implemented"))
}
