// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: proto/namespace/cloud/iam/v1beta/tokens.proto

package iamv1beta

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RevokableToken_Scope int32

const (
	RevokableToken_SCOPE_UNKNOWN           RevokableToken_Scope = 0
	RevokableToken_TENANT_SCOPE            RevokableToken_Scope = 1 // default scope if not selected
	RevokableToken_TENANT_MEMBERSHIP_SCOPE RevokableToken_Scope = 2
)

// Enum value maps for RevokableToken_Scope.
var (
	RevokableToken_Scope_name = map[int32]string{
		0: "SCOPE_UNKNOWN",
		1: "TENANT_SCOPE",
		2: "TENANT_MEMBERSHIP_SCOPE",
	}
	RevokableToken_Scope_value = map[string]int32{
		"SCOPE_UNKNOWN":           0,
		"TENANT_SCOPE":            1,
		"TENANT_MEMBERSHIP_SCOPE": 2,
	}
)

func (x RevokableToken_Scope) Enum() *RevokableToken_Scope {
	p := new(RevokableToken_Scope)
	*p = x
	return p
}

func (x RevokableToken_Scope) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RevokableToken_Scope) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_namespace_cloud_iam_v1beta_tokens_proto_enumTypes[0].Descriptor()
}

func (RevokableToken_Scope) Type() protoreflect.EnumType {
	return &file_proto_namespace_cloud_iam_v1beta_tokens_proto_enumTypes[0]
}

func (x RevokableToken_Scope) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RevokableToken_Scope.Descriptor instead.
func (RevokableToken_Scope) EnumDescriptor() ([]byte, []int) {
	return file_proto_namespace_cloud_iam_v1beta_tokens_proto_rawDescGZIP(), []int{14, 0}
}

type RevokableToken_State int32

const (
	RevokableToken_STATE_UNKNOWN RevokableToken_State = 0
	RevokableToken_ACTIVE        RevokableToken_State = 1
	RevokableToken_REVOKED       RevokableToken_State = 2
	RevokableToken_EXPIRED       RevokableToken_State = 3
)

// Enum value maps for RevokableToken_State.
var (
	RevokableToken_State_name = map[int32]string{
		0: "STATE_UNKNOWN",
		1: "ACTIVE",
		2: "REVOKED",
		3: "EXPIRED",
	}
	RevokableToken_State_value = map[string]int32{
		"STATE_UNKNOWN": 0,
		"ACTIVE":        1,
		"REVOKED":       2,
		"EXPIRED":       3,
	}
)

func (x RevokableToken_State) Enum() *RevokableToken_State {
	p := new(RevokableToken_State)
	*p = x
	return p
}

func (x RevokableToken_State) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RevokableToken_State) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_namespace_cloud_iam_v1beta_tokens_proto_enumTypes[1].Descriptor()
}

func (RevokableToken_State) Type() protoreflect.EnumType {
	return &file_proto_namespace_cloud_iam_v1beta_tokens_proto_enumTypes[1]
}

func (x RevokableToken_State) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RevokableToken_State.Descriptor instead.
func (RevokableToken_State) EnumDescriptor() ([]byte, []int) {
	return file_proto_namespace_cloud_iam_v1beta_tokens_proto_rawDescGZIP(), []int{14, 1}
}

type IssueIdTokenRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Target audience for the generated identity token.
	Audience      string `protobuf:"bytes,1,opt,name=audience,proto3" json:"audience,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IssueIdTokenRequest) Reset() {
	*x = IssueIdTokenRequest{}
	mi := &file_proto_namespace_cloud_iam_v1beta_tokens_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IssueIdTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IssueIdTokenRequest) ProtoMessage() {}

func (x *IssueIdTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_namespace_cloud_iam_v1beta_tokens_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IssueIdTokenRequest.ProtoReflect.Descriptor instead.
func (*IssueIdTokenRequest) Descriptor() ([]byte, []int) {
	return file_proto_namespace_cloud_iam_v1beta_tokens_proto_rawDescGZIP(), []int{0}
}

func (x *IssueIdTokenRequest) GetAudience() string {
	if x != nil {
		return x.Audience
	}
	return ""
}

type IssueIdTokenResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The signed OIDC ID token. Use this token to authenticate with external
	// services that trust the Namespace federation issuer
	// (`https://federation.namespaceapis.com`).
	IdToken       string `protobuf:"bytes,1,opt,name=id_token,json=idToken,proto3" json:"id_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IssueIdTokenResponse) Reset() {
	*x = IssueIdTokenResponse{}
	mi := &file_proto_namespace_cloud_iam_v1beta_tokens_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IssueIdTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IssueIdTokenResponse) ProtoMessage() {}

func (x *IssueIdTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_namespace_cloud_iam_v1beta_tokens_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IssueIdTokenResponse.ProtoReflect.Descriptor instead.
func (*IssueIdTokenResponse) Descriptor() ([]byte, []int) {
	return file_proto_namespace_cloud_iam_v1beta_tokens_proto_rawDescGZIP(), []int{1}
}

func (x *IssueIdTokenResponse) GetIdToken() string {
	if x != nil {
		return x.IdToken
	}
	return ""
}

type IssueTenantTokenRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Which tenant credentials should be produced for.
	TenantId string `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	// A integration-specified identifier that represents the user that is
	// requesting these credentials. The actor identity is embedded into the
	// verifiable claims of the resulting JWT.
	ActorId string `protobuf:"bytes,2,opt,name=actor_id,json=actorId,proto3" json:"actor_id,omitempty"`
	// For how long should the resulting credentials be valid for. If not
	// specified, a short-lived default is used (e.g 15mins).
	DurationSecs int64 `protobuf:"varint,3,opt,name=duration_secs,json=durationSecs,proto3" json:"duration_secs,omitempty"`
	// A set of policies that apply to this tenant token.
	Policies []*TenantTokenPolicy `protobuf:"bytes,4,rep,name=policies,proto3" json:"policies,omitempty"`
	// Configure the access permissions available with this token.
	Access        *AccessPolicy `protobuf:"bytes,5,opt,name=access,proto3" json:"access,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IssueTenantTokenRequest) Reset() {
	*x = IssueTenantTokenRequest{}
	mi := &file_proto_namespace_cloud_iam_v1beta_tokens_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IssueTenantTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IssueTenantTokenRequest) ProtoMessage() {}

func (x *IssueTenantTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_namespace_cloud_iam_v1beta_tokens_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IssueTenantTokenRequest.ProtoReflect.Descriptor instead.
func (*IssueTenantTokenRequest) Descriptor() ([]byte, []int) {
	return file_proto_namespace_cloud_iam_v1beta_tokens_proto_rawDescGZIP(), []int{2}
}

func (x *IssueTenantTokenRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *IssueTenantTokenRequest) GetActorId() string {
	if x != nil {
		return x.ActorId
	}
	return ""
}

func (x *IssueTenantTokenRequest) GetDurationSecs() int64 {
	if x != nil {
		return x.DurationSecs
	}
	return 0
}

func (x *IssueTenantTokenRequest) GetPolicies() []*TenantTokenPolicy {
	if x != nil {
		return x.Policies
	}
	return nil
}

func (x *IssueTenantTokenRequest) GetAccess() *AccessPolicy {
	if x != nil {
		return x.Access
	}
	return nil
}

type AccessPolicy struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Grant a restricted set of permissions to this token.
	// See https://namespace.so/docs/security/permissions for available permissions.
	Grants        []*Permission `protobuf:"bytes,1,rep,name=grants,proto3" json:"grants,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccessPolicy) Reset() {
	*x = AccessPolicy{}
	mi := &file_proto_namespace_cloud_iam_v1beta_tokens_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccessPolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccessPolicy) ProtoMessage() {}

func (x *AccessPolicy) ProtoReflect() protoreflect.Message {
	mi := &file_proto_namespace_cloud_iam_v1beta_tokens_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccessPolicy.ProtoReflect.Descriptor instead.
func (*AccessPolicy) Descriptor() ([]byte, []int) {
	return file_proto_namespace_cloud_iam_v1beta_tokens_proto_rawDescGZIP(), []int{3}
}

func (x *AccessPolicy) GetGrants() []*Permission {
	if x != nil {
		return x.Grants
	}
	return nil
}

type IssueTenantTokenResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The tenant Bearer token. Pass this in the `Authorization: Bearer {token}`
	// header when calling Namespace APIs.
	BearerToken   string `protobuf:"bytes,1,opt,name=bearer_token,json=bearerToken,proto3" json:"bearer_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IssueTenantTokenResponse) Reset() {
	*x = IssueTenantTokenResponse{}
	mi := &file_proto_namespace_cloud_iam_v1beta_tokens_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IssueTenantTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IssueTenantTokenResponse) ProtoMessage() {}

func (x *IssueTenantTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_namespace_cloud_iam_v1beta_tokens_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IssueTenantTokenResponse.ProtoReflect.Descriptor instead.
func (*IssueTenantTokenResponse) Descriptor() ([]byte, []int) {
	return file_proto_namespace_cloud_iam_v1beta_tokens_proto_rawDescGZIP(), []int{4}
}

func (x *IssueTenantTokenResponse) GetBearerToken() string {
	if x != nil {
		return x.BearerToken
	}
	return ""
}

type IssueTenantTokenWithOIDCRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Which tenant credentials should be produced for.
	TenantId string `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	// The OIDC token from a trusted external issuer.
	OidcToken string `protobuf:"bytes,2,opt,name=oidc_token,json=oidcToken,proto3" json:"oidc_token,omitempty"`
	// For how long the resulting credentials should be valid.
	Duration      *durationpb.Duration `protobuf:"bytes,3,opt,name=duration,proto3" json:"duration,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IssueTenantTokenWithOIDCRequest) Reset() {
	*x = IssueTenantTokenWithOIDCRequest{}
	mi := &file_proto_namespace_cloud_iam_v1beta_tokens_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IssueTenantTokenWithOIDCRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IssueTenantTokenWithOIDCRequest) ProtoMessage() {}

func (x *IssueTenantTokenWithOIDCRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_namespace_cloud_iam_v1beta_tokens_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IssueTenantTokenWithOIDCRequest.ProtoReflect.Descriptor instead.
func (*IssueTenantTokenWithOIDCRequest) Descriptor() ([]byte, []int) {
	return file_proto_namespace_cloud_iam_v1beta_tokens_proto_rawDescGZIP(), []int{5}
}

func (x *IssueTenantTokenWithOIDCRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *IssueTenantTokenWithOIDCRequest) GetOidcToken() string {
	if x != nil {
		return x.OidcToken
	}
	return ""
}

func (x *IssueTenantTokenWithOIDCRequest) GetDuration() *durationpb.Duration {
	if x != nil {
		return x.Duration
	}
	return nil
}

type TenantTokenPolicy struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The policy type being set.
	//
	// Consult with the Namespace team on which controls can be applied per tenant token.
	PolicyType string `protobuf:"bytes,1,opt,name=policy_type,json=policyType,proto3" json:"policy_type,omitempty"`
	// The policy-specific value. It may be a string, number, or serialized
	// message (e.g. JSON).
	Value         string `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TenantTokenPolicy) Reset() {
	*x = TenantTokenPolicy{}
	mi := &file_proto_namespace_cloud_iam_v1beta_tokens_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TenantTokenPolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TenantTokenPolicy) ProtoMessage() {}

func (x *TenantTokenPolicy) ProtoReflect() protoreflect.Message {
	mi := &file_proto_namespace_cloud_iam_v1beta_tokens_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TenantTokenPolicy.ProtoReflect.Descriptor instead.
func (*TenantTokenPolicy) Descriptor() ([]byte, []int) {
	return file_proto_namespace_cloud_iam_v1beta_tokens_proto_rawDescGZIP(), []int{6}
}

func (x *TenantTokenPolicy) GetPolicyType() string {
	if x != nil {
		return x.PolicyType
	}
	return ""
}

func (x *TenantTokenPolicy) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type CreateRevokableTokenRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// A unique name for the token within the tenant. Required.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// A human-readable description of the token's purpose.
	Description string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	// When the token should expire. Maximum expiration is 1 year from creation.
	// May be omitted for membership-scoped tokens to create a token with unlimited duration.
	ExpiresAt *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	// A set of policies that apply to this token.
	Policies []*TenantTokenPolicy `protobuf:"bytes,4,rep,name=policies,proto3" json:"policies,omitempty"`
	// Configure the access permissions available with this token.
	Access *AccessPolicy `protobuf:"bytes,5,opt,name=access,proto3" json:"access,omitempty"`
	// Allows restricting the scope of the issued token.
	Scope         RevokableToken_Scope `protobuf:"varint,6,opt,name=scope,proto3,enum=namespace.cloud.iam.v1beta.RevokableToken_Scope" json:"scope,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRevokableTokenRequest) Reset() {
	*x = CreateRevokableTokenRequest{}
	mi := &file_proto_namespace_cloud_iam_v1beta_tokens_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRevokableTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRevokableTokenRequest) ProtoMessage() {}

func (x *CreateRevokableTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_namespace_cloud_iam_v1beta_tokens_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRevokableTokenRequest.ProtoReflect.Descriptor instead.
func (*CreateRevokableTokenRequest) Descriptor() ([]byte, []int) {
	return file_proto_namespace_cloud_iam_v1beta_tokens_proto_rawDescGZIP(), []int{7}
}

func (x *CreateRevokableTokenRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateRevokableTokenRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateRevokableTokenRequest) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *CreateRevokableTokenRequest) GetPolicies() []*TenantTokenPolicy {
	if x != nil {
		return x.Policies
	}
	return nil
}

func (x *CreateRevokableTokenRequest) GetAccess() *AccessPolicy {
	if x != nil {
		return x.Access
	}
	return nil
}

func (x *CreateRevokableTokenRequest) GetScope() RevokableToken_Scope {
	if x != nil {
		return x.Scope
	}
	return RevokableToken_SCOPE_UNKNOWN
}

type CreateRevokableTokenResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The bearer token that can be used for authentication.
	// This value is only returned once at creation time and
	// cannot be retrieved later.
	BearerToken string `protobuf:"bytes,1,opt,name=bearer_token,json=bearerToken,proto3" json:"bearer_token,omitempty"`
	// The token metadata, including the token_id (prefixed with "tok_") which
	// can be used to revoke or list the token.
	Token         *RevokableToken `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRevokableTokenResponse) Reset() {
	*x = CreateRevokableTokenResponse{}
	mi := &file_proto_namespace_cloud_iam_v1beta_tokens_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRevokableTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRevokableTokenResponse) ProtoMessage() {}

func (x *CreateRevokableTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_namespace_cloud_iam_v1beta_tokens_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRevokableTokenResponse.ProtoReflect.Descriptor instead.
func (*CreateRevokableTokenResponse) Descriptor() ([]byte, []int) {
	return file_proto_namespace_cloud_iam_v1beta_tokens_proto_rawDescGZIP(), []int{8}
}

func (x *CreateRevokableTokenResponse) GetBearerToken() string {
	if x != nil {
		return x.BearerToken
	}
	return ""
}

func (x *CreateRevokableTokenResponse) GetToken() *RevokableToken {
	if x != nil {
		return x.Token
	}
	return nil
}

type RefreshRevokableTokenRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The unique identifier of the token to refresh, prefixed with "tok_".
	TokenId string `protobuf:"bytes,1,opt,name=token_id,json=tokenId,proto3" json:"token_id,omitempty"`
	// Ensure the token remains valid for at least this much longer.
	// Maximum duration is 1 year.
	MinimumDuration *durationpb.Duration `protobuf:"bytes,2,opt,name=minimum_duration,json=minimumDuration,proto3" json:"minimum_duration,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RefreshRevokableTokenRequest) Reset() {
	*x = RefreshRevokableTokenRequest{}
	mi := &file_proto_namespace_cloud_iam_v1beta_tokens_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshRevokableTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshRevokableTokenRequest) ProtoMessage() {}

func (x *RefreshRevokableTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_namespace_cloud_iam_v1beta_tokens_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshRevokableTokenRequest.ProtoReflect.Descriptor instead.
func (*RefreshRevokableTokenRequest) Descriptor() ([]byte, []int) {
	return file_proto_namespace_cloud_iam_v1beta_tokens_proto_rawDescGZIP(), []int{9}
}

func (x *RefreshRevokableTokenRequest) GetTokenId() string {
	if x != nil {
		return x.TokenId
	}
	return ""
}

func (x *RefreshRevokableTokenRequest) GetMinimumDuration() *durationpb.Duration {
	if x != nil {
		return x.MinimumDuration
	}
	return nil
}

type RefreshRevokableTokenResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The refreshed token metadata.
	Token         *RevokableToken `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshRevokableTokenResponse) Reset() {
	*x = RefreshRevokableTokenResponse{}
	mi := &file_proto_namespace_cloud_iam_v1beta_tokens_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshRevokableTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshRevokableTokenResponse) ProtoMessage() {}

func (x *RefreshRevokableTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_namespace_cloud_iam_v1beta_tokens_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshRevokableTokenResponse.ProtoReflect.Descriptor instead.
func (*RefreshRevokableTokenResponse) Descriptor() ([]byte, []int) {
	return file_proto_namespace_cloud_iam_v1beta_tokens_proto_rawDescGZIP(), []int{10}
}

func (x *RefreshRevokableTokenResponse) GetToken() *RevokableToken {
	if x != nil {
		return x.Token
	}
	return nil
}

type RevokeRevokableTokenRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The unique identifier of the token to revoke, prefixed with "tok_".
	TokenId       string `protobuf:"bytes,1,opt,name=token_id,json=tokenId,proto3" json:"token_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeRevokableTokenRequest) Reset() {
	*x = RevokeRevokableTokenRequest{}
	mi := &file_proto_namespace_cloud_iam_v1beta_tokens_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeRevokableTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeRevokableTokenRequest) ProtoMessage() {}

func (x *RevokeRevokableTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_namespace_cloud_iam_v1beta_tokens_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeRevokableTokenRequest.ProtoReflect.Descriptor instead.
func (*RevokeRevokableTokenRequest) Descriptor() ([]byte, []int) {
	return file_proto_namespace_cloud_iam_v1beta_tokens_proto_rawDescGZIP(), []int{11}
}

func (x *RevokeRevokableTokenRequest) GetTokenId() string {
	if x != nil {
		return x.TokenId
	}
	return ""
}

type ListRevokableTokensRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// If a previous response returned a `pagination_cursor`, it can be
	// specified to continue reading results with the same arguments as the
	// original call.
	PaginationCursor []byte `protobuf:"bytes,1,opt,name=pagination_cursor,json=paginationCursor,proto3" json:"pagination_cursor,omitempty"`
	// The maximum number of entries to return as part of this ListRevokableTokens
	// request. A maximum number of entries may also be specified when
	// `pagination_cursor` is set.
	//
	// We won't return more than `max_entries`, but may return fewer.
	MaxEntries int64 `protobuf:"varint,2,opt,name=max_entries,json=maxEntries,proto3" json:"max_entries,omitempty"`
	// If true, include revoked tokens in the results.
	IncludeRevoked bool `protobuf:"varint,3,opt,name=include_revoked,json=includeRevoked,proto3" json:"include_revoked,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ListRevokableTokensRequest) Reset() {
	*x = ListRevokableTokensRequest{}
	mi := &file_proto_namespace_cloud_iam_v1beta_tokens_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRevokableTokensRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRevokableTokensRequest) ProtoMessage() {}

func (x *ListRevokableTokensRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_namespace_cloud_iam_v1beta_tokens_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRevokableTokensRequest.ProtoReflect.Descriptor instead.
func (*ListRevokableTokensRequest) Descriptor() ([]byte, []int) {
	return file_proto_namespace_cloud_iam_v1beta_tokens_proto_rawDescGZIP(), []int{12}
}

func (x *ListRevokableTokensRequest) GetPaginationCursor() []byte {
	if x != nil {
		return x.PaginationCursor
	}
	return nil
}

func (x *ListRevokableTokensRequest) GetMaxEntries() int64 {
	if x != nil {
		return x.MaxEntries
	}
	return 0
}

func (x *ListRevokableTokensRequest) GetIncludeRevoked() bool {
	if x != nil {
		return x.IncludeRevoked
	}
	return false
}

type ListRevokableTokensResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The list of revokable tokens.
	Tokens []*RevokableToken `protobuf:"bytes,1,rep,name=tokens,proto3" json:"tokens,omitempty"`
	// If set, there are additional results. Pass the same cursor to a
	// subsequent ListRevokableTokens call to continue fetching results.
	PaginationCursor []byte `protobuf:"bytes,2,opt,name=pagination_cursor,json=paginationCursor,proto3" json:"pagination_cursor,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ListRevokableTokensResponse) Reset() {
	*x = ListRevokableTokensResponse{}
	mi := &file_proto_namespace_cloud_iam_v1beta_tokens_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRevokableTokensResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRevokableTokensResponse) ProtoMessage() {}

func (x *ListRevokableTokensResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_namespace_cloud_iam_v1beta_tokens_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRevokableTokensResponse.ProtoReflect.Descriptor instead.
func (*ListRevokableTokensResponse) Descriptor() ([]byte, []int) {
	return file_proto_namespace_cloud_iam_v1beta_tokens_proto_rawDescGZIP(), []int{13}
}

func (x *ListRevokableTokensResponse) GetTokens() []*RevokableToken {
	if x != nil {
		return x.Tokens
	}
	return nil
}

func (x *ListRevokableTokensResponse) GetPaginationCursor() []byte {
	if x != nil {
		return x.PaginationCursor
	}
	return nil
}

type RevokableToken struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The unique identifier for this token, prefixed with "tok_". This is used for revocation.
	TokenId string `protobuf:"bytes,1,opt,name=token_id,json=tokenId,proto3" json:"token_id,omitempty"`
	// The tenant this token belongs to.
	TenantId string `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	// A unique name for the token within the tenant.
	Name string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	// A human-readable description of the token's purpose.
	Description string `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	// When the token was created.
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// When the token expires. Tokens are implicitly invalid after this time.
	// If omitted, the membership-scoped token has unlimited duration.
	ExpiresAt *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	// If set, when the token was explicitly revoked.
	RevokedAt *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=revoked_at,json=revokedAt,proto3" json:"revoked_at,omitempty"`
	// If set, the actor who revoked the token.
	RevokedByActorId string `protobuf:"bytes,8,opt,name=revoked_by_actor_id,json=revokedByActorId,proto3" json:"revoked_by_actor_id,omitempty"`
	// The actor who created this token.
	CreatorActorId string `protobuf:"bytes,9,opt,name=creator_actor_id,json=creatorActorId,proto3" json:"creator_actor_id,omitempty"`
	// Indicates whether the token is bound to a particular membership, or tenant-wide.
	Scope RevokableToken_Scope `protobuf:"varint,10,opt,name=scope,proto3,enum=namespace.cloud.iam.v1beta.RevokableToken_Scope" json:"scope,omitempty"`
	// The permissions granted to this token.
	Permissions []*Permission `protobuf:"bytes,11,rep,name=permissions,proto3" json:"permissions,omitempty"`
	// The current state of the token.
	State         RevokableToken_State `protobuf:"varint,12,opt,name=state,proto3,enum=namespace.cloud.iam.v1beta.RevokableToken_State" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokableToken) Reset() {
	*x = RevokableToken{}
	mi := &file_proto_namespace_cloud_iam_v1beta_tokens_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokableToken) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokableToken) ProtoMessage() {}

func (x *RevokableToken) ProtoReflect() protoreflect.Message {
	mi := &file_proto_namespace_cloud_iam_v1beta_tokens_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokableToken.ProtoReflect.Descriptor instead.
func (*RevokableToken) Descriptor() ([]byte, []int) {
	return file_proto_namespace_cloud_iam_v1beta_tokens_proto_rawDescGZIP(), []int{14}
}

func (x *RevokableToken) GetTokenId() string {
	if x != nil {
		return x.TokenId
	}
	return ""
}

func (x *RevokableToken) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *RevokableToken) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RevokableToken) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *RevokableToken) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *RevokableToken) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *RevokableToken) GetRevokedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.RevokedAt
	}
	return nil
}

func (x *RevokableToken) GetRevokedByActorId() string {
	if x != nil {
		return x.RevokedByActorId
	}
	return ""
}

func (x *RevokableToken) GetCreatorActorId() string {
	if x != nil {
		return x.CreatorActorId
	}
	return ""
}

func (x *RevokableToken) GetScope() RevokableToken_Scope {
	if x != nil {
		return x.Scope
	}
	return RevokableToken_SCOPE_UNKNOWN
}

func (x *RevokableToken) GetPermissions() []*Permission {
	if x != nil {
		return x.Permissions
	}
	return nil
}

func (x *RevokableToken) GetState() RevokableToken_State {
	if x != nil {
		return x.State
	}
	return RevokableToken_STATE_UNKNOWN
}

type BatchRevokeRevokableTokenRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Revoke tokens created before this timestamp.
	// If not set, no time-based filtering is applied.
	Before *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=before,proto3" json:"before,omitempty"`
	// Revoke tokens created by this actor_id (only applies to user actors).
	// If not set, no actor-based filtering is applied.
	CreatedByActorId string `protobuf:"bytes,2,opt,name=created_by_actor_id,json=createdByActorId,proto3" json:"created_by_actor_id,omitempty"`
	// Revoke tokens with the selected scope only.
	// If not set, no scope-based filtering is applied.
	Scope         RevokableToken_Scope `protobuf:"varint,3,opt,name=scope,proto3,enum=namespace.cloud.iam.v1beta.RevokableToken_Scope" json:"scope,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchRevokeRevokableTokenRequest) Reset() {
	*x = BatchRevokeRevokableTokenRequest{}
	mi := &file_proto_namespace_cloud_iam_v1beta_tokens_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchRevokeRevokableTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchRevokeRevokableTokenRequest) ProtoMessage() {}

func (x *BatchRevokeRevokableTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_namespace_cloud_iam_v1beta_tokens_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchRevokeRevokableTokenRequest.ProtoReflect.Descriptor instead.
func (*BatchRevokeRevokableTokenRequest) Descriptor() ([]byte, []int) {
	return file_proto_namespace_cloud_iam_v1beta_tokens_proto_rawDescGZIP(), []int{15}
}

func (x *BatchRevokeRevokableTokenRequest) GetBefore() *timestamppb.Timestamp {
	if x != nil {
		return x.Before
	}
	return nil
}

func (x *BatchRevokeRevokableTokenRequest) GetCreatedByActorId() string {
	if x != nil {
		return x.CreatedByActorId
	}
	return ""
}

func (x *BatchRevokeRevokableTokenRequest) GetScope() RevokableToken_Scope {
	if x != nil {
		return x.Scope
	}
	return RevokableToken_SCOPE_UNKNOWN
}

type BatchRevokeRevokableTokenResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The IDs of the tokens that were revoked (prefixed with "tok_").
	RevokedTokenIds []string `protobuf:"bytes,1,rep,name=revoked_token_ids,json=revokedTokenIds,proto3" json:"revoked_token_ids,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *BatchRevokeRevokableTokenResponse) Reset() {
	*x = BatchRevokeRevokableTokenResponse{}
	mi := &file_proto_namespace_cloud_iam_v1beta_tokens_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchRevokeRevokableTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchRevokeRevokableTokenResponse) ProtoMessage() {}

func (x *BatchRevokeRevokableTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_namespace_cloud_iam_v1beta_tokens_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchRevokeRevokableTokenResponse.ProtoReflect.Descriptor instead.
func (*BatchRevokeRevokableTokenResponse) Descriptor() ([]byte, []int) {
	return file_proto_namespace_cloud_iam_v1beta_tokens_proto_rawDescGZIP(), []int{16}
}

func (x *BatchRevokeRevokableTokenResponse) GetRevokedTokenIds() []string {
	if x != nil {
		return x.RevokedTokenIds
	}
	return nil
}

var File_proto_namespace_cloud_iam_v1beta_tokens_proto protoreflect.FileDescriptor

const file_proto_namespace_cloud_iam_v1beta_tokens_proto_rawDesc = "" +
	"\n" +
	"-proto/namespace/cloud/iam/v1beta/tokens.proto\x12\x1anamespace.cloud.iam.v1beta\x1a\x1egoogle/protobuf/duration.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a,proto/namespace/cloud/iam/v1beta/authz.proto\"1\n" +
	"\x13IssueIdTokenRequest\x12\x1a\n" +
	"\baudience\x18\x01 \x01(\tR\baudience\"1\n" +
	"\x14IssueIdTokenResponse\x12\x19\n" +
	"\bid_token\x18\x01 \x01(\tR\aidToken\"\x83\x02\n" +
	"\x17IssueTenantTokenRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x19\n" +
	"\bactor_id\x18\x02 \x01(\tR\aactorId\x12#\n" +
	"\rduration_secs\x18\x03 \x01(\x03R\fdurationSecs\x12I\n" +
	"\bpolicies\x18\x04 \x03(\v2-.namespace.cloud.iam.v1beta.TenantTokenPolicyR\bpolicies\x12@\n" +
	"\x06access\x18\x05 \x01(\v2(.namespace.cloud.iam.v1beta.AccessPolicyR\x06access\"N\n" +
	"\fAccessPolicy\x12>\n" +
	"\x06grants\x18\x01 \x03(\v2&.namespace.cloud.iam.v1beta.PermissionR\x06grants\"=\n" +
	"\x18IssueTenantTokenResponse\x12!\n" +
	"\fbearer_token\x18\x01 \x01(\tR\vbearerToken\"\x94\x01\n" +
	"\x1fIssueTenantTokenWithOIDCRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x1d\n" +
	"\n" +
	"oidc_token\x18\x02 \x01(\tR\toidcToken\x125\n" +
	"\bduration\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\bduration\"J\n" +
	"\x11TenantTokenPolicy\x12\x1f\n" +
	"\vpolicy_type\x18\x01 \x01(\tR\n" +
	"policyType\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"\xe3\x02\n" +
	"\x1bCreateRevokableTokenRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x129\n" +
	"\n" +
	"expires_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x12I\n" +
	"\bpolicies\x18\x04 \x03(\v2-.namespace.cloud.iam.v1beta.TenantTokenPolicyR\bpolicies\x12@\n" +
	"\x06access\x18\x05 \x01(\v2(.namespace.cloud.iam.v1beta.AccessPolicyR\x06access\x12F\n" +
	"\x05scope\x18\x06 \x01(\x0e20.namespace.cloud.iam.v1beta.RevokableToken.ScopeR\x05scope\"\x83\x01\n" +
	"\x1cCreateRevokableTokenResponse\x12!\n" +
	"\fbearer_token\x18\x01 \x01(\tR\vbearerToken\x12@\n" +
	"\x05token\x18\x02 \x01(\v2*.namespace.cloud.iam.v1beta.RevokableTokenR\x05token\"\x7f\n" +
	"\x1cRefreshRevokableTokenRequest\x12\x19\n" +
	"\btoken_id\x18\x01 \x01(\tR\atokenId\x12D\n" +
	"\x10minimum_duration\x18\x02 \x01(\v2\x19.google.protobuf.DurationR\x0fminimumDuration\"a\n" +
	"\x1dRefreshRevokableTokenResponse\x12@\n" +
	"\x05token\x18\x01 \x01(\v2*.namespace.cloud.iam.v1beta.RevokableTokenR\x05token\"8\n" +
	"\x1bRevokeRevokableTokenRequest\x12\x19\n" +
	"\btoken_id\x18\x01 \x01(\tR\atokenId\"\x93\x01\n" +
	"\x1aListRevokableTokensRequest\x12+\n" +
	"\x11pagination_cursor\x18\x01 \x01(\fR\x10paginationCursor\x12\x1f\n" +
	"\vmax_entries\x18\x02 \x01(\x03R\n" +
	"maxEntries\x12'\n" +
	"\x0finclude_revoked\x18\x03 \x01(\bR\x0eincludeRevoked\"\x8e\x01\n" +
	"\x1bListRevokableTokensResponse\x12B\n" +
	"\x06tokens\x18\x01 \x03(\v2*.namespace.cloud.iam.v1beta.RevokableTokenR\x06tokens\x12+\n" +
	"\x11pagination_cursor\x18\x02 \x01(\fR\x10paginationCursor\"\xef\x05\n" +
	"\x0eRevokableToken\x12\x19\n" +
	"\btoken_id\x18\x01 \x01(\tR\atokenId\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"expires_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x129\n" +
	"\n" +
	"revoked_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\trevokedAt\x12-\n" +
	"\x13revoked_by_actor_id\x18\b \x01(\tR\x10revokedByActorId\x12(\n" +
	"\x10creator_actor_id\x18\t \x01(\tR\x0ecreatorActorId\x12F\n" +
	"\x05scope\x18\n" +
	" \x01(\x0e20.namespace.cloud.iam.v1beta.RevokableToken.ScopeR\x05scope\x12H\n" +
	"\vpermissions\x18\v \x03(\v2&.namespace.cloud.iam.v1beta.PermissionR\vpermissions\x12F\n" +
	"\x05state\x18\f \x01(\x0e20.namespace.cloud.iam.v1beta.RevokableToken.StateR\x05state\"I\n" +
	"\x05Scope\x12\x11\n" +
	"\rSCOPE_UNKNOWN\x10\x00\x12\x10\n" +
	"\fTENANT_SCOPE\x10\x01\x12\x1b\n" +
	"\x17TENANT_MEMBERSHIP_SCOPE\x10\x02\"@\n" +
	"\x05State\x12\x11\n" +
	"\rSTATE_UNKNOWN\x10\x00\x12\n" +
	"\n" +
	"\x06ACTIVE\x10\x01\x12\v\n" +
	"\aREVOKED\x10\x02\x12\v\n" +
	"\aEXPIRED\x10\x03\"\xcd\x01\n" +
	" BatchRevokeRevokableTokenRequest\x122\n" +
	"\x06before\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x06before\x12-\n" +
	"\x13created_by_actor_id\x18\x02 \x01(\tR\x10createdByActorId\x12F\n" +
	"\x05scope\x18\x03 \x01(\x0e20.namespace.cloud.iam.v1beta.RevokableToken.ScopeR\x05scope\"O\n" +
	"!BatchRevokeRevokableTokenResponse\x12*\n" +
	"\x11revoked_token_ids\x18\x01 \x03(\tR\x0frevokedTokenIds2\xb8\b\n" +
	"\fTokenService\x12q\n" +
	"\fIssueIdToken\x12/.namespace.cloud.iam.v1beta.IssueIdTokenRequest\x1a0.namespace.cloud.iam.v1beta.IssueIdTokenResponse\x12}\n" +
	"\x10IssueTenantToken\x123.namespace.cloud.iam.v1beta.IssueTenantTokenRequest\x1a4.namespace.cloud.iam.v1beta.IssueTenantTokenResponse\x12\x8d\x01\n" +
	"\x18IssueTenantTokenWithOIDC\x12;.namespace.cloud.iam.v1beta.IssueTenantTokenWithOIDCRequest\x1a4.namespace.cloud.iam.v1beta.IssueTenantTokenResponse\x12\x89\x01\n" +
	"\x14CreateRevokableToken\x127.namespace.cloud.iam.v1beta.CreateRevokableTokenRequest\x1a8.namespace.cloud.iam.v1beta.CreateRevokableTokenResponse\x12\x8c\x01\n" +
	"\x15RefreshRevokableToken\x128.namespace.cloud.iam.v1beta.RefreshRevokableTokenRequest\x1a9.namespace.cloud.iam.v1beta.RefreshRevokableTokenResponse\x12g\n" +
	"\x14RevokeRevokableToken\x127.namespace.cloud.iam.v1beta.RevokeRevokableTokenRequest\x1a\x16.google.protobuf.Empty\x12\x86\x01\n" +
	"\x13ListRevokableTokens\x126.namespace.cloud.iam.v1beta.ListRevokableTokensRequest\x1a7.namespace.cloud.iam.v1beta.ListRevokableTokensResponse\x12\x98\x01\n" +
	"\x19BatchRevokeRevokableToken\x12<.namespace.cloud.iam.v1beta.BatchRevokeRevokableTokenRequest\x1a=.namespace.cloud.iam.v1beta.BatchRevokeRevokableTokenResponseB\x85\x02\n" +
	"\x1ecom.namespace.cloud.iam.v1betaB\vTokensProtoP\x01ZInamespacelabs.dev/integrations/proto/namespace/cloud/iam/v1beta;iamv1beta\xa2\x02\x03NCI\xaa\x02\x1aNamespace.Cloud.Iam.V1beta\xca\x02\x1bNamespace_\\Cloud\\Iam\\V1beta\xe2\x02'Namespace_\\Cloud\\Iam\\V1beta\\GPBMetadata\xea\x02\x1dNamespace::Cloud::Iam::V1betab\x06proto3"

var (
	file_proto_namespace_cloud_iam_v1beta_tokens_proto_rawDescOnce sync.Once
	file_proto_namespace_cloud_iam_v1beta_tokens_proto_rawDescData []byte
)

func file_proto_namespace_cloud_iam_v1beta_tokens_proto_rawDescGZIP() []byte {
	file_proto_namespace_cloud_iam_v1beta_tokens_proto_rawDescOnce.Do(func() {
		file_proto_namespace_cloud_iam_v1beta_tokens_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_namespace_cloud_iam_v1beta_tokens_proto_rawDesc), len(file_proto_namespace_cloud_iam_v1beta_tokens_proto_rawDesc)))
	})
	return file_proto_namespace_cloud_iam_v1beta_tokens_proto_rawDescData
}

var file_proto_namespace_cloud_iam_v1beta_tokens_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_namespace_cloud_iam_v1beta_tokens_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_proto_namespace_cloud_iam_v1beta_tokens_proto_goTypes = []any{
	(RevokableToken_Scope)(0),                 // 0: namespace.cloud.iam.v1beta.RevokableToken.Scope
	(RevokableToken_State)(0),                 // 1: namespace.cloud.iam.v1beta.RevokableToken.State
	(*IssueIdTokenRequest)(nil),               // 2: namespace.cloud.iam.v1beta.IssueIdTokenRequest
	(*IssueIdTokenResponse)(nil),              // 3: namespace.cloud.iam.v1beta.IssueIdTokenResponse
	(*IssueTenantTokenRequest)(nil),           // 4: namespace.cloud.iam.v1beta.IssueTenantTokenRequest
	(*AccessPolicy)(nil),                      // 5: namespace.cloud.iam.v1beta.AccessPolicy
	(*IssueTenantTokenResponse)(nil),          // 6: namespace.cloud.iam.v1beta.IssueTenantTokenResponse
	(*IssueTenantTokenWithOIDCRequest)(nil),   // 7: namespace.cloud.iam.v1beta.IssueTenantTokenWithOIDCRequest
	(*TenantTokenPolicy)(nil),                 // 8: namespace.cloud.iam.v1beta.TenantTokenPolicy
	(*CreateRevokableTokenRequest)(nil),       // 9: namespace.cloud.iam.v1beta.CreateRevokableTokenRequest
	(*CreateRevokableTokenResponse)(nil),      // 10: namespace.cloud.iam.v1beta.CreateRevokableTokenResponse
	(*RefreshRevokableTokenRequest)(nil),      // 11: namespace.cloud.iam.v1beta.RefreshRevokableTokenRequest
	(*RefreshRevokableTokenResponse)(nil),     // 12: namespace.cloud.iam.v1beta.RefreshRevokableTokenResponse
	(*RevokeRevokableTokenRequest)(nil),       // 13: namespace.cloud.iam.v1beta.RevokeRevokableTokenRequest
	(*ListRevokableTokensRequest)(nil),        // 14: namespace.cloud.iam.v1beta.ListRevokableTokensRequest
	(*ListRevokableTokensResponse)(nil),       // 15: namespace.cloud.iam.v1beta.ListRevokableTokensResponse
	(*RevokableToken)(nil),                    // 16: namespace.cloud.iam.v1beta.RevokableToken
	(*BatchRevokeRevokableTokenRequest)(nil),  // 17: namespace.cloud.iam.v1beta.BatchRevokeRevokableTokenRequest
	(*BatchRevokeRevokableTokenResponse)(nil), // 18: namespace.cloud.iam.v1beta.BatchRevokeRevokableTokenResponse
	(*Permission)(nil),                        // 19: namespace.cloud.iam.v1beta.Permission
	(*durationpb.Duration)(nil),               // 20: google.protobuf.Duration
	(*timestamppb.Timestamp)(nil),             // 21: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),                     // 22: google.protobuf.Empty
}
var file_proto_namespace_cloud_iam_v1beta_tokens_proto_depIdxs = []int32{
	8,  // 0: namespace.cloud.iam.v1beta.IssueTenantTokenRequest.policies:type_name -> namespace.cloud.iam.v1beta.TenantTokenPolicy
	5,  // 1: namespace.cloud.iam.v1beta.IssueTenantTokenRequest.access:type_name -> namespace.cloud.iam.v1beta.AccessPolicy
	19, // 2: namespace.cloud.iam.v1beta.AccessPolicy.grants:type_name -> namespace.cloud.iam.v1beta.Permission
	20, // 3: namespace.cloud.iam.v1beta.IssueTenantTokenWithOIDCRequest.duration:type_name -> google.protobuf.Duration
	21, // 4: namespace.cloud.iam.v1beta.CreateRevokableTokenRequest.expires_at:type_name -> google.protobuf.Timestamp
	8,  // 5: namespace.cloud.iam.v1beta.CreateRevokableTokenRequest.policies:type_name -> namespace.cloud.iam.v1beta.TenantTokenPolicy
	5,  // 6: namespace.cloud.iam.v1beta.CreateRevokableTokenRequest.access:type_name -> namespace.cloud.iam.v1beta.AccessPolicy
	0,  // 7: namespace.cloud.iam.v1beta.CreateRevokableTokenRequest.scope:type_name -> namespace.cloud.iam.v1beta.RevokableToken.Scope
	16, // 8: namespace.cloud.iam.v1beta.CreateRevokableTokenResponse.token:type_name -> namespace.cloud.iam.v1beta.RevokableToken
	20, // 9: namespace.cloud.iam.v1beta.RefreshRevokableTokenRequest.minimum_duration:type_name -> google.protobuf.Duration
	16, // 10: namespace.cloud.iam.v1beta.RefreshRevokableTokenResponse.token:type_name -> namespace.cloud.iam.v1beta.RevokableToken
	16, // 11: namespace.cloud.iam.v1beta.ListRevokableTokensResponse.tokens:type_name -> namespace.cloud.iam.v1beta.RevokableToken
	21, // 12: namespace.cloud.iam.v1beta.RevokableToken.created_at:type_name -> google.protobuf.Timestamp
	21, // 13: namespace.cloud.iam.v1beta.RevokableToken.expires_at:type_name -> google.protobuf.Timestamp
	21, // 14: namespace.cloud.iam.v1beta.RevokableToken.revoked_at:type_name -> google.protobuf.Timestamp
	0,  // 15: namespace.cloud.iam.v1beta.RevokableToken.scope:type_name -> namespace.cloud.iam.v1beta.RevokableToken.Scope
	19, // 16: namespace.cloud.iam.v1beta.RevokableToken.permissions:type_name -> namespace.cloud.iam.v1beta.Permission
	1,  // 17: namespace.cloud.iam.v1beta.RevokableToken.state:type_name -> namespace.cloud.iam.v1beta.RevokableToken.State
	21, // 18: namespace.cloud.iam.v1beta.BatchRevokeRevokableTokenRequest.before:type_name -> google.protobuf.Timestamp
	0,  // 19: namespace.cloud.iam.v1beta.BatchRevokeRevokableTokenRequest.scope:type_name -> namespace.cloud.iam.v1beta.RevokableToken.Scope
	2,  // 20: namespace.cloud.iam.v1beta.TokenService.IssueIdToken:input_type -> namespace.cloud.iam.v1beta.IssueIdTokenRequest
	4,  // 21: namespace.cloud.iam.v1beta.TokenService.IssueTenantToken:input_type -> namespace.cloud.iam.v1beta.IssueTenantTokenRequest
	7,  // 22: namespace.cloud.iam.v1beta.TokenService.IssueTenantTokenWithOIDC:input_type -> namespace.cloud.iam.v1beta.IssueTenantTokenWithOIDCRequest
	9,  // 23: namespace.cloud.iam.v1beta.TokenService.CreateRevokableToken:input_type -> namespace.cloud.iam.v1beta.CreateRevokableTokenRequest
	11, // 24: namespace.cloud.iam.v1beta.TokenService.RefreshRevokableToken:input_type -> namespace.cloud.iam.v1beta.RefreshRevokableTokenRequest
	13, // 25: namespace.cloud.iam.v1beta.TokenService.RevokeRevokableToken:input_type -> namespace.cloud.iam.v1beta.RevokeRevokableTokenRequest
	14, // 26: namespace.cloud.iam.v1beta.TokenService.ListRevokableTokens:input_type -> namespace.cloud.iam.v1beta.ListRevokableTokensRequest
	17, // 27: namespace.cloud.iam.v1beta.TokenService.BatchRevokeRevokableToken:input_type -> namespace.cloud.iam.v1beta.BatchRevokeRevokableTokenRequest
	3,  // 28: namespace.cloud.iam.v1beta.TokenService.IssueIdToken:output_type -> namespace.cloud.iam.v1beta.IssueIdTokenResponse
	6,  // 29: namespace.cloud.iam.v1beta.TokenService.IssueTenantToken:output_type -> namespace.cloud.iam.v1beta.IssueTenantTokenResponse
	6,  // 30: namespace.cloud.iam.v1beta.TokenService.IssueTenantTokenWithOIDC:output_type -> namespace.cloud.iam.v1beta.IssueTenantTokenResponse
	10, // 31: namespace.cloud.iam.v1beta.TokenService.CreateRevokableToken:output_type -> namespace.cloud.iam.v1beta.CreateRevokableTokenResponse
	12, // 32: namespace.cloud.iam.v1beta.TokenService.RefreshRevokableToken:output_type -> namespace.cloud.iam.v1beta.RefreshRevokableTokenResponse
	22, // 33: namespace.cloud.iam.v1beta.TokenService.RevokeRevokableToken:output_type -> google.protobuf.Empty
	15, // 34: namespace.cloud.iam.v1beta.TokenService.ListRevokableTokens:output_type -> namespace.cloud.iam.v1beta.ListRevokableTokensResponse
	18, // 35: namespace.cloud.iam.v1beta.TokenService.BatchRevokeRevokableToken:output_type -> namespace.cloud.iam.v1beta.BatchRevokeRevokableTokenResponse
	28, // [28:36] is the sub-list for method output_type
	20, // [20:28] is the sub-list for method input_type
	20, // [20:20] is the sub-list for extension type_name
	20, // [20:20] is the sub-list for extension extendee
	0,  // [0:20] is the sub-list for field type_name
}

func init() { file_proto_namespace_cloud_iam_v1beta_tokens_proto_init() }
func file_proto_namespace_cloud_iam_v1beta_tokens_proto_init() {
	if File_proto_namespace_cloud_iam_v1beta_tokens_proto != nil {
		return
	}
	file_proto_namespace_cloud_iam_v1beta_authz_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_namespace_cloud_iam_v1beta_tokens_proto_rawDesc), len(file_proto_namespace_cloud_iam_v1beta_tokens_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_namespace_cloud_iam_v1beta_tokens_proto_goTypes,
		DependencyIndexes: file_proto_namespace_cloud_iam_v1beta_tokens_proto_depIdxs,
		EnumInfos:         file_proto_namespace_cloud_iam_v1beta_tokens_proto_enumTypes,
		MessageInfos:      file_proto_namespace_cloud_iam_v1beta_tokens_proto_msgTypes,
	}.Build()
	File_proto_namespace_cloud_iam_v1beta_tokens_proto = out.File
	file_proto_namespace_cloud_iam_v1beta_tokens_proto_goTypes = nil
	file_proto_namespace_cloud_iam_v1beta_tokens_proto_depIdxs = nil
}
