// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: proto/namespace/cloud/github/v1beta/images.proto

package githubv1betaconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1beta "namespacelabs.dev/integrations/proto/namespace/cloud/github/v1beta"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// ImageServiceName is the fully-qualified name of the ImageService service.
	ImageServiceName = "namespace.cloud.github.v1beta.ImageService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// ImageServiceListBaseImagesProcedure is the fully-qualified name of the ImageService's
	// ListBaseImages RPC.
	ImageServiceListBaseImagesProcedure = "/namespace.cloud.github.v1beta.ImageService/ListBaseImages"
)

// These variables are the protoreflect.Descriptor objects for the RPCs defined in this package.
var (
	imageServiceServiceDescriptor              = v1beta.File_proto_namespace_cloud_github_v1beta_images_proto.Services().ByName("ImageService")
	imageServiceListBaseImagesMethodDescriptor = imageServiceServiceDescriptor.Methods().ByName("ListBaseImages")
)

// ImageServiceClient is a client for the namespace.cloud.github.v1beta.ImageService service.
type ImageServiceClient interface {
	// Lists currently available base images for GitHub runners.
	// Returns only active images that can be used for new runners.
	ListBaseImages(context.Context, *connect.Request[v1beta.ListBaseImagesRequest]) (*connect.Response[v1beta.ListBaseImagesResponse], error)
}

// NewImageServiceClient constructs a client for the namespace.cloud.github.v1beta.ImageService
// service. By default, it uses the Connect protocol with the binary Protobuf Codec, asks for
// gzipped responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply
// the connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewImageServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) ImageServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	return &imageServiceClient{
		listBaseImages: connect.NewClient[v1beta.ListBaseImagesRequest, v1beta.ListBaseImagesResponse](
			httpClient,
			baseURL+ImageServiceListBaseImagesProcedure,
			connect.WithSchema(imageServiceListBaseImagesMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
	}
}

// imageServiceClient implements ImageServiceClient.
type imageServiceClient struct {
	listBaseImages *connect.Client[v1beta.ListBaseImagesRequest, v1beta.ListBaseImagesResponse]
}

// ListBaseImages calls namespace.cloud.github.v1beta.ImageService.ListBaseImages.
func (c *imageServiceClient) ListBaseImages(ctx context.Context, req *connect.Request[v1beta.ListBaseImagesRequest]) (*connect.Response[v1beta.ListBaseImagesResponse], error) {
	return c.listBaseImages.CallUnary(ctx, req)
}

// ImageServiceHandler is an implementation of the namespace.cloud.github.v1beta.ImageService
// service.
type ImageServiceHandler interface {
	// Lists currently available base images for GitHub runners.
	// Returns only active images that can be used for new runners.
	ListBaseImages(context.Context, *connect.Request[v1beta.ListBaseImagesRequest]) (*connect.Response[v1beta.ListBaseImagesResponse], error)
}

// NewImageServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewImageServiceHandler(svc ImageServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	imageServiceListBaseImagesHandler := connect.NewUnaryHandler(
		ImageServiceListBaseImagesProcedure,
		svc.ListBaseImages,
		connect.WithSchema(imageServiceListBaseImagesMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	return "/namespace.cloud.github.v1beta.ImageService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case ImageServiceListBaseImagesProcedure:
			imageServiceListBaseImagesHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedImageServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedImageServiceHandler struct{}

func (UnimplementedImageServiceHandler) ListBaseImages(context.Context, *connect.Request[v1beta.ListBaseImagesRequest]) (*connect.Response[v1beta.ListBaseImagesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("namespace.cloud.github.v1beta.ImageService.ListBaseImages is not implemented"))
}
