// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: proto/namespace/experimental/compute/reservations.proto

package compute

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	v1beta "namespacelabs.dev/integrations/proto/namespace/cloud/compute/v1beta"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReservationStatus int32

const (
	ReservationStatus_UNKNOWN ReservationStatus = 0
	// Reservation is in progress, no instance has been assigned yet.
	ReservationStatus_PENDING ReservationStatus = 1
	// An instance was assigned to the reservation.
	ReservationStatus_FULFILLED ReservationStatus = 2
	// The reservation deadline is in the past and no instance was assigned.
	ReservationStatus_EXPIRED ReservationStatus = 3
)

// Enum value maps for ReservationStatus.
var (
	ReservationStatus_name = map[int32]string{
		0: "UNKNOWN",
		1: "PENDING",
		2: "FULFILLED",
		3: "EXPIRED",
	}
	ReservationStatus_value = map[string]int32{
		"UNKNOWN":   0,
		"PENDING":   1,
		"FULFILLED": 2,
		"EXPIRED":   3,
	}
)

func (x ReservationStatus) Enum() *ReservationStatus {
	p := new(ReservationStatus)
	*p = x
	return p
}

func (x ReservationStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ReservationStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_namespace_experimental_compute_reservations_proto_enumTypes[0].Descriptor()
}

func (ReservationStatus) Type() protoreflect.EnumType {
	return &file_proto_namespace_experimental_compute_reservations_proto_enumTypes[0]
}

func (x ReservationStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ReservationStatus.Descriptor instead.
func (ReservationStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_namespace_experimental_compute_reservations_proto_rawDescGZIP(), []int{0}
}

type ReserveInstanceRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// All parameters for the underlying instance to be created
	CreateInstanceReq *v1beta.CreateInstanceRequest `protobuf:"bytes,1,opt,name=create_instance_req,json=createInstanceReq,proto3" json:"create_instance_req,omitempty"`
	// Deadline by which the instance should be created. If the reservation has
	// not been fulfilled by this time, the server will no longer attempt to
	// create the instance.
	ReservationDeadline *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=reservation_deadline,json=reservationDeadline,proto3" json:"reservation_deadline,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ReserveInstanceRequest) Reset() {
	*x = ReserveInstanceRequest{}
	mi := &file_proto_namespace_experimental_compute_reservations_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReserveInstanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReserveInstanceRequest) ProtoMessage() {}

func (x *ReserveInstanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_namespace_experimental_compute_reservations_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReserveInstanceRequest.ProtoReflect.Descriptor instead.
func (*ReserveInstanceRequest) Descriptor() ([]byte, []int) {
	return file_proto_namespace_experimental_compute_reservations_proto_rawDescGZIP(), []int{0}
}

func (x *ReserveInstanceRequest) GetCreateInstanceReq() *v1beta.CreateInstanceRequest {
	if x != nil {
		return x.CreateInstanceReq
	}
	return nil
}

func (x *ReserveInstanceRequest) GetReservationDeadline() *timestamppb.Timestamp {
	if x != nil {
		return x.ReservationDeadline
	}
	return nil
}

type ReserveInstanceResponse struct {
	state         protoimpl.MessageState                       `protogen:"open.v1"`
	ReservationId string                                       `protobuf:"bytes,1,opt,name=reservation_id,json=reservationId,proto3" json:"reservation_id,omitempty"`
	Metadata      *ReserveInstanceResponse_ReservationMetadata `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReserveInstanceResponse) Reset() {
	*x = ReserveInstanceResponse{}
	mi := &file_proto_namespace_experimental_compute_reservations_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReserveInstanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReserveInstanceResponse) ProtoMessage() {}

func (x *ReserveInstanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_namespace_experimental_compute_reservations_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReserveInstanceResponse.ProtoReflect.Descriptor instead.
func (*ReserveInstanceResponse) Descriptor() ([]byte, []int) {
	return file_proto_namespace_experimental_compute_reservations_proto_rawDescGZIP(), []int{1}
}

func (x *ReserveInstanceResponse) GetReservationId() string {
	if x != nil {
		return x.ReservationId
	}
	return ""
}

func (x *ReserveInstanceResponse) GetMetadata() *ReserveInstanceResponse_ReservationMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type DescribeReservationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReservationId string                 `protobuf:"bytes,1,opt,name=reservation_id,json=reservationId,proto3" json:"reservation_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DescribeReservationRequest) Reset() {
	*x = DescribeReservationRequest{}
	mi := &file_proto_namespace_experimental_compute_reservations_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DescribeReservationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DescribeReservationRequest) ProtoMessage() {}

func (x *DescribeReservationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_namespace_experimental_compute_reservations_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DescribeReservationRequest.ProtoReflect.Descriptor instead.
func (*DescribeReservationRequest) Descriptor() ([]byte, []int) {
	return file_proto_namespace_experimental_compute_reservations_proto_rawDescGZIP(), []int{2}
}

func (x *DescribeReservationRequest) GetReservationId() string {
	if x != nil {
		return x.ReservationId
	}
	return ""
}

type DescribeReservationResponse struct {
	state               protoimpl.MessageState                       `protogen:"open.v1"`
	ReservationId       string                                       `protobuf:"bytes,1,opt,name=reservation_id,json=reservationId,proto3" json:"reservation_id,omitempty"`
	ReservationMetadata *ReserveInstanceResponse_ReservationMetadata `protobuf:"bytes,3,opt,name=reservation_metadata,json=reservationMetadata,proto3" json:"reservation_metadata,omitempty"`
	// If the reservation has been fulfilled, the corresponding instance ID
	// and the time at which the fulfillment occurred
	InstanceId      string                 `protobuf:"bytes,4,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	FulfillmentTime *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=fulfillment_time,json=fulfillmentTime,proto3" json:"fulfillment_time,omitempty"`
	LastAttempt     *CreationAttempt       `protobuf:"bytes,6,opt,name=last_attempt,json=lastAttempt,proto3" json:"last_attempt,omitempty"`
	Status          ReservationStatus      `protobuf:"varint,7,opt,name=status,proto3,enum=namespace.experimental.compute.ReservationStatus" json:"status,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *DescribeReservationResponse) Reset() {
	*x = DescribeReservationResponse{}
	mi := &file_proto_namespace_experimental_compute_reservations_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DescribeReservationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DescribeReservationResponse) ProtoMessage() {}

func (x *DescribeReservationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_namespace_experimental_compute_reservations_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DescribeReservationResponse.ProtoReflect.Descriptor instead.
func (*DescribeReservationResponse) Descriptor() ([]byte, []int) {
	return file_proto_namespace_experimental_compute_reservations_proto_rawDescGZIP(), []int{3}
}

func (x *DescribeReservationResponse) GetReservationId() string {
	if x != nil {
		return x.ReservationId
	}
	return ""
}

func (x *DescribeReservationResponse) GetReservationMetadata() *ReserveInstanceResponse_ReservationMetadata {
	if x != nil {
		return x.ReservationMetadata
	}
	return nil
}

func (x *DescribeReservationResponse) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *DescribeReservationResponse) GetFulfillmentTime() *timestamppb.Timestamp {
	if x != nil {
		return x.FulfillmentTime
	}
	return nil
}

func (x *DescribeReservationResponse) GetLastAttempt() *CreationAttempt {
	if x != nil {
		return x.LastAttempt
	}
	return nil
}

func (x *DescribeReservationResponse) GetStatus() ReservationStatus {
	if x != nil {
		return x.Status
	}
	return ReservationStatus_UNKNOWN
}

type CreationAttempt struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Timestamp *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// Instance that was started on this attempt.
	// If creating an instance failed, error will be set instead.
	InstanceId string `protobuf:"bytes,2,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	// Set if creating an instance failed on this attempt.
	Error         string `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreationAttempt) Reset() {
	*x = CreationAttempt{}
	mi := &file_proto_namespace_experimental_compute_reservations_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreationAttempt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreationAttempt) ProtoMessage() {}

func (x *CreationAttempt) ProtoReflect() protoreflect.Message {
	mi := &file_proto_namespace_experimental_compute_reservations_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreationAttempt.ProtoReflect.Descriptor instead.
func (*CreationAttempt) Descriptor() ([]byte, []int) {
	return file_proto_namespace_experimental_compute_reservations_proto_rawDescGZIP(), []int{4}
}

func (x *CreationAttempt) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *CreationAttempt) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *CreationAttempt) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type CancelReservationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReservationId string                 `protobuf:"bytes,1,opt,name=reservation_id,json=reservationId,proto3" json:"reservation_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelReservationRequest) Reset() {
	*x = CancelReservationRequest{}
	mi := &file_proto_namespace_experimental_compute_reservations_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelReservationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelReservationRequest) ProtoMessage() {}

func (x *CancelReservationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_namespace_experimental_compute_reservations_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelReservationRequest.ProtoReflect.Descriptor instead.
func (*CancelReservationRequest) Descriptor() ([]byte, []int) {
	return file_proto_namespace_experimental_compute_reservations_proto_rawDescGZIP(), []int{5}
}

func (x *CancelReservationRequest) GetReservationId() string {
	if x != nil {
		return x.ReservationId
	}
	return ""
}

type CancelReservationResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	ReservationDeadline *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=reservation_deadline,json=reservationDeadline,proto3" json:"reservation_deadline,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *CancelReservationResponse) Reset() {
	*x = CancelReservationResponse{}
	mi := &file_proto_namespace_experimental_compute_reservations_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelReservationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelReservationResponse) ProtoMessage() {}

func (x *CancelReservationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_namespace_experimental_compute_reservations_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelReservationResponse.ProtoReflect.Descriptor instead.
func (*CancelReservationResponse) Descriptor() ([]byte, []int) {
	return file_proto_namespace_experimental_compute_reservations_proto_rawDescGZIP(), []int{6}
}

func (x *CancelReservationResponse) GetReservationDeadline() *timestamppb.Timestamp {
	if x != nil {
		return x.ReservationDeadline
	}
	return nil
}

type UpdateReservationDeadlineRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	ReservationId       string                 `protobuf:"bytes,1,opt,name=reservation_id,json=reservationId,proto3" json:"reservation_id,omitempty"`
	ReservationDeadline *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=reservation_deadline,json=reservationDeadline,proto3" json:"reservation_deadline,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *UpdateReservationDeadlineRequest) Reset() {
	*x = UpdateReservationDeadlineRequest{}
	mi := &file_proto_namespace_experimental_compute_reservations_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateReservationDeadlineRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateReservationDeadlineRequest) ProtoMessage() {}

func (x *UpdateReservationDeadlineRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_namespace_experimental_compute_reservations_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateReservationDeadlineRequest.ProtoReflect.Descriptor instead.
func (*UpdateReservationDeadlineRequest) Descriptor() ([]byte, []int) {
	return file_proto_namespace_experimental_compute_reservations_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateReservationDeadlineRequest) GetReservationId() string {
	if x != nil {
		return x.ReservationId
	}
	return ""
}

func (x *UpdateReservationDeadlineRequest) GetReservationDeadline() *timestamppb.Timestamp {
	if x != nil {
		return x.ReservationDeadline
	}
	return nil
}

type UpdateReservationDeadlineResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	ReservationDeadline *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=reservation_deadline,json=reservationDeadline,proto3" json:"reservation_deadline,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *UpdateReservationDeadlineResponse) Reset() {
	*x = UpdateReservationDeadlineResponse{}
	mi := &file_proto_namespace_experimental_compute_reservations_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateReservationDeadlineResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateReservationDeadlineResponse) ProtoMessage() {}

func (x *UpdateReservationDeadlineResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_namespace_experimental_compute_reservations_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateReservationDeadlineResponse.ProtoReflect.Descriptor instead.
func (*UpdateReservationDeadlineResponse) Descriptor() ([]byte, []int) {
	return file_proto_namespace_experimental_compute_reservations_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateReservationDeadlineResponse) GetReservationDeadline() *timestamppb.Timestamp {
	if x != nil {
		return x.ReservationDeadline
	}
	return nil
}

type ListReservationsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// When filtering for a time range, we return all reservations which were/are
	// active at any point in that time range, meaning at least one of (creation_time,
	// reservation_end) is in the window [period_start, period_end] OR
	// creation_time < period_start < period_end < reservation_end.
	// We consider reservation_end to be the reservation_deadline for reservations
	// that have not been fulfilled, and fulfillment_time for those that have, so
	// a reservation with fulfillment_time < period_start <= reservation_deadline
	// will not be included in the response.
	PeriodStart *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=period_start,json=periodStart,proto3" json:"period_start,omitempty"` // default to epoch
	PeriodEnd   *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=period_end,json=periodEnd,proto3" json:"period_end,omitempty"`       // default to now
	// Maximum number of reservations to return. Capped at 50,000; default 100
	MaxEntries int64 `protobuf:"varint,3,opt,name=max_entries,json=maxEntries,proto3" json:"max_entries,omitempty"`
	// If true, no reservations that have been fulfilled (have an instance assigned)
	// will be returned
	ExcludeFulfilled bool `protobuf:"varint,4,opt,name=exclude_fulfilled,json=excludeFulfilled,proto3" json:"exclude_fulfilled,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ListReservationsRequest) Reset() {
	*x = ListReservationsRequest{}
	mi := &file_proto_namespace_experimental_compute_reservations_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListReservationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListReservationsRequest) ProtoMessage() {}

func (x *ListReservationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_namespace_experimental_compute_reservations_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListReservationsRequest.ProtoReflect.Descriptor instead.
func (*ListReservationsRequest) Descriptor() ([]byte, []int) {
	return file_proto_namespace_experimental_compute_reservations_proto_rawDescGZIP(), []int{9}
}

func (x *ListReservationsRequest) GetPeriodStart() *timestamppb.Timestamp {
	if x != nil {
		return x.PeriodStart
	}
	return nil
}

func (x *ListReservationsRequest) GetPeriodEnd() *timestamppb.Timestamp {
	if x != nil {
		return x.PeriodEnd
	}
	return nil
}

func (x *ListReservationsRequest) GetMaxEntries() int64 {
	if x != nil {
		return x.MaxEntries
	}
	return 0
}

func (x *ListReservationsRequest) GetExcludeFulfilled() bool {
	if x != nil {
		return x.ExcludeFulfilled
	}
	return false
}

type ListReservationsResponse struct {
	state         protoimpl.MessageState         `protogen:"open.v1"`
	Reservations  []*DescribeReservationResponse `protobuf:"bytes,1,rep,name=reservations,proto3" json:"reservations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListReservationsResponse) Reset() {
	*x = ListReservationsResponse{}
	mi := &file_proto_namespace_experimental_compute_reservations_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListReservationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListReservationsResponse) ProtoMessage() {}

func (x *ListReservationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_namespace_experimental_compute_reservations_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListReservationsResponse.ProtoReflect.Descriptor instead.
func (*ListReservationsResponse) Descriptor() ([]byte, []int) {
	return file_proto_namespace_experimental_compute_reservations_proto_rawDescGZIP(), []int{10}
}

func (x *ListReservationsResponse) GetReservations() []*DescribeReservationResponse {
	if x != nil {
		return x.Reservations
	}
	return nil
}

type ReserveInstanceResponse_ReservationMetadata struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The time at which the reservation was initially requested
	ReservationTime     *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=reservation_time,json=reservationTime,proto3" json:"reservation_time,omitempty"`
	ReservationDeadline *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=reservation_deadline,json=reservationDeadline,proto3" json:"reservation_deadline,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ReserveInstanceResponse_ReservationMetadata) Reset() {
	*x = ReserveInstanceResponse_ReservationMetadata{}
	mi := &file_proto_namespace_experimental_compute_reservations_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReserveInstanceResponse_ReservationMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReserveInstanceResponse_ReservationMetadata) ProtoMessage() {}

func (x *ReserveInstanceResponse_ReservationMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_proto_namespace_experimental_compute_reservations_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReserveInstanceResponse_ReservationMetadata.ProtoReflect.Descriptor instead.
func (*ReserveInstanceResponse_ReservationMetadata) Descriptor() ([]byte, []int) {
	return file_proto_namespace_experimental_compute_reservations_proto_rawDescGZIP(), []int{1, 0}
}

func (x *ReserveInstanceResponse_ReservationMetadata) GetReservationTime() *timestamppb.Timestamp {
	if x != nil {
		return x.ReservationTime
	}
	return nil
}

func (x *ReserveInstanceResponse_ReservationMetadata) GetReservationDeadline() *timestamppb.Timestamp {
	if x != nil {
		return x.ReservationDeadline
	}
	return nil
}

var File_proto_namespace_experimental_compute_reservations_proto protoreflect.FileDescriptor

const file_proto_namespace_experimental_compute_reservations_proto_rawDesc = "" +
	"\n" +
	"7proto/namespace/experimental/compute/reservations.proto\x12\x1enamespace.experimental.compute\x1a\x1fgoogle/protobuf/timestamp.proto\x1a2proto/namespace/cloud/compute/v1beta/compute.proto\"\xce\x01\n" +
	"\x16ReserveInstanceRequest\x12e\n" +
	"\x13create_instance_req\x18\x01 \x01(\v25.namespace.cloud.compute.v1beta.CreateInstanceRequestR\x11createInstanceReq\x12M\n" +
	"\x14reservation_deadline\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x13reservationDeadline\"\xd7\x02\n" +
	"\x17ReserveInstanceResponse\x12%\n" +
	"\x0ereservation_id\x18\x01 \x01(\tR\rreservationId\x12g\n" +
	"\bmetadata\x18\x02 \x01(\v2K.namespace.experimental.compute.ReserveInstanceResponse.ReservationMetadataR\bmetadata\x1a\xab\x01\n" +
	"\x13ReservationMetadata\x12E\n" +
	"\x10reservation_time\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x0freservationTime\x12M\n" +
	"\x14reservation_deadline\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x13reservationDeadline\"C\n" +
	"\x1aDescribeReservationRequest\x12%\n" +
	"\x0ereservation_id\x18\x01 \x01(\tR\rreservationId\"\xd1\x03\n" +
	"\x1bDescribeReservationResponse\x12%\n" +
	"\x0ereservation_id\x18\x01 \x01(\tR\rreservationId\x12~\n" +
	"\x14reservation_metadata\x18\x03 \x01(\v2K.namespace.experimental.compute.ReserveInstanceResponse.ReservationMetadataR\x13reservationMetadata\x12\x1f\n" +
	"\vinstance_id\x18\x04 \x01(\tR\n" +
	"instanceId\x12E\n" +
	"\x10fulfillment_time\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\x0ffulfillmentTime\x12R\n" +
	"\flast_attempt\x18\x06 \x01(\v2/.namespace.experimental.compute.CreationAttemptR\vlastAttempt\x12I\n" +
	"\x06status\x18\a \x01(\x0e21.namespace.experimental.compute.ReservationStatusR\x06statusJ\x04\b\x02\x10\x03\"\x82\x01\n" +
	"\x0fCreationAttempt\x128\n" +
	"\ttimestamp\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x1f\n" +
	"\vinstance_id\x18\x02 \x01(\tR\n" +
	"instanceId\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"A\n" +
	"\x18CancelReservationRequest\x12%\n" +
	"\x0ereservation_id\x18\x01 \x01(\tR\rreservationId\"j\n" +
	"\x19CancelReservationResponse\x12M\n" +
	"\x14reservation_deadline\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x13reservationDeadline\"\x98\x01\n" +
	" UpdateReservationDeadlineRequest\x12%\n" +
	"\x0ereservation_id\x18\x01 \x01(\tR\rreservationId\x12M\n" +
	"\x14reservation_deadline\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x13reservationDeadline\"r\n" +
	"!UpdateReservationDeadlineResponse\x12M\n" +
	"\x14reservation_deadline\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x13reservationDeadline\"\xe1\x01\n" +
	"\x17ListReservationsRequest\x12=\n" +
	"\fperiod_start\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\vperiodStart\x129\n" +
	"\n" +
	"period_end\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tperiodEnd\x12\x1f\n" +
	"\vmax_entries\x18\x03 \x01(\x03R\n" +
	"maxEntries\x12+\n" +
	"\x11exclude_fulfilled\x18\x04 \x01(\bR\x10excludeFulfilled\"{\n" +
	"\x18ListReservationsResponse\x12_\n" +
	"\freservations\x18\x01 \x03(\v2;.namespace.experimental.compute.DescribeReservationResponseR\freservations*I\n" +
	"\x11ReservationStatus\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\v\n" +
	"\aPENDING\x10\x01\x12\r\n" +
	"\tFULFILLED\x10\x02\x12\v\n" +
	"\aEXPIRED\x10\x032\xe0\x05\n" +
	"\x12ReservationService\x12\x82\x01\n" +
	"\x0fReserveInstance\x126.namespace.experimental.compute.ReserveInstanceRequest\x1a7.namespace.experimental.compute.ReserveInstanceResponse\x12\x8e\x01\n" +
	"\x13DescribeReservation\x12:.namespace.experimental.compute.DescribeReservationRequest\x1a;.namespace.experimental.compute.DescribeReservationResponse\x12\x88\x01\n" +
	"\x11CancelReservation\x128.namespace.experimental.compute.CancelReservationRequest\x1a9.namespace.experimental.compute.CancelReservationResponse\x12\xa0\x01\n" +
	"\x19UpdateReservationDeadline\x12@.namespace.experimental.compute.UpdateReservationDeadlineRequest\x1aA.namespace.experimental.compute.UpdateReservationDeadlineResponse\x12\x85\x01\n" +
	"\x10ListReservations\x127.namespace.experimental.compute.ListReservationsRequest\x1a8.namespace.experimental.compute.ListReservationsResponseB\x98\x02\n" +
	"\"com.namespace.experimental.computeB\x11ReservationsProtoP\x01ZCnamespacelabs.dev/integrations/proto/namespace/experimental/compute\xa2\x02\x03NEC\xaa\x02\x1eNamespace.Experimental.Compute\xca\x02\x1fNamespace_\\Experimental\\Compute\xe2\x02+Namespace_\\Experimental\\Compute\\GPBMetadata\xea\x02 Namespace::Experimental::Computeb\x06proto3"

var (
	file_proto_namespace_experimental_compute_reservations_proto_rawDescOnce sync.Once
	file_proto_namespace_experimental_compute_reservations_proto_rawDescData []byte
)

func file_proto_namespace_experimental_compute_reservations_proto_rawDescGZIP() []byte {
	file_proto_namespace_experimental_compute_reservations_proto_rawDescOnce.Do(func() {
		file_proto_namespace_experimental_compute_reservations_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_namespace_experimental_compute_reservations_proto_rawDesc), len(file_proto_namespace_experimental_compute_reservations_proto_rawDesc)))
	})
	return file_proto_namespace_experimental_compute_reservations_proto_rawDescData
}

var file_proto_namespace_experimental_compute_reservations_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_namespace_experimental_compute_reservations_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_proto_namespace_experimental_compute_reservations_proto_goTypes = []any{
	(ReservationStatus)(0),                              // 0: namespace.experimental.compute.ReservationStatus
	(*ReserveInstanceRequest)(nil),                      // 1: namespace.experimental.compute.ReserveInstanceRequest
	(*ReserveInstanceResponse)(nil),                     // 2: namespace.experimental.compute.ReserveInstanceResponse
	(*DescribeReservationRequest)(nil),                  // 3: namespace.experimental.compute.DescribeReservationRequest
	(*DescribeReservationResponse)(nil),                 // 4: namespace.experimental.compute.DescribeReservationResponse
	(*CreationAttempt)(nil),                             // 5: namespace.experimental.compute.CreationAttempt
	(*CancelReservationRequest)(nil),                    // 6: namespace.experimental.compute.CancelReservationRequest
	(*CancelReservationResponse)(nil),                   // 7: namespace.experimental.compute.CancelReservationResponse
	(*UpdateReservationDeadlineRequest)(nil),            // 8: namespace.experimental.compute.UpdateReservationDeadlineRequest
	(*UpdateReservationDeadlineResponse)(nil),           // 9: namespace.experimental.compute.UpdateReservationDeadlineResponse
	(*ListReservationsRequest)(nil),                     // 10: namespace.experimental.compute.ListReservationsRequest
	(*ListReservationsResponse)(nil),                    // 11: namespace.experimental.compute.ListReservationsResponse
	(*ReserveInstanceResponse_ReservationMetadata)(nil), // 12: namespace.experimental.compute.ReserveInstanceResponse.ReservationMetadata
	(*v1beta.CreateInstanceRequest)(nil),                // 13: namespace.cloud.compute.v1beta.CreateInstanceRequest
	(*timestamppb.Timestamp)(nil),                       // 14: google.protobuf.Timestamp
}
var file_proto_namespace_experimental_compute_reservations_proto_depIdxs = []int32{
	13, // 0: namespace.experimental.compute.ReserveInstanceRequest.create_instance_req:type_name -> namespace.cloud.compute.v1beta.CreateInstanceRequest
	14, // 1: namespace.experimental.compute.ReserveInstanceRequest.reservation_deadline:type_name -> google.protobuf.Timestamp
	12, // 2: namespace.experimental.compute.ReserveInstanceResponse.metadata:type_name -> namespace.experimental.compute.ReserveInstanceResponse.ReservationMetadata
	12, // 3: namespace.experimental.compute.DescribeReservationResponse.reservation_metadata:type_name -> namespace.experimental.compute.ReserveInstanceResponse.ReservationMetadata
	14, // 4: namespace.experimental.compute.DescribeReservationResponse.fulfillment_time:type_name -> google.protobuf.Timestamp
	5,  // 5: namespace.experimental.compute.DescribeReservationResponse.last_attempt:type_name -> namespace.experimental.compute.CreationAttempt
	0,  // 6: namespace.experimental.compute.DescribeReservationResponse.status:type_name -> namespace.experimental.compute.ReservationStatus
	14, // 7: namespace.experimental.compute.CreationAttempt.timestamp:type_name -> google.protobuf.Timestamp
	14, // 8: namespace.experimental.compute.CancelReservationResponse.reservation_deadline:type_name -> google.protobuf.Timestamp
	14, // 9: namespace.experimental.compute.UpdateReservationDeadlineRequest.reservation_deadline:type_name -> google.protobuf.Timestamp
	14, // 10: namespace.experimental.compute.UpdateReservationDeadlineResponse.reservation_deadline:type_name -> google.protobuf.Timestamp
	14, // 11: namespace.experimental.compute.ListReservationsRequest.period_start:type_name -> google.protobuf.Timestamp
	14, // 12: namespace.experimental.compute.ListReservationsRequest.period_end:type_name -> google.protobuf.Timestamp
	4,  // 13: namespace.experimental.compute.ListReservationsResponse.reservations:type_name -> namespace.experimental.compute.DescribeReservationResponse
	14, // 14: namespace.experimental.compute.ReserveInstanceResponse.ReservationMetadata.reservation_time:type_name -> google.protobuf.Timestamp
	14, // 15: namespace.experimental.compute.ReserveInstanceResponse.ReservationMetadata.reservation_deadline:type_name -> google.protobuf.Timestamp
	1,  // 16: namespace.experimental.compute.ReservationService.ReserveInstance:input_type -> namespace.experimental.compute.ReserveInstanceRequest
	3,  // 17: namespace.experimental.compute.ReservationService.DescribeReservation:input_type -> namespace.experimental.compute.DescribeReservationRequest
	6,  // 18: namespace.experimental.compute.ReservationService.CancelReservation:input_type -> namespace.experimental.compute.CancelReservationRequest
	8,  // 19: namespace.experimental.compute.ReservationService.UpdateReservationDeadline:input_type -> namespace.experimental.compute.UpdateReservationDeadlineRequest
	10, // 20: namespace.experimental.compute.ReservationService.ListReservations:input_type -> namespace.experimental.compute.ListReservationsRequest
	2,  // 21: namespace.experimental.compute.ReservationService.ReserveInstance:output_type -> namespace.experimental.compute.ReserveInstanceResponse
	4,  // 22: namespace.experimental.compute.ReservationService.DescribeReservation:output_type -> namespace.experimental.compute.DescribeReservationResponse
	7,  // 23: namespace.experimental.compute.ReservationService.CancelReservation:output_type -> namespace.experimental.compute.CancelReservationResponse
	9,  // 24: namespace.experimental.compute.ReservationService.UpdateReservationDeadline:output_type -> namespace.experimental.compute.UpdateReservationDeadlineResponse
	11, // 25: namespace.experimental.compute.ReservationService.ListReservations:output_type -> namespace.experimental.compute.ListReservationsResponse
	21, // [21:26] is the sub-list for method output_type
	16, // [16:21] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_proto_namespace_experimental_compute_reservations_proto_init() }
func file_proto_namespace_experimental_compute_reservations_proto_init() {
	if File_proto_namespace_experimental_compute_reservations_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_namespace_experimental_compute_reservations_proto_rawDesc), len(file_proto_namespace_experimental_compute_reservations_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_namespace_experimental_compute_reservations_proto_goTypes,
		DependencyIndexes: file_proto_namespace_experimental_compute_reservations_proto_depIdxs,
		EnumInfos:         file_proto_namespace_experimental_compute_reservations_proto_enumTypes,
		MessageInfos:      file_proto_namespace_experimental_compute_reservations_proto_msgTypes,
	}.Build()
	File_proto_namespace_experimental_compute_reservations_proto = out.File
	file_proto_namespace_experimental_compute_reservations_proto_goTypes = nil
	file_proto_namespace_experimental_compute_reservations_proto_depIdxs = nil
}
