// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: proto/namespace/experimental/compute/reservations.proto

package compute

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ReservationService_ReserveInstance_FullMethodName           = "/namespace.experimental.compute.ReservationService/ReserveInstance"
	ReservationService_DescribeReservation_FullMethodName       = "/namespace.experimental.compute.ReservationService/DescribeReservation"
	ReservationService_CancelReservation_FullMethodName         = "/namespace.experimental.compute.ReservationService/CancelReservation"
	ReservationService_UpdateReservationDeadline_FullMethodName = "/namespace.experimental.compute.ReservationService/UpdateReservationDeadline"
	ReservationService_ListReservations_FullMethodName          = "/namespace.experimental.compute.ReservationService/ListReservations"
)

// ReservationServiceClient is the client API for ReservationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ReservationService provides an extension of ComputeService, trading
// latency for more persistent instance creation requests.
//
// The basic unit is a "reservation," the intent to create an instance
// by some deadline. In the case where instance creation may otherwise
// fail, for example because the caller has no available contracted
// capacity, the request // will be queued until it is possible to fulfill
// or until the reservation deadline elapses.
type ReservationServiceClient interface {
	// Create a reservation for an instance. The server will immediately
	// return a reservation ID and attempt to create the desired instance.
	// In the event that the instance cannot be created instantaneously, the
	// server will periodically retry until the provided reservation deadline.
	ReserveInstance(ctx context.Context, in *ReserveInstanceRequest, opts ...grpc.CallOption) (*ReserveInstanceResponse, error)
	// Returns the metadata about a previously created reservation. Includes
	// the instance ID of the instance that fulfilled the reservation, if
	// such an instance exists.
	DescribeReservation(ctx context.Context, in *DescribeReservationRequest, opts ...grpc.CallOption) (*DescribeReservationResponse, error)
	// Cancel a pending reservation. Has no effect if the reservation has expired;
	// throws an error if it has already been fulfilled (i.e. if it has a corresponding
	// running instance). Equivalent to UpdateReservationDeadline(now).
	CancelReservation(ctx context.Context, in *CancelReservationRequest, opts ...grpc.CallOption) (*CancelReservationResponse, error)
	// Update the deadline of a reservation. Fails if the new deadline is in the past
	// or if the reservation has already been fulfilled. UpdateReservationDeadline(now)
	// is equivalent to CancelReservation.
	UpdateReservationDeadline(ctx context.Context, in *UpdateReservationDeadlineRequest, opts ...grpc.CallOption) (*UpdateReservationDeadlineResponse, error)
	// List reservations that were active within a specified time range.
	ListReservations(ctx context.Context, in *ListReservationsRequest, opts ...grpc.CallOption) (*ListReservationsResponse, error)
}

type reservationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewReservationServiceClient(cc grpc.ClientConnInterface) ReservationServiceClient {
	return &reservationServiceClient{cc}
}

func (c *reservationServiceClient) ReserveInstance(ctx context.Context, in *ReserveInstanceRequest, opts ...grpc.CallOption) (*ReserveInstanceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReserveInstanceResponse)
	err := c.cc.Invoke(ctx, ReservationService_ReserveInstance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reservationServiceClient) DescribeReservation(ctx context.Context, in *DescribeReservationRequest, opts ...grpc.CallOption) (*DescribeReservationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DescribeReservationResponse)
	err := c.cc.Invoke(ctx, ReservationService_DescribeReservation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reservationServiceClient) CancelReservation(ctx context.Context, in *CancelReservationRequest, opts ...grpc.CallOption) (*CancelReservationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CancelReservationResponse)
	err := c.cc.Invoke(ctx, ReservationService_CancelReservation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reservationServiceClient) UpdateReservationDeadline(ctx context.Context, in *UpdateReservationDeadlineRequest, opts ...grpc.CallOption) (*UpdateReservationDeadlineResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateReservationDeadlineResponse)
	err := c.cc.Invoke(ctx, ReservationService_UpdateReservationDeadline_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reservationServiceClient) ListReservations(ctx context.Context, in *ListReservationsRequest, opts ...grpc.CallOption) (*ListReservationsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListReservationsResponse)
	err := c.cc.Invoke(ctx, ReservationService_ListReservations_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ReservationServiceServer is the server API for ReservationService service.
// All implementations must embed UnimplementedReservationServiceServer
// for forward compatibility.
//
// ReservationService provides an extension of ComputeService, trading
// latency for more persistent instance creation requests.
//
// The basic unit is a "reservation," the intent to create an instance
// by some deadline. In the case where instance creation may otherwise
// fail, for example because the caller has no available contracted
// capacity, the request // will be queued until it is possible to fulfill
// or until the reservation deadline elapses.
type ReservationServiceServer interface {
	// Create a reservation for an instance. The server will immediately
	// return a reservation ID and attempt to create the desired instance.
	// In the event that the instance cannot be created instantaneously, the
	// server will periodically retry until the provided reservation deadline.
	ReserveInstance(context.Context, *ReserveInstanceRequest) (*ReserveInstanceResponse, error)
	// Returns the metadata about a previously created reservation. Includes
	// the instance ID of the instance that fulfilled the reservation, if
	// such an instance exists.
	DescribeReservation(context.Context, *DescribeReservationRequest) (*DescribeReservationResponse, error)
	// Cancel a pending reservation. Has no effect if the reservation has expired;
	// throws an error if it has already been fulfilled (i.e. if it has a corresponding
	// running instance). Equivalent to UpdateReservationDeadline(now).
	CancelReservation(context.Context, *CancelReservationRequest) (*CancelReservationResponse, error)
	// Update the deadline of a reservation. Fails if the new deadline is in the past
	// or if the reservation has already been fulfilled. UpdateReservationDeadline(now)
	// is equivalent to CancelReservation.
	UpdateReservationDeadline(context.Context, *UpdateReservationDeadlineRequest) (*UpdateReservationDeadlineResponse, error)
	// List reservations that were active within a specified time range.
	ListReservations(context.Context, *ListReservationsRequest) (*ListReservationsResponse, error)
	mustEmbedUnimplementedReservationServiceServer()
}

// UnimplementedReservationServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedReservationServiceServer struct{}

func (UnimplementedReservationServiceServer) ReserveInstance(context.Context, *ReserveInstanceRequest) (*ReserveInstanceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReserveInstance not implemented")
}
func (UnimplementedReservationServiceServer) DescribeReservation(context.Context, *DescribeReservationRequest) (*DescribeReservationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DescribeReservation not implemented")
}
func (UnimplementedReservationServiceServer) CancelReservation(context.Context, *CancelReservationRequest) (*CancelReservationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CancelReservation not implemented")
}
func (UnimplementedReservationServiceServer) UpdateReservationDeadline(context.Context, *UpdateReservationDeadlineRequest) (*UpdateReservationDeadlineResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateReservationDeadline not implemented")
}
func (UnimplementedReservationServiceServer) ListReservations(context.Context, *ListReservationsRequest) (*ListReservationsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListReservations not implemented")
}
func (UnimplementedReservationServiceServer) mustEmbedUnimplementedReservationServiceServer() {}
func (UnimplementedReservationServiceServer) testEmbeddedByValue()                            {}

// UnsafeReservationServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ReservationServiceServer will
// result in compilation errors.
type UnsafeReservationServiceServer interface {
	mustEmbedUnimplementedReservationServiceServer()
}

func RegisterReservationServiceServer(s grpc.ServiceRegistrar, srv ReservationServiceServer) {
	// If the following call panics, it indicates UnimplementedReservationServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ReservationService_ServiceDesc, srv)
}

func _ReservationService_ReserveInstance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReserveInstanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReservationServiceServer).ReserveInstance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReservationService_ReserveInstance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReservationServiceServer).ReserveInstance(ctx, req.(*ReserveInstanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReservationService_DescribeReservation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DescribeReservationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReservationServiceServer).DescribeReservation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReservationService_DescribeReservation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReservationServiceServer).DescribeReservation(ctx, req.(*DescribeReservationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReservationService_CancelReservation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelReservationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReservationServiceServer).CancelReservation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReservationService_CancelReservation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReservationServiceServer).CancelReservation(ctx, req.(*CancelReservationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReservationService_UpdateReservationDeadline_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateReservationDeadlineRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReservationServiceServer).UpdateReservationDeadline(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReservationService_UpdateReservationDeadline_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReservationServiceServer).UpdateReservationDeadline(ctx, req.(*UpdateReservationDeadlineRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReservationService_ListReservations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListReservationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReservationServiceServer).ListReservations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReservationService_ListReservations_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReservationServiceServer).ListReservations(ctx, req.(*ListReservationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ReservationService_ServiceDesc is the grpc.ServiceDesc for ReservationService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ReservationService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "namespace.experimental.compute.ReservationService",
	HandlerType: (*ReservationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ReserveInstance",
			Handler:    _ReservationService_ReserveInstance_Handler,
		},
		{
			MethodName: "DescribeReservation",
			Handler:    _ReservationService_DescribeReservation_Handler,
		},
		{
			MethodName: "CancelReservation",
			Handler:    _ReservationService_CancelReservation_Handler,
		},
		{
			MethodName: "UpdateReservationDeadline",
			Handler:    _ReservationService_UpdateReservationDeadline_Handler,
		},
		{
			MethodName: "ListReservations",
			Handler:    _ReservationService_ListReservations_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/namespace/experimental/compute/reservations.proto",
}
