// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: proto/namespace/cloud/compute/v1beta/command.proto

package computev1beta

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CommandService_RunCommand_FullMethodName     = "/namespace.cloud.compute.v1beta.CommandService/RunCommand"
	CommandService_RunCommandSync_FullMethodName = "/namespace.cloud.compute.v1beta.CommandService/RunCommandSync"
)

// CommandServiceClient is the client API for CommandService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// CommandService allows executing commands in containers running within
// compute instances.
//
// ## Access
//
// Like ComputeService, CommandService is regionalized for fault tolerance.
// Each of the regional API endpoints offers a view into the compute instances
// running at that location. Reach out to Namespace team at support@namespace.so
// for a list of available regions.
//
// ```
// https://{region}.compute.namespaceapis.com:443
// # E.g.:
// https://eu.compute.namespaceapis.com:443
// https://us.compute.namespaceapis.com:443
// ```
//
// ## Authentication
//
// Calls to the CommandService require a *tenant token* or a *workload token*
// passed as a Bearer token as part of each call. These are always required.
//
// A *tenant token* identifies both the workspace that the call operates on, but
// may also constrain the set of actions that the caller may do.
//
// A *workload token* identifies a running instance, and the workspace it is
// running in. Each running instance has a workload token, which is
// automatically made available to services running inside the instance.
//
// A *tenant token* can be obtained using the
// [IAM API](https://buf.build/namespace/cloud/docs/main:namespace.cloud.iam.v1beta).
type CommandServiceClient interface {
	// Runs a command in a container within a running instance. Stdout and stderr
	// are streamed back as individual responses. The final response includes an
	// ExitStatus with the command's exit code.
	//
	// ### Errors
	// - If the instance does not exist, a `NotFound` status is returned.
	// - If the target container does not exist, a `NotFound` status is returned.
	RunCommand(ctx context.Context, in *RunCommandRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[RunCommandResponse], error)
	// Runs a command in a container within a running instance and waits for it
	// to complete. Stdout and stderr are bundled into a single response,
	// similar to CombinedOutput.
	//
	// ### Errors
	// - If the instance does not exist, a `NotFound` status is returned.
	// - If the target container does not exist, a `NotFound` status is returned.
	RunCommandSync(ctx context.Context, in *RunCommandRequest, opts ...grpc.CallOption) (*RunCommandSyncResponse, error)
}

type commandServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCommandServiceClient(cc grpc.ClientConnInterface) CommandServiceClient {
	return &commandServiceClient{cc}
}

func (c *commandServiceClient) RunCommand(ctx context.Context, in *RunCommandRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[RunCommandResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &CommandService_ServiceDesc.Streams[0], CommandService_RunCommand_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[RunCommandRequest, RunCommandResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CommandService_RunCommandClient = grpc.ServerStreamingClient[RunCommandResponse]

func (c *commandServiceClient) RunCommandSync(ctx context.Context, in *RunCommandRequest, opts ...grpc.CallOption) (*RunCommandSyncResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RunCommandSyncResponse)
	err := c.cc.Invoke(ctx, CommandService_RunCommandSync_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CommandServiceServer is the server API for CommandService service.
// All implementations must embed UnimplementedCommandServiceServer
// for forward compatibility.
//
// CommandService allows executing commands in containers running within
// compute instances.
//
// ## Access
//
// Like ComputeService, CommandService is regionalized for fault tolerance.
// Each of the regional API endpoints offers a view into the compute instances
// running at that location. Reach out to Namespace team at support@namespace.so
// for a list of available regions.
//
// ```
// https://{region}.compute.namespaceapis.com:443
// # E.g.:
// https://eu.compute.namespaceapis.com:443
// https://us.compute.namespaceapis.com:443
// ```
//
// ## Authentication
//
// Calls to the CommandService require a *tenant token* or a *workload token*
// passed as a Bearer token as part of each call. These are always required.
//
// A *tenant token* identifies both the workspace that the call operates on, but
// may also constrain the set of actions that the caller may do.
//
// A *workload token* identifies a running instance, and the workspace it is
// running in. Each running instance has a workload token, which is
// automatically made available to services running inside the instance.
//
// A *tenant token* can be obtained using the
// [IAM API](https://buf.build/namespace/cloud/docs/main:namespace.cloud.iam.v1beta).
type CommandServiceServer interface {
	// Runs a command in a container within a running instance. Stdout and stderr
	// are streamed back as individual responses. The final response includes an
	// ExitStatus with the command's exit code.
	//
	// ### Errors
	// - If the instance does not exist, a `NotFound` status is returned.
	// - If the target container does not exist, a `NotFound` status is returned.
	RunCommand(*RunCommandRequest, grpc.ServerStreamingServer[RunCommandResponse]) error
	// Runs a command in a container within a running instance and waits for it
	// to complete. Stdout and stderr are bundled into a single response,
	// similar to CombinedOutput.
	//
	// ### Errors
	// - If the instance does not exist, a `NotFound` status is returned.
	// - If the target container does not exist, a `NotFound` status is returned.
	RunCommandSync(context.Context, *RunCommandRequest) (*RunCommandSyncResponse, error)
	mustEmbedUnimplementedCommandServiceServer()
}

// UnimplementedCommandServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCommandServiceServer struct{}

func (UnimplementedCommandServiceServer) RunCommand(*RunCommandRequest, grpc.ServerStreamingServer[RunCommandResponse]) error {
	return status.Error(codes.Unimplemented, "method RunCommand not implemented")
}
func (UnimplementedCommandServiceServer) RunCommandSync(context.Context, *RunCommandRequest) (*RunCommandSyncResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RunCommandSync not implemented")
}
func (UnimplementedCommandServiceServer) mustEmbedUnimplementedCommandServiceServer() {}
func (UnimplementedCommandServiceServer) testEmbeddedByValue()                        {}

// UnsafeCommandServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CommandServiceServer will
// result in compilation errors.
type UnsafeCommandServiceServer interface {
	mustEmbedUnimplementedCommandServiceServer()
}

func RegisterCommandServiceServer(s grpc.ServiceRegistrar, srv CommandServiceServer) {
	// If the following call panics, it indicates UnimplementedCommandServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CommandService_ServiceDesc, srv)
}

func _CommandService_RunCommand_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(RunCommandRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CommandServiceServer).RunCommand(m, &grpc.GenericServerStream[RunCommandRequest, RunCommandResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CommandService_RunCommandServer = grpc.ServerStreamingServer[RunCommandResponse]

func _CommandService_RunCommandSync_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RunCommandRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommandServiceServer).RunCommandSync(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CommandService_RunCommandSync_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommandServiceServer).RunCommandSync(ctx, req.(*RunCommandRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CommandService_ServiceDesc is the grpc.ServiceDesc for CommandService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CommandService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "namespace.cloud.compute.v1beta.CommandService",
	HandlerType: (*CommandServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RunCommandSync",
			Handler:    _CommandService_RunCommandSync_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "RunCommand",
			Handler:       _CommandService_RunCommand_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/namespace/cloud/compute/v1beta/command.proto",
}
