// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: proto/namespace/cloud/compute/v1beta/observability.proto

package computev1beta

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ObservabilityService_StreamInstanceLogs_FullMethodName       = "/namespace.cloud.compute.v1beta.ObservabilityService/StreamInstanceLogs"
	ObservabilityService_FetchInstanceLogs_FullMethodName        = "/namespace.cloud.compute.v1beta.ObservabilityService/FetchInstanceLogs"
	ObservabilityService_FetchInstanceDiagnostics_FullMethodName = "/namespace.cloud.compute.v1beta.ObservabilityService/FetchInstanceDiagnostics"
	ObservabilityService_FetchInstanceEgress_FullMethodName      = "/namespace.cloud.compute.v1beta.ObservabilityService/FetchInstanceEgress"
)

// ObservabilityServiceClient is the client API for ObservabilityService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ObservabilityService grants you access to logs and metrics of compute resources.
// See https://namespace.so/docs/architecture/compute/observability for an overview.
//
// ## Access
//
// Like ComputeService, ObservabilityService is regionalized for fault tolerance.
// Each of the regional API endpoints offers a view into the compute instances
// running at that location. Reach out to Namespace team at support@namespace.so
// for a list of available regions.
//
// ```
// https://{region}.compute.namespaceapis.com:443
// # E.g.:
// https://eu.compute.namespaceapis.com:443
// https://us.compute.namespaceapis.com:443
// ```
//
// ## Authentication
//
// Calls to the ObservabilityService require a *tenant token* passed as a Bearer
// token as part of each call. These are always required.
//
// A *tenant token* identifies both the workspace that the call operates on, but
// may also constrain the set of actions that the caller may do.
//
// A *tenant token* can be obtained using the
// [IAM API](https://buf.build/namespace/cloud/docs/main:namespace.cloud.iam.v1beta).
type ObservabilityServiceClient interface {
	// Stream logs of a particular instance. If `follow` is set, waits for additional logs
	// as well. If following, and the instance is shut down, the log stream will terminate.
	//
	// ### Errors
	// - If no instance id is provided, a `InvalidArgument` status is returned.
	// - If the provided id does not match any known instance, a `NotFound` status is returned.
	StreamInstanceLogs(ctx context.Context, in *StreamInstanceLogsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[LogBlock], error)
	// Fetches logs of a particular instance (or instances). The instances can still be running.
	//
	// A time range is required to use this API. Either the lookups being done have naturally a
	// range, e.g. last 30 minutes, or you should lookup the time that the instances ran and
	// pass those to the API.
	//
	// If no time range is specified, the serving cost might be too high, and the API server may
	// elect to reject the call.
	FetchInstanceLogs(ctx context.Context, in *FetchInstanceLogsRequest, opts ...grpc.CallOption) (*FetchInstanceLogsResponse, error)
	// Fetches diagnostic findings for a particular instance.
	// Requires the {"instance/o11y/oom", "list"} permission for the instance.
	//
	// ### Errors
	// - If no instance id is provided, an `InvalidArgument` status is returned.
	FetchInstanceDiagnostics(ctx context.Context, in *FetchInstanceDiagnosticsRequest, opts ...grpc.CallOption) (*FetchInstanceDiagnosticsResponse, error)
	FetchInstanceEgress(ctx context.Context, in *FetchInstanceEgressRequest, opts ...grpc.CallOption) (*FetchInstanceEgressResponse, error)
}

type observabilityServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewObservabilityServiceClient(cc grpc.ClientConnInterface) ObservabilityServiceClient {
	return &observabilityServiceClient{cc}
}

func (c *observabilityServiceClient) StreamInstanceLogs(ctx context.Context, in *StreamInstanceLogsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[LogBlock], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ObservabilityService_ServiceDesc.Streams[0], ObservabilityService_StreamInstanceLogs_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamInstanceLogsRequest, LogBlock]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ObservabilityService_StreamInstanceLogsClient = grpc.ServerStreamingClient[LogBlock]

func (c *observabilityServiceClient) FetchInstanceLogs(ctx context.Context, in *FetchInstanceLogsRequest, opts ...grpc.CallOption) (*FetchInstanceLogsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FetchInstanceLogsResponse)
	err := c.cc.Invoke(ctx, ObservabilityService_FetchInstanceLogs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *observabilityServiceClient) FetchInstanceDiagnostics(ctx context.Context, in *FetchInstanceDiagnosticsRequest, opts ...grpc.CallOption) (*FetchInstanceDiagnosticsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FetchInstanceDiagnosticsResponse)
	err := c.cc.Invoke(ctx, ObservabilityService_FetchInstanceDiagnostics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *observabilityServiceClient) FetchInstanceEgress(ctx context.Context, in *FetchInstanceEgressRequest, opts ...grpc.CallOption) (*FetchInstanceEgressResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FetchInstanceEgressResponse)
	err := c.cc.Invoke(ctx, ObservabilityService_FetchInstanceEgress_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ObservabilityServiceServer is the server API for ObservabilityService service.
// All implementations must embed UnimplementedObservabilityServiceServer
// for forward compatibility.
//
// ObservabilityService grants you access to logs and metrics of compute resources.
// See https://namespace.so/docs/architecture/compute/observability for an overview.
//
// ## Access
//
// Like ComputeService, ObservabilityService is regionalized for fault tolerance.
// Each of the regional API endpoints offers a view into the compute instances
// running at that location. Reach out to Namespace team at support@namespace.so
// for a list of available regions.
//
// ```
// https://{region}.compute.namespaceapis.com:443
// # E.g.:
// https://eu.compute.namespaceapis.com:443
// https://us.compute.namespaceapis.com:443
// ```
//
// ## Authentication
//
// Calls to the ObservabilityService require a *tenant token* passed as a Bearer
// token as part of each call. These are always required.
//
// A *tenant token* identifies both the workspace that the call operates on, but
// may also constrain the set of actions that the caller may do.
//
// A *tenant token* can be obtained using the
// [IAM API](https://buf.build/namespace/cloud/docs/main:namespace.cloud.iam.v1beta).
type ObservabilityServiceServer interface {
	// Stream logs of a particular instance. If `follow` is set, waits for additional logs
	// as well. If following, and the instance is shut down, the log stream will terminate.
	//
	// ### Errors
	// - If no instance id is provided, a `InvalidArgument` status is returned.
	// - If the provided id does not match any known instance, a `NotFound` status is returned.
	StreamInstanceLogs(*StreamInstanceLogsRequest, grpc.ServerStreamingServer[LogBlock]) error
	// Fetches logs of a particular instance (or instances). The instances can still be running.
	//
	// A time range is required to use this API. Either the lookups being done have naturally a
	// range, e.g. last 30 minutes, or you should lookup the time that the instances ran and
	// pass those to the API.
	//
	// If no time range is specified, the serving cost might be too high, and the API server may
	// elect to reject the call.
	FetchInstanceLogs(context.Context, *FetchInstanceLogsRequest) (*FetchInstanceLogsResponse, error)
	// Fetches diagnostic findings for a particular instance.
	// Requires the {"instance/o11y/oom", "list"} permission for the instance.
	//
	// ### Errors
	// - If no instance id is provided, an `InvalidArgument` status is returned.
	FetchInstanceDiagnostics(context.Context, *FetchInstanceDiagnosticsRequest) (*FetchInstanceDiagnosticsResponse, error)
	FetchInstanceEgress(context.Context, *FetchInstanceEgressRequest) (*FetchInstanceEgressResponse, error)
	mustEmbedUnimplementedObservabilityServiceServer()
}

// UnimplementedObservabilityServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedObservabilityServiceServer struct{}

func (UnimplementedObservabilityServiceServer) StreamInstanceLogs(*StreamInstanceLogsRequest, grpc.ServerStreamingServer[LogBlock]) error {
	return status.Error(codes.Unimplemented, "method StreamInstanceLogs not implemented")
}
func (UnimplementedObservabilityServiceServer) FetchInstanceLogs(context.Context, *FetchInstanceLogsRequest) (*FetchInstanceLogsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FetchInstanceLogs not implemented")
}
func (UnimplementedObservabilityServiceServer) FetchInstanceDiagnostics(context.Context, *FetchInstanceDiagnosticsRequest) (*FetchInstanceDiagnosticsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FetchInstanceDiagnostics not implemented")
}
func (UnimplementedObservabilityServiceServer) FetchInstanceEgress(context.Context, *FetchInstanceEgressRequest) (*FetchInstanceEgressResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FetchInstanceEgress not implemented")
}
func (UnimplementedObservabilityServiceServer) mustEmbedUnimplementedObservabilityServiceServer() {}
func (UnimplementedObservabilityServiceServer) testEmbeddedByValue()                              {}

// UnsafeObservabilityServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ObservabilityServiceServer will
// result in compilation errors.
type UnsafeObservabilityServiceServer interface {
	mustEmbedUnimplementedObservabilityServiceServer()
}

func RegisterObservabilityServiceServer(s grpc.ServiceRegistrar, srv ObservabilityServiceServer) {
	// If the following call panics, it indicates UnimplementedObservabilityServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ObservabilityService_ServiceDesc, srv)
}

func _ObservabilityService_StreamInstanceLogs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamInstanceLogsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ObservabilityServiceServer).StreamInstanceLogs(m, &grpc.GenericServerStream[StreamInstanceLogsRequest, LogBlock]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ObservabilityService_StreamInstanceLogsServer = grpc.ServerStreamingServer[LogBlock]

func _ObservabilityService_FetchInstanceLogs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FetchInstanceLogsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ObservabilityServiceServer).FetchInstanceLogs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ObservabilityService_FetchInstanceLogs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ObservabilityServiceServer).FetchInstanceLogs(ctx, req.(*FetchInstanceLogsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ObservabilityService_FetchInstanceDiagnostics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FetchInstanceDiagnosticsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ObservabilityServiceServer).FetchInstanceDiagnostics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ObservabilityService_FetchInstanceDiagnostics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ObservabilityServiceServer).FetchInstanceDiagnostics(ctx, req.(*FetchInstanceDiagnosticsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ObservabilityService_FetchInstanceEgress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FetchInstanceEgressRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ObservabilityServiceServer).FetchInstanceEgress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ObservabilityService_FetchInstanceEgress_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ObservabilityServiceServer).FetchInstanceEgress(ctx, req.(*FetchInstanceEgressRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ObservabilityService_ServiceDesc is the grpc.ServiceDesc for ObservabilityService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ObservabilityService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "namespace.cloud.compute.v1beta.ObservabilityService",
	HandlerType: (*ObservabilityServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FetchInstanceLogs",
			Handler:    _ObservabilityService_FetchInstanceLogs_Handler,
		},
		{
			MethodName: "FetchInstanceDiagnostics",
			Handler:    _ObservabilityService_FetchInstanceDiagnostics_Handler,
		},
		{
			MethodName: "FetchInstanceEgress",
			Handler:    _ObservabilityService_FetchInstanceEgress_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamInstanceLogs",
			Handler:       _ObservabilityService_StreamInstanceLogs_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/namespace/cloud/compute/v1beta/observability.proto",
}
