// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: proto/namespace/cloud/compute/v1beta/storage.proto

package computev1beta

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	StorageService_GetCacheVolume_FullMethodName                  = "/namespace.cloud.compute.v1beta.StorageService/GetCacheVolume"
	StorageService_ListCacheVolumes_FullMethodName                = "/namespace.cloud.compute.v1beta.StorageService/ListCacheVolumes"
	StorageService_GetVolumeTagSummary_FullMethodName             = "/namespace.cloud.compute.v1beta.StorageService/GetVolumeTagSummary"
	StorageService_ListVolumeTagSummaries_FullMethodName          = "/namespace.cloud.compute.v1beta.StorageService/ListVolumeTagSummaries"
	StorageService_DestroyCacheVolume_FullMethodName              = "/namespace.cloud.compute.v1beta.StorageService/DestroyCacheVolume"
	StorageService_ListPersistentVolumes_FullMethodName           = "/namespace.cloud.compute.v1beta.StorageService/ListPersistentVolumes"
	StorageService_DestroyPersistentVolumes_FullMethodName        = "/namespace.cloud.compute.v1beta.StorageService/DestroyPersistentVolumes"
	StorageService_DescribePersistentVolume_FullMethodName        = "/namespace.cloud.compute.v1beta.StorageService/DescribePersistentVolume"
	StorageService_ListPersistentVolumeSnapshots_FullMethodName   = "/namespace.cloud.compute.v1beta.StorageService/ListPersistentVolumeSnapshots"
	StorageService_DestroyPersistentVolumeSnapshot_FullMethodName = "/namespace.cloud.compute.v1beta.StorageService/DestroyPersistentVolumeSnapshot"
)

// StorageServiceClient is the client API for StorageService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// StorageService allows the management of storage used by a tenant.
// Accessible storage classes include [Cache Volumes](https://namespace.so/docs/architecture/storage/cache-volumes)
// and Persistent Volumes.
//
// ## Access
//
// Like ComputeService, StorageService is regionalized for fault tolerance.
// Reach out to Namespace team at support@namespace.so for a list of available regions.
//
// ```
// https://{region}.compute.namespaceapis.com:443
// # E.g.:
// https://eu.compute.namespaceapis.com:443
// https://us.compute.namespaceapis.com:443
// ```
//
// ## Authentication
//
// Calls to the StorageService require a *tenant token* passed as a Bearer token as
// part of each call. These are always required.
//
// A *tenant token* identifies both the workspace that the call operates on, but
// may also constrain the set of actions that the caller may do.
//
// A *tenant token* can be obtained using the
// [IAM API](https://buf.build/namespace/cloud/docs/main:namespace.cloud.iam.v1beta).
type StorageServiceClient interface {
	// Returns a Cache Volume.
	GetCacheVolume(ctx context.Context, in *GetCacheVolumeRequest, opts ...grpc.CallOption) (*GetCacheVolumeResponse, error)
	// Returns a list of all Cache Volumes used by this tenant.
	ListCacheVolumes(ctx context.Context, in *ListCacheVolumesRequest, opts ...grpc.CallOption) (*ListCacheVolumesResponse, error)
	// Produces a summary for a Cache Volume tag used by this tenant.
	GetVolumeTagSummary(ctx context.Context, in *GetVolumeTagSummaryRequest, opts ...grpc.CallOption) (*GetVolumeTagSummaryResponse, error)
	// Produces a summary for each Cache Volume tag used by this tenant.
	ListVolumeTagSummaries(ctx context.Context, in *ListVolumeTagSummariesRequest, opts ...grpc.CallOption) (*ListVolumeTagSummariesResponse, error)
	// Release all Cache Volumes belonging to a selected `tag`. This operation cannot be undone.
	//
	// ### Errors
	// - If no volume tag is provided, a `InvalidArgument` status is returned.
	// - If the provided volume tag does not match any known volume tag, a `NotFound` status is returned.
	DestroyCacheVolume(ctx context.Context, in *DestroyCacheVolumeRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Returns a list of all Persistent Volumes for a given tag.
	ListPersistentVolumes(ctx context.Context, in *ListPersistentVolumesRequest, opts ...grpc.CallOption) (*ListPersistentVolumesResponse, error)
	// Destroys Persistent Volumes matching the given criteria. Returns the metadata of destroyed volumes.
	//
	// At least one matcher (id or tag) must be specified. For safety, the IS_NOT operator is denied.
	//
	// ### Errors
	// - If no matcher is provided, a `InvalidArgument` status is returned.
	// - If IS_NOT operator is used, a `InvalidArgument` status is returned.
	// - If no volumes are found matching criteria, a `NotFound` status is returned.
	DestroyPersistentVolumes(ctx context.Context, in *DestroyPersistentVolumesRequest, opts ...grpc.CallOption) (*DestroyPersistentVolumesResponse, error)
	// Returns details of a Persistent Volume.
	//
	// ### Errors
	// - If the volume does not exist, a `NotFound` status is returned.
	DescribePersistentVolume(ctx context.Context, in *DescribePersistentVolumeRequest, opts ...grpc.CallOption) (*DescribePersistentVolumeResponse, error)
	// Returns all snapshots of a Persistent Volume.
	ListPersistentVolumeSnapshots(ctx context.Context, in *ListPersistentVolumeSnapshotsRequest, opts ...grpc.CallOption) (*ListPersistentVolumeSnapshotsResponse, error)
	// Marks a persistent volume snapshot as abandoned. Abandoned snapshots are excluded
	// when selecting a base snapshot for new volumes. This is useful for marking corrupted
	// or unwanted snapshots without destroying the volume itself.
	//
	// ### Errors
	// - If the snapshot does not exist, a `NotFound` status is returned.
	// - If the snapshot is still attached to an instance, a `FailedPrecondition` status is returned.
	DestroyPersistentVolumeSnapshot(ctx context.Context, in *DestroyPersistentVolumeSnapshotRequest, opts ...grpc.CallOption) (*DestroyPersistentVolumeSnapshotResponse, error)
}

type storageServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewStorageServiceClient(cc grpc.ClientConnInterface) StorageServiceClient {
	return &storageServiceClient{cc}
}

func (c *storageServiceClient) GetCacheVolume(ctx context.Context, in *GetCacheVolumeRequest, opts ...grpc.CallOption) (*GetCacheVolumeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCacheVolumeResponse)
	err := c.cc.Invoke(ctx, StorageService_GetCacheVolume_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageServiceClient) ListCacheVolumes(ctx context.Context, in *ListCacheVolumesRequest, opts ...grpc.CallOption) (*ListCacheVolumesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListCacheVolumesResponse)
	err := c.cc.Invoke(ctx, StorageService_ListCacheVolumes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageServiceClient) GetVolumeTagSummary(ctx context.Context, in *GetVolumeTagSummaryRequest, opts ...grpc.CallOption) (*GetVolumeTagSummaryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetVolumeTagSummaryResponse)
	err := c.cc.Invoke(ctx, StorageService_GetVolumeTagSummary_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageServiceClient) ListVolumeTagSummaries(ctx context.Context, in *ListVolumeTagSummariesRequest, opts ...grpc.CallOption) (*ListVolumeTagSummariesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListVolumeTagSummariesResponse)
	err := c.cc.Invoke(ctx, StorageService_ListVolumeTagSummaries_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageServiceClient) DestroyCacheVolume(ctx context.Context, in *DestroyCacheVolumeRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, StorageService_DestroyCacheVolume_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageServiceClient) ListPersistentVolumes(ctx context.Context, in *ListPersistentVolumesRequest, opts ...grpc.CallOption) (*ListPersistentVolumesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListPersistentVolumesResponse)
	err := c.cc.Invoke(ctx, StorageService_ListPersistentVolumes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageServiceClient) DestroyPersistentVolumes(ctx context.Context, in *DestroyPersistentVolumesRequest, opts ...grpc.CallOption) (*DestroyPersistentVolumesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DestroyPersistentVolumesResponse)
	err := c.cc.Invoke(ctx, StorageService_DestroyPersistentVolumes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageServiceClient) DescribePersistentVolume(ctx context.Context, in *DescribePersistentVolumeRequest, opts ...grpc.CallOption) (*DescribePersistentVolumeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DescribePersistentVolumeResponse)
	err := c.cc.Invoke(ctx, StorageService_DescribePersistentVolume_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageServiceClient) ListPersistentVolumeSnapshots(ctx context.Context, in *ListPersistentVolumeSnapshotsRequest, opts ...grpc.CallOption) (*ListPersistentVolumeSnapshotsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListPersistentVolumeSnapshotsResponse)
	err := c.cc.Invoke(ctx, StorageService_ListPersistentVolumeSnapshots_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageServiceClient) DestroyPersistentVolumeSnapshot(ctx context.Context, in *DestroyPersistentVolumeSnapshotRequest, opts ...grpc.CallOption) (*DestroyPersistentVolumeSnapshotResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DestroyPersistentVolumeSnapshotResponse)
	err := c.cc.Invoke(ctx, StorageService_DestroyPersistentVolumeSnapshot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StorageServiceServer is the server API for StorageService service.
// All implementations must embed UnimplementedStorageServiceServer
// for forward compatibility.
//
// StorageService allows the management of storage used by a tenant.
// Accessible storage classes include [Cache Volumes](https://namespace.so/docs/architecture/storage/cache-volumes)
// and Persistent Volumes.
//
// ## Access
//
// Like ComputeService, StorageService is regionalized for fault tolerance.
// Reach out to Namespace team at support@namespace.so for a list of available regions.
//
// ```
// https://{region}.compute.namespaceapis.com:443
// # E.g.:
// https://eu.compute.namespaceapis.com:443
// https://us.compute.namespaceapis.com:443
// ```
//
// ## Authentication
//
// Calls to the StorageService require a *tenant token* passed as a Bearer token as
// part of each call. These are always required.
//
// A *tenant token* identifies both the workspace that the call operates on, but
// may also constrain the set of actions that the caller may do.
//
// A *tenant token* can be obtained using the
// [IAM API](https://buf.build/namespace/cloud/docs/main:namespace.cloud.iam.v1beta).
type StorageServiceServer interface {
	// Returns a Cache Volume.
	GetCacheVolume(context.Context, *GetCacheVolumeRequest) (*GetCacheVolumeResponse, error)
	// Returns a list of all Cache Volumes used by this tenant.
	ListCacheVolumes(context.Context, *ListCacheVolumesRequest) (*ListCacheVolumesResponse, error)
	// Produces a summary for a Cache Volume tag used by this tenant.
	GetVolumeTagSummary(context.Context, *GetVolumeTagSummaryRequest) (*GetVolumeTagSummaryResponse, error)
	// Produces a summary for each Cache Volume tag used by this tenant.
	ListVolumeTagSummaries(context.Context, *ListVolumeTagSummariesRequest) (*ListVolumeTagSummariesResponse, error)
	// Release all Cache Volumes belonging to a selected `tag`. This operation cannot be undone.
	//
	// ### Errors
	// - If no volume tag is provided, a `InvalidArgument` status is returned.
	// - If the provided volume tag does not match any known volume tag, a `NotFound` status is returned.
	DestroyCacheVolume(context.Context, *DestroyCacheVolumeRequest) (*emptypb.Empty, error)
	// Returns a list of all Persistent Volumes for a given tag.
	ListPersistentVolumes(context.Context, *ListPersistentVolumesRequest) (*ListPersistentVolumesResponse, error)
	// Destroys Persistent Volumes matching the given criteria. Returns the metadata of destroyed volumes.
	//
	// At least one matcher (id or tag) must be specified. For safety, the IS_NOT operator is denied.
	//
	// ### Errors
	// - If no matcher is provided, a `InvalidArgument` status is returned.
	// - If IS_NOT operator is used, a `InvalidArgument` status is returned.
	// - If no volumes are found matching criteria, a `NotFound` status is returned.
	DestroyPersistentVolumes(context.Context, *DestroyPersistentVolumesRequest) (*DestroyPersistentVolumesResponse, error)
	// Returns details of a Persistent Volume.
	//
	// ### Errors
	// - If the volume does not exist, a `NotFound` status is returned.
	DescribePersistentVolume(context.Context, *DescribePersistentVolumeRequest) (*DescribePersistentVolumeResponse, error)
	// Returns all snapshots of a Persistent Volume.
	ListPersistentVolumeSnapshots(context.Context, *ListPersistentVolumeSnapshotsRequest) (*ListPersistentVolumeSnapshotsResponse, error)
	// Marks a persistent volume snapshot as abandoned. Abandoned snapshots are excluded
	// when selecting a base snapshot for new volumes. This is useful for marking corrupted
	// or unwanted snapshots without destroying the volume itself.
	//
	// ### Errors
	// - If the snapshot does not exist, a `NotFound` status is returned.
	// - If the snapshot is still attached to an instance, a `FailedPrecondition` status is returned.
	DestroyPersistentVolumeSnapshot(context.Context, *DestroyPersistentVolumeSnapshotRequest) (*DestroyPersistentVolumeSnapshotResponse, error)
	mustEmbedUnimplementedStorageServiceServer()
}

// UnimplementedStorageServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedStorageServiceServer struct{}

func (UnimplementedStorageServiceServer) GetCacheVolume(context.Context, *GetCacheVolumeRequest) (*GetCacheVolumeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCacheVolume not implemented")
}
func (UnimplementedStorageServiceServer) ListCacheVolumes(context.Context, *ListCacheVolumesRequest) (*ListCacheVolumesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListCacheVolumes not implemented")
}
func (UnimplementedStorageServiceServer) GetVolumeTagSummary(context.Context, *GetVolumeTagSummaryRequest) (*GetVolumeTagSummaryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetVolumeTagSummary not implemented")
}
func (UnimplementedStorageServiceServer) ListVolumeTagSummaries(context.Context, *ListVolumeTagSummariesRequest) (*ListVolumeTagSummariesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListVolumeTagSummaries not implemented")
}
func (UnimplementedStorageServiceServer) DestroyCacheVolume(context.Context, *DestroyCacheVolumeRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DestroyCacheVolume not implemented")
}
func (UnimplementedStorageServiceServer) ListPersistentVolumes(context.Context, *ListPersistentVolumesRequest) (*ListPersistentVolumesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListPersistentVolumes not implemented")
}
func (UnimplementedStorageServiceServer) DestroyPersistentVolumes(context.Context, *DestroyPersistentVolumesRequest) (*DestroyPersistentVolumesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DestroyPersistentVolumes not implemented")
}
func (UnimplementedStorageServiceServer) DescribePersistentVolume(context.Context, *DescribePersistentVolumeRequest) (*DescribePersistentVolumeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DescribePersistentVolume not implemented")
}
func (UnimplementedStorageServiceServer) ListPersistentVolumeSnapshots(context.Context, *ListPersistentVolumeSnapshotsRequest) (*ListPersistentVolumeSnapshotsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListPersistentVolumeSnapshots not implemented")
}
func (UnimplementedStorageServiceServer) DestroyPersistentVolumeSnapshot(context.Context, *DestroyPersistentVolumeSnapshotRequest) (*DestroyPersistentVolumeSnapshotResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DestroyPersistentVolumeSnapshot not implemented")
}
func (UnimplementedStorageServiceServer) mustEmbedUnimplementedStorageServiceServer() {}
func (UnimplementedStorageServiceServer) testEmbeddedByValue()                        {}

// UnsafeStorageServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StorageServiceServer will
// result in compilation errors.
type UnsafeStorageServiceServer interface {
	mustEmbedUnimplementedStorageServiceServer()
}

func RegisterStorageServiceServer(s grpc.ServiceRegistrar, srv StorageServiceServer) {
	// If the following call panics, it indicates UnimplementedStorageServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&StorageService_ServiceDesc, srv)
}

func _StorageService_GetCacheVolume_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCacheVolumeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServiceServer).GetCacheVolume(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StorageService_GetCacheVolume_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServiceServer).GetCacheVolume(ctx, req.(*GetCacheVolumeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageService_ListCacheVolumes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCacheVolumesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServiceServer).ListCacheVolumes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StorageService_ListCacheVolumes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServiceServer).ListCacheVolumes(ctx, req.(*ListCacheVolumesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageService_GetVolumeTagSummary_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetVolumeTagSummaryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServiceServer).GetVolumeTagSummary(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StorageService_GetVolumeTagSummary_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServiceServer).GetVolumeTagSummary(ctx, req.(*GetVolumeTagSummaryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageService_ListVolumeTagSummaries_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListVolumeTagSummariesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServiceServer).ListVolumeTagSummaries(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StorageService_ListVolumeTagSummaries_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServiceServer).ListVolumeTagSummaries(ctx, req.(*ListVolumeTagSummariesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageService_DestroyCacheVolume_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DestroyCacheVolumeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServiceServer).DestroyCacheVolume(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StorageService_DestroyCacheVolume_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServiceServer).DestroyCacheVolume(ctx, req.(*DestroyCacheVolumeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageService_ListPersistentVolumes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPersistentVolumesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServiceServer).ListPersistentVolumes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StorageService_ListPersistentVolumes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServiceServer).ListPersistentVolumes(ctx, req.(*ListPersistentVolumesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageService_DestroyPersistentVolumes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DestroyPersistentVolumesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServiceServer).DestroyPersistentVolumes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StorageService_DestroyPersistentVolumes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServiceServer).DestroyPersistentVolumes(ctx, req.(*DestroyPersistentVolumesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageService_DescribePersistentVolume_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DescribePersistentVolumeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServiceServer).DescribePersistentVolume(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StorageService_DescribePersistentVolume_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServiceServer).DescribePersistentVolume(ctx, req.(*DescribePersistentVolumeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageService_ListPersistentVolumeSnapshots_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPersistentVolumeSnapshotsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServiceServer).ListPersistentVolumeSnapshots(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StorageService_ListPersistentVolumeSnapshots_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServiceServer).ListPersistentVolumeSnapshots(ctx, req.(*ListPersistentVolumeSnapshotsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageService_DestroyPersistentVolumeSnapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DestroyPersistentVolumeSnapshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServiceServer).DestroyPersistentVolumeSnapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StorageService_DestroyPersistentVolumeSnapshot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServiceServer).DestroyPersistentVolumeSnapshot(ctx, req.(*DestroyPersistentVolumeSnapshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// StorageService_ServiceDesc is the grpc.ServiceDesc for StorageService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StorageService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "namespace.cloud.compute.v1beta.StorageService",
	HandlerType: (*StorageServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetCacheVolume",
			Handler:    _StorageService_GetCacheVolume_Handler,
		},
		{
			MethodName: "ListCacheVolumes",
			Handler:    _StorageService_ListCacheVolumes_Handler,
		},
		{
			MethodName: "GetVolumeTagSummary",
			Handler:    _StorageService_GetVolumeTagSummary_Handler,
		},
		{
			MethodName: "ListVolumeTagSummaries",
			Handler:    _StorageService_ListVolumeTagSummaries_Handler,
		},
		{
			MethodName: "DestroyCacheVolume",
			Handler:    _StorageService_DestroyCacheVolume_Handler,
		},
		{
			MethodName: "ListPersistentVolumes",
			Handler:    _StorageService_ListPersistentVolumes_Handler,
		},
		{
			MethodName: "DestroyPersistentVolumes",
			Handler:    _StorageService_DestroyPersistentVolumes_Handler,
		},
		{
			MethodName: "DescribePersistentVolume",
			Handler:    _StorageService_DescribePersistentVolume_Handler,
		},
		{
			MethodName: "ListPersistentVolumeSnapshots",
			Handler:    _StorageService_ListPersistentVolumeSnapshots_Handler,
		},
		{
			MethodName: "DestroyPersistentVolumeSnapshot",
			Handler:    _StorageService_DestroyPersistentVolumeSnapshot_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/namespace/cloud/compute/v1beta/storage.proto",
}
