// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: proto/namespace/stdlib/labels.proto

package stdlib

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LabelFilterEntry_LabelFilterOp int32

const (
	LabelFilterEntry_UNKNOWN   LabelFilterEntry_LabelFilterOp = 0
	LabelFilterEntry_EQUAL     LabelFilterEntry_LabelFilterOp = 1
	LabelFilterEntry_NOT_EQUAL LabelFilterEntry_LabelFilterOp = 2
	LabelFilterEntry_EXIST     LabelFilterEntry_LabelFilterOp = 3
)

// Enum value maps for LabelFilterEntry_LabelFilterOp.
var (
	LabelFilterEntry_LabelFilterOp_name = map[int32]string{
		0: "UNKNOWN",
		1: "EQUAL",
		2: "NOT_EQUAL",
		3: "EXIST",
	}
	LabelFilterEntry_LabelFilterOp_value = map[string]int32{
		"UNKNOWN":   0,
		"EQUAL":     1,
		"NOT_EQUAL": 2,
		"EXIST":     3,
	}
)

func (x LabelFilterEntry_LabelFilterOp) Enum() *LabelFilterEntry_LabelFilterOp {
	p := new(LabelFilterEntry_LabelFilterOp)
	*p = x
	return p
}

func (x LabelFilterEntry_LabelFilterOp) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LabelFilterEntry_LabelFilterOp) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_namespace_stdlib_labels_proto_enumTypes[0].Descriptor()
}

func (LabelFilterEntry_LabelFilterOp) Type() protoreflect.EnumType {
	return &file_proto_namespace_stdlib_labels_proto_enumTypes[0]
}

func (x LabelFilterEntry_LabelFilterOp) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LabelFilterEntry_LabelFilterOp.Descriptor instead.
func (LabelFilterEntry_LabelFilterOp) EnumDescriptor() ([]byte, []int) {
	return file_proto_namespace_stdlib_labels_proto_rawDescGZIP(), []int{1, 0}
}

// Labels are key/value pairs attached to entities such as tenants.
type Label struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// A name is an string up to 63 bytes that matches the regular expression `^[a-z]([a-z0-9-.]*[a-z0-9])?$`.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Label values are arbitrary values up to 255 bytes.
	Value         string `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Label) Reset() {
	*x = Label{}
	mi := &file_proto_namespace_stdlib_labels_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Label) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Label) ProtoMessage() {}

func (x *Label) ProtoReflect() protoreflect.Message {
	mi := &file_proto_namespace_stdlib_labels_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Label.ProtoReflect.Descriptor instead.
func (*Label) Descriptor() ([]byte, []int) {
	return file_proto_namespace_stdlib_labels_proto_rawDescGZIP(), []int{0}
}

func (x *Label) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Label) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type LabelFilterEntry struct {
	state         protoimpl.MessageState         `protogen:"open.v1"`
	Name          string                         `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value         string                         `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Op            LabelFilterEntry_LabelFilterOp `protobuf:"varint,3,opt,name=op,proto3,enum=namespace.stdlib.LabelFilterEntry_LabelFilterOp" json:"op,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LabelFilterEntry) Reset() {
	*x = LabelFilterEntry{}
	mi := &file_proto_namespace_stdlib_labels_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LabelFilterEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LabelFilterEntry) ProtoMessage() {}

func (x *LabelFilterEntry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_namespace_stdlib_labels_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LabelFilterEntry.ProtoReflect.Descriptor instead.
func (*LabelFilterEntry) Descriptor() ([]byte, []int) {
	return file_proto_namespace_stdlib_labels_proto_rawDescGZIP(), []int{1}
}

func (x *LabelFilterEntry) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *LabelFilterEntry) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *LabelFilterEntry) GetOp() LabelFilterEntry_LabelFilterOp {
	if x != nil {
		return x.Op
	}
	return LabelFilterEntry_UNKNOWN
}

var File_proto_namespace_stdlib_labels_proto protoreflect.FileDescriptor

const file_proto_namespace_stdlib_labels_proto_rawDesc = "" +
	"\n" +
	"#proto/namespace/stdlib/labels.proto\x12\x10namespace.stdlib\"1\n" +
	"\x05Label\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"\xc1\x01\n" +
	"\x10LabelFilterEntry\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\x12@\n" +
	"\x02op\x18\x03 \x01(\x0e20.namespace.stdlib.LabelFilterEntry.LabelFilterOpR\x02op\"A\n" +
	"\rLabelFilterOp\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\t\n" +
	"\x05EQUAL\x10\x01\x12\r\n" +
	"\tNOT_EQUAL\x10\x02\x12\t\n" +
	"\x05EXIST\x10\x03B\xbd\x01\n" +
	"\x14com.namespace.stdlibB\vLabelsProtoP\x01Z5namespacelabs.dev/integrations/proto/namespace/stdlib\xa2\x02\x03NSX\xaa\x02\x10Namespace.Stdlib\xca\x02\x11Namespace_\\Stdlib\xe2\x02\x1dNamespace_\\Stdlib\\GPBMetadata\xea\x02\x11Namespace::Stdlibb\x06proto3"

var (
	file_proto_namespace_stdlib_labels_proto_rawDescOnce sync.Once
	file_proto_namespace_stdlib_labels_proto_rawDescData []byte
)

func file_proto_namespace_stdlib_labels_proto_rawDescGZIP() []byte {
	file_proto_namespace_stdlib_labels_proto_rawDescOnce.Do(func() {
		file_proto_namespace_stdlib_labels_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_namespace_stdlib_labels_proto_rawDesc), len(file_proto_namespace_stdlib_labels_proto_rawDesc)))
	})
	return file_proto_namespace_stdlib_labels_proto_rawDescData
}

var file_proto_namespace_stdlib_labels_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_namespace_stdlib_labels_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_namespace_stdlib_labels_proto_goTypes = []any{
	(LabelFilterEntry_LabelFilterOp)(0), // 0: namespace.stdlib.LabelFilterEntry.LabelFilterOp
	(*Label)(nil),                       // 1: namespace.stdlib.Label
	(*LabelFilterEntry)(nil),            // 2: namespace.stdlib.LabelFilterEntry
}
var file_proto_namespace_stdlib_labels_proto_depIdxs = []int32{
	0, // 0: namespace.stdlib.LabelFilterEntry.op:type_name -> namespace.stdlib.LabelFilterEntry.LabelFilterOp
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_namespace_stdlib_labels_proto_init() }
func file_proto_namespace_stdlib_labels_proto_init() {
	if File_proto_namespace_stdlib_labels_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_namespace_stdlib_labels_proto_rawDesc), len(file_proto_namespace_stdlib_labels_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_namespace_stdlib_labels_proto_goTypes,
		DependencyIndexes: file_proto_namespace_stdlib_labels_proto_depIdxs,
		EnumInfos:         file_proto_namespace_stdlib_labels_proto_enumTypes,
		MessageInfos:      file_proto_namespace_stdlib_labels_proto_msgTypes,
	}.Build()
	File_proto_namespace_stdlib_labels_proto = out.File
	file_proto_namespace_stdlib_labels_proto_goTypes = nil
	file_proto_namespace_stdlib_labels_proto_depIdxs = nil
}
