// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: proto/namespace/cloud/compute/v1beta/compute.proto

package computev1betaconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	v1beta "namespacelabs.dev/integrations/proto/namespace/cloud/compute/v1beta"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// ComputeServiceName is the fully-qualified name of the ComputeService service.
	ComputeServiceName = "namespace.cloud.compute.v1beta.ComputeService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// ComputeServiceCreateInstanceProcedure is the fully-qualified name of the ComputeService's
	// CreateInstance RPC.
	ComputeServiceCreateInstanceProcedure = "/namespace.cloud.compute.v1beta.ComputeService/CreateInstance"
	// ComputeServiceWaitInstanceProcedure is the fully-qualified name of the ComputeService's
	// WaitInstance RPC.
	ComputeServiceWaitInstanceProcedure = "/namespace.cloud.compute.v1beta.ComputeService/WaitInstance"
	// ComputeServiceWaitInstanceSyncProcedure is the fully-qualified name of the ComputeService's
	// WaitInstanceSync RPC.
	ComputeServiceWaitInstanceSyncProcedure = "/namespace.cloud.compute.v1beta.ComputeService/WaitInstanceSync"
	// ComputeServiceExtendInstanceProcedure is the fully-qualified name of the ComputeService's
	// ExtendInstance RPC.
	ComputeServiceExtendInstanceProcedure = "/namespace.cloud.compute.v1beta.ComputeService/ExtendInstance"
	// ComputeServiceStartContainersProcedure is the fully-qualified name of the ComputeService's
	// StartContainers RPC.
	ComputeServiceStartContainersProcedure = "/namespace.cloud.compute.v1beta.ComputeService/StartContainers"
	// ComputeServiceDescribeInstanceProcedure is the fully-qualified name of the ComputeService's
	// DescribeInstance RPC.
	ComputeServiceDescribeInstanceProcedure = "/namespace.cloud.compute.v1beta.ComputeService/DescribeInstance"
	// ComputeServiceDestroyInstanceProcedure is the fully-qualified name of the ComputeService's
	// DestroyInstance RPC.
	ComputeServiceDestroyInstanceProcedure = "/namespace.cloud.compute.v1beta.ComputeService/DestroyInstance"
	// ComputeServiceListInstancesProcedure is the fully-qualified name of the ComputeService's
	// ListInstances RPC.
	ComputeServiceListInstancesProcedure = "/namespace.cloud.compute.v1beta.ComputeService/ListInstances"
	// ComputeServiceSuspendInstanceProcedure is the fully-qualified name of the ComputeService's
	// SuspendInstance RPC.
	ComputeServiceSuspendInstanceProcedure = "/namespace.cloud.compute.v1beta.ComputeService/SuspendInstance"
	// ComputeServiceWakeInstanceProcedure is the fully-qualified name of the ComputeService's
	// WakeInstance RPC.
	ComputeServiceWakeInstanceProcedure = "/namespace.cloud.compute.v1beta.ComputeService/WakeInstance"
	// ComputeServiceCreateIngressProcedure is the fully-qualified name of the ComputeService's
	// CreateIngress RPC.
	ComputeServiceCreateIngressProcedure = "/namespace.cloud.compute.v1beta.ComputeService/CreateIngress"
	// ComputeServiceListIngressesProcedure is the fully-qualified name of the ComputeService's
	// ListIngresses RPC.
	ComputeServiceListIngressesProcedure = "/namespace.cloud.compute.v1beta.ComputeService/ListIngresses"
	// ComputeServiceGetKubernetesConfigProcedure is the fully-qualified name of the ComputeService's
	// GetKubernetesConfig RPC.
	ComputeServiceGetKubernetesConfigProcedure = "/namespace.cloud.compute.v1beta.ComputeService/GetKubernetesConfig"
	// ComputeServiceGetInstanceMetricsProcedure is the fully-qualified name of the ComputeService's
	// GetInstanceMetrics RPC.
	ComputeServiceGetInstanceMetricsProcedure = "/namespace.cloud.compute.v1beta.ComputeService/GetInstanceMetrics"
	// ComputeServiceGetNetworkConfigurationProcedure is the fully-qualified name of the
	// ComputeService's GetNetworkConfiguration RPC.
	ComputeServiceGetNetworkConfigurationProcedure = "/namespace.cloud.compute.v1beta.ComputeService/GetNetworkConfiguration"
	// ComputeServiceGetSSHConfigProcedure is the fully-qualified name of the ComputeService's
	// GetSSHConfig RPC.
	ComputeServiceGetSSHConfigProcedure = "/namespace.cloud.compute.v1beta.ComputeService/GetSSHConfig"
	// ComputeServiceGetVNCConfigProcedure is the fully-qualified name of the ComputeService's
	// GetVNCConfig RPC.
	ComputeServiceGetVNCConfigProcedure = "/namespace.cloud.compute.v1beta.ComputeService/GetVNCConfig"
	// ComputeServiceReleaseUniqueTagProcedure is the fully-qualified name of the ComputeService's
	// ReleaseUniqueTag RPC.
	ComputeServiceReleaseUniqueTagProcedure = "/namespace.cloud.compute.v1beta.ComputeService/ReleaseUniqueTag"
	// ComputeServiceOptimizeImageProcedure is the fully-qualified name of the ComputeService's
	// OptimizeImage RPC.
	ComputeServiceOptimizeImageProcedure = "/namespace.cloud.compute.v1beta.ComputeService/OptimizeImage"
	// ComputeServiceListInstanceNotificationsProcedure is the fully-qualified name of the
	// ComputeService's ListInstanceNotifications RPC.
	ComputeServiceListInstanceNotificationsProcedure = "/namespace.cloud.compute.v1beta.ComputeService/ListInstanceNotifications"
)

// These variables are the protoreflect.Descriptor objects for the RPCs defined in this package.
var (
	computeServiceServiceDescriptor                         = v1beta.File_proto_namespace_cloud_compute_v1beta_compute_proto.Services().ByName("ComputeService")
	computeServiceCreateInstanceMethodDescriptor            = computeServiceServiceDescriptor.Methods().ByName("CreateInstance")
	computeServiceWaitInstanceMethodDescriptor              = computeServiceServiceDescriptor.Methods().ByName("WaitInstance")
	computeServiceWaitInstanceSyncMethodDescriptor          = computeServiceServiceDescriptor.Methods().ByName("WaitInstanceSync")
	computeServiceExtendInstanceMethodDescriptor            = computeServiceServiceDescriptor.Methods().ByName("ExtendInstance")
	computeServiceStartContainersMethodDescriptor           = computeServiceServiceDescriptor.Methods().ByName("StartContainers")
	computeServiceDescribeInstanceMethodDescriptor          = computeServiceServiceDescriptor.Methods().ByName("DescribeInstance")
	computeServiceDestroyInstanceMethodDescriptor           = computeServiceServiceDescriptor.Methods().ByName("DestroyInstance")
	computeServiceListInstancesMethodDescriptor             = computeServiceServiceDescriptor.Methods().ByName("ListInstances")
	computeServiceSuspendInstanceMethodDescriptor           = computeServiceServiceDescriptor.Methods().ByName("SuspendInstance")
	computeServiceWakeInstanceMethodDescriptor              = computeServiceServiceDescriptor.Methods().ByName("WakeInstance")
	computeServiceCreateIngressMethodDescriptor             = computeServiceServiceDescriptor.Methods().ByName("CreateIngress")
	computeServiceListIngressesMethodDescriptor             = computeServiceServiceDescriptor.Methods().ByName("ListIngresses")
	computeServiceGetKubernetesConfigMethodDescriptor       = computeServiceServiceDescriptor.Methods().ByName("GetKubernetesConfig")
	computeServiceGetInstanceMetricsMethodDescriptor        = computeServiceServiceDescriptor.Methods().ByName("GetInstanceMetrics")
	computeServiceGetNetworkConfigurationMethodDescriptor   = computeServiceServiceDescriptor.Methods().ByName("GetNetworkConfiguration")
	computeServiceGetSSHConfigMethodDescriptor              = computeServiceServiceDescriptor.Methods().ByName("GetSSHConfig")
	computeServiceGetVNCConfigMethodDescriptor              = computeServiceServiceDescriptor.Methods().ByName("GetVNCConfig")
	computeServiceReleaseUniqueTagMethodDescriptor          = computeServiceServiceDescriptor.Methods().ByName("ReleaseUniqueTag")
	computeServiceOptimizeImageMethodDescriptor             = computeServiceServiceDescriptor.Methods().ByName("OptimizeImage")
	computeServiceListInstanceNotificationsMethodDescriptor = computeServiceServiceDescriptor.Methods().ByName("ListInstanceNotifications")
)

// ComputeServiceClient is a client for the namespace.cloud.compute.v1beta.ComputeService service.
type ComputeServiceClient interface {
	// Creates a new instance. Instances are micro-vm backed environments which
	// are optimized to run containers. Each instance is deployed with
	// `containerd`, and with optionally `dockerd` and Kubernetes.
	//
	// Instances can run one or more containers. Containers can be started using
	// one of two mechanisms:
	//   - Namespace managed containers: containers are specified at creation time
	//     via the `containers` field, or at runtime via the `StartContainers`
	//     method. Managed containers have logs and metrics automatically
	//     collected, and Namespace's infrastructure optimizes future startup time
	//     of repeated use of the same containers. These containers are handled as
	//     "critical" and their lifetime is tied to the VMs -- if they fail,
	//     either due to early exit, OOM, etc, the instance also fails. Namespace
	//     managed containers are always run on containerd directly, in the
	//     `default` namespace.
	//
	//   - User-managed containers: after an instance is created, you can use the
	//     containerd or Docker APIs to create and manage containers yourself.
	//     These containers are not marked required, so it's up to a user to take
	//     action to terminate a VM on container failure.
	//
	// Instances that are running can be accessed via the region ingress.
	// Endpoints per exposed service are returned as part of the instance
	// creation. For example, proxies are exposed that allow direct access to
	// `containerd`, `docker`, etc services which are usually only exposed over
	// Unix sockets.
	//
	// The creation of an instance produces a set of metadata: InstanceMetadata
	// is also available in ListInstances requests, but the remainder of
	// metadata (e.g. extended metadata) is only available at creation time, or
	// if DescribeInstance is called.
	//
	// Instance creation is non-blocking. After an instance is created call
	// WaitInstance to observe the states instance creation goes through.
	//
	// ### Errors
	//   - If the workspace is out of resources, a `ResourceExhausted` status is
	//     returned.
	//   - If the request refers to an invalid argument, e.g. a non-existing
	//     region, an `InvalidArgument` status is returned.
	CreateInstance(context.Context, *connect.Request[v1beta.CreateInstanceRequest]) (*connect.Response[v1beta.DescribeInstanceResponse], error)
	// Waits until an instance reaches the RUNNING state. Intermediate updates,
	// such as state progressions, or service state changes, are sent as
	// individual metadata updates.
	//
	// When the instance reaches the RUNNING state, the server terminates the
	// stream.
	//
	// If the instance was already in the RUNNING state when WaitInstance is
	// called, a single InstanceMetadata is returned and the stream is closed
	// immediately.
	//
	// ### Errors
	//   - If the instance does not exist, a `NotFound` status is returned.
	//   - If instance creation is unsuccessful, `Internal` error is returned.
	//     Refer to the InstanceMetadata.status in the last response for detailed
	//     status.
	WaitInstance(context.Context, *connect.Request[v1beta.WaitInstanceRequest]) (*connect.ServerStreamForClient[v1beta.WaitInstanceResponse], error)
	// Waits until an instance reaches the RUNNING state and returns the
	// instance metadata.
	//
	// To receive intermediate state updates during instance creation process
	// use the streaming version of this method — `WaitInstance`.
	//
	// ### Errors
	// - If the instance does not exist, a `NotFound` status is returned.
	WaitInstanceSync(context.Context, *connect.Request[v1beta.WaitInstanceRequest]) (*connect.Response[v1beta.WaitInstanceResponse], error)
	// Extend the lifetime of an instance by the provided duration.
	//
	// ### Errors
	// - If the instance does not exist, a `NotFound` status is returned.
	ExtendInstance(context.Context, *connect.Request[v1beta.ExtendInstanceRequest]) (*connect.Response[v1beta.ExtendInstanceResponse], error)
	// Adds the specified set of containers to a running instance.
	//
	// ### Errors
	// - If the instance does not exist, a `NotFound` status is returned.
	StartContainers(context.Context, *connect.Request[v1beta.StartContainersRequest]) (*connect.Response[v1beta.StartContainersResponse], error)
	// Obtains the metadata (including extra metadata) of a previously created
	// instance.
	//
	// ### Errors
	// - If the instance does not exist, a `NotFound` status is returned.
	DescribeInstance(context.Context, *connect.Request[v1beta.DescribeInstanceRequest]) (*connect.Response[v1beta.DescribeInstanceResponse], error)
	// Destroys a previously created instance.
	//
	// ### Errors
	// - If the instance does not exist, a `NotFound` status is returned.
	DestroyInstance(context.Context, *connect.Request[v1beta.DestroyInstanceRequest]) (*connect.Response[emptypb.Empty], error)
	// Returns a list of all instances that match the specified filter.
	ListInstances(context.Context, *connect.Request[v1beta.ListInstancesRequest]) (*connect.Response[v1beta.ListInstancesResponse], error)
	// Request that the specified instance be suspended, i.e. it's execution is
	// stopped and RAM and disks snapshotted in a way that can be restored
	// without the instance being restarted.
	//
	// See WakeInstance for the counterpart.
	//
	// ### Errors
	// - If the instance does not exist, a `NotFound` status is returned.
	SuspendInstance(context.Context, *connect.Request[v1beta.SuspendInstanceRequest]) (*connect.Response[emptypb.Empty], error)
	// Wakes up a suspended instance. Is a no-op if it is already running.
	//
	// ### Errors
	// - If the instance does not exist, a `NotFound` status is returned.
	// - If the instance is not suspended, an `FailedPrecondition` status is returned.
	WakeInstance(context.Context, *connect.Request[v1beta.WakeInstanceRequest]) (*connect.Response[emptypb.Empty], error)
	// Exposes a backend within the instance to the public internet. Typically
	// used to serve public HTTPS-termination ingress that is backed by a
	// container running inside the instance.
	// See https://namespace.so/docs/architecture/networking/ingress for details.
	//
	// ### Errors
	// - If the instance does not exist, a `NotFound` status is returned.
	CreateIngress(context.Context, *connect.Request[v1beta.CreateIngressRequest]) (*connect.Response[v1beta.CreateIngressResponse], error)
	// Returns the list of backends exposed from the instance to the public
	// internet. This includes ingresses created using `CreateIngress` above
	// or ingresses declaratively exposed using FEATURE_KUBERNETES_INGRESS_MANAGER
	// feature.
	//
	// ### Errors
	//   - If the instance does not exist, a `NotFound` status is returned.
	//   - If the instance is already terminated, a `FailedPrecondition`
	//     status is returned.
	ListIngresses(context.Context, *connect.Request[v1beta.ListIngressesRequest]) (*connect.Response[v1beta.ListIngressesResponse], error)
	// Returns a configuration that can be used by `kubectl` to access
	// Kubernetes inside the specified instance.
	//
	// ### Errors
	//   - If the instance does not exist, a `NotFound` status is returned.
	//   - If the instance is not running Kubernetes, an `FailedPrecondition`
	//     status is returned.
	GetKubernetesConfig(context.Context, *connect.Request[v1beta.GetKubernetesConfigRequest]) (*connect.Response[v1beta.GetKubernetesConfigResponse], error)
	// Returns metrics that represent resource usage by the specified instance.
	// Metrics can also be queried from instances that are still running.
	// See https://namespace.so/docs/architecture/compute/observability for details.
	//
	// ### Errors
	// - If the instance does not exist, a `NotFound` status is returned.
	GetInstanceMetrics(context.Context, *connect.Request[v1beta.GetInstanceMetricsRequest]) (*connect.Response[v1beta.GetInstanceMetricsResponse], error)
	// Returns the network configuration used within the target workspace.
	// See https://namespace.so/docs/architecture/networking for details.
	GetNetworkConfiguration(context.Context, *connect.Request[v1beta.GetNetworkConfigurationRequest]) (*connect.Response[v1beta.GetNetworkConfigurationResponse], error)
	// Returns a configuration that can be used to access the instance with SSH.
	// See https://namespace.so/docs/architecture/compute/ssh-remote-display for details.
	//
	// ### Errors
	// - If the instance does not exist, a `NotFound` status is returned.
	GetSSHConfig(context.Context, *connect.Request[v1beta.GetSSHConfigRequest]) (*connect.Response[v1beta.GetSSHConfigResponse], error)
	// Returns a configuration that can be used to access the instance's remote display using VNC.
	// The caller's authentication token must also grant access to the instance ingress when connecting to the returned endpoint.
	//
	// ### Errors
	// - If the instance does not exist, a `NotFound` status is returned.
	// - If the instance does not expose a VNC service, a `FailedPrecondition` status is returned.
	GetVNCConfig(context.Context, *connect.Request[v1beta.GetVNCConfigRequest]) (*connect.Response[v1beta.GetVNCConfigResponse], error)
	// Release the currently associated instance ID from a unique tag.
	//
	// Tags are only unique per region. Make sure to select the correct ComputeService endpoint.
	// When calling this service from within an instance, `NSC_ENDPOINT` will point to the ComputeService endpoint for the current region.
	// Our [SDK](https://github.com/namespacelabs/integrations?tab=readme-ov-file#namespace-integrations) handles this automatically.
	//
	// ### Errors
	// - If the unique tag does not exist, a `NotFound` status is returned.
	ReleaseUniqueTag(context.Context, *connect.Request[v1beta.ReleaseUniqueTagRequest]) (*connect.Response[v1beta.ReleaseUniqueTagResponse], error)
	// Triggers an internal process to optimize an image. This is not always
	// needed and is used for internal purposes.
	OptimizeImage(context.Context, *connect.Request[v1beta.OptimizeImageRequest]) (*connect.ServerStreamForClient[v1beta.OptimizeImageProgress], error)
	// Returns a list of instance notification events. Each instance has at most one event
	// in the response, representing its most recent state change. Events can
	// be filtered by instance ID.
	ListInstanceNotifications(context.Context, *connect.Request[v1beta.ListInstanceNotificationsRequest]) (*connect.Response[v1beta.ListInstanceNotificationsResponse], error)
}

// NewComputeServiceClient constructs a client for the namespace.cloud.compute.v1beta.ComputeService
// service. By default, it uses the Connect protocol with the binary Protobuf Codec, asks for
// gzipped responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply
// the connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewComputeServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) ComputeServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	return &computeServiceClient{
		createInstance: connect.NewClient[v1beta.CreateInstanceRequest, v1beta.DescribeInstanceResponse](
			httpClient,
			baseURL+ComputeServiceCreateInstanceProcedure,
			connect.WithSchema(computeServiceCreateInstanceMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		waitInstance: connect.NewClient[v1beta.WaitInstanceRequest, v1beta.WaitInstanceResponse](
			httpClient,
			baseURL+ComputeServiceWaitInstanceProcedure,
			connect.WithSchema(computeServiceWaitInstanceMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		waitInstanceSync: connect.NewClient[v1beta.WaitInstanceRequest, v1beta.WaitInstanceResponse](
			httpClient,
			baseURL+ComputeServiceWaitInstanceSyncProcedure,
			connect.WithSchema(computeServiceWaitInstanceSyncMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		extendInstance: connect.NewClient[v1beta.ExtendInstanceRequest, v1beta.ExtendInstanceResponse](
			httpClient,
			baseURL+ComputeServiceExtendInstanceProcedure,
			connect.WithSchema(computeServiceExtendInstanceMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		startContainers: connect.NewClient[v1beta.StartContainersRequest, v1beta.StartContainersResponse](
			httpClient,
			baseURL+ComputeServiceStartContainersProcedure,
			connect.WithSchema(computeServiceStartContainersMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		describeInstance: connect.NewClient[v1beta.DescribeInstanceRequest, v1beta.DescribeInstanceResponse](
			httpClient,
			baseURL+ComputeServiceDescribeInstanceProcedure,
			connect.WithSchema(computeServiceDescribeInstanceMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		destroyInstance: connect.NewClient[v1beta.DestroyInstanceRequest, emptypb.Empty](
			httpClient,
			baseURL+ComputeServiceDestroyInstanceProcedure,
			connect.WithSchema(computeServiceDestroyInstanceMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		listInstances: connect.NewClient[v1beta.ListInstancesRequest, v1beta.ListInstancesResponse](
			httpClient,
			baseURL+ComputeServiceListInstancesProcedure,
			connect.WithSchema(computeServiceListInstancesMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		suspendInstance: connect.NewClient[v1beta.SuspendInstanceRequest, emptypb.Empty](
			httpClient,
			baseURL+ComputeServiceSuspendInstanceProcedure,
			connect.WithSchema(computeServiceSuspendInstanceMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		wakeInstance: connect.NewClient[v1beta.WakeInstanceRequest, emptypb.Empty](
			httpClient,
			baseURL+ComputeServiceWakeInstanceProcedure,
			connect.WithSchema(computeServiceWakeInstanceMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		createIngress: connect.NewClient[v1beta.CreateIngressRequest, v1beta.CreateIngressResponse](
			httpClient,
			baseURL+ComputeServiceCreateIngressProcedure,
			connect.WithSchema(computeServiceCreateIngressMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		listIngresses: connect.NewClient[v1beta.ListIngressesRequest, v1beta.ListIngressesResponse](
			httpClient,
			baseURL+ComputeServiceListIngressesProcedure,
			connect.WithSchema(computeServiceListIngressesMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		getKubernetesConfig: connect.NewClient[v1beta.GetKubernetesConfigRequest, v1beta.GetKubernetesConfigResponse](
			httpClient,
			baseURL+ComputeServiceGetKubernetesConfigProcedure,
			connect.WithSchema(computeServiceGetKubernetesConfigMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		getInstanceMetrics: connect.NewClient[v1beta.GetInstanceMetricsRequest, v1beta.GetInstanceMetricsResponse](
			httpClient,
			baseURL+ComputeServiceGetInstanceMetricsProcedure,
			connect.WithSchema(computeServiceGetInstanceMetricsMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		getNetworkConfiguration: connect.NewClient[v1beta.GetNetworkConfigurationRequest, v1beta.GetNetworkConfigurationResponse](
			httpClient,
			baseURL+ComputeServiceGetNetworkConfigurationProcedure,
			connect.WithSchema(computeServiceGetNetworkConfigurationMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		getSSHConfig: connect.NewClient[v1beta.GetSSHConfigRequest, v1beta.GetSSHConfigResponse](
			httpClient,
			baseURL+ComputeServiceGetSSHConfigProcedure,
			connect.WithSchema(computeServiceGetSSHConfigMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		getVNCConfig: connect.NewClient[v1beta.GetVNCConfigRequest, v1beta.GetVNCConfigResponse](
			httpClient,
			baseURL+ComputeServiceGetVNCConfigProcedure,
			connect.WithSchema(computeServiceGetVNCConfigMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		releaseUniqueTag: connect.NewClient[v1beta.ReleaseUniqueTagRequest, v1beta.ReleaseUniqueTagResponse](
			httpClient,
			baseURL+ComputeServiceReleaseUniqueTagProcedure,
			connect.WithSchema(computeServiceReleaseUniqueTagMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		optimizeImage: connect.NewClient[v1beta.OptimizeImageRequest, v1beta.OptimizeImageProgress](
			httpClient,
			baseURL+ComputeServiceOptimizeImageProcedure,
			connect.WithSchema(computeServiceOptimizeImageMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		listInstanceNotifications: connect.NewClient[v1beta.ListInstanceNotificationsRequest, v1beta.ListInstanceNotificationsResponse](
			httpClient,
			baseURL+ComputeServiceListInstanceNotificationsProcedure,
			connect.WithSchema(computeServiceListInstanceNotificationsMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
	}
}

// computeServiceClient implements ComputeServiceClient.
type computeServiceClient struct {
	createInstance            *connect.Client[v1beta.CreateInstanceRequest, v1beta.DescribeInstanceResponse]
	waitInstance              *connect.Client[v1beta.WaitInstanceRequest, v1beta.WaitInstanceResponse]
	waitInstanceSync          *connect.Client[v1beta.WaitInstanceRequest, v1beta.WaitInstanceResponse]
	extendInstance            *connect.Client[v1beta.ExtendInstanceRequest, v1beta.ExtendInstanceResponse]
	startContainers           *connect.Client[v1beta.StartContainersRequest, v1beta.StartContainersResponse]
	describeInstance          *connect.Client[v1beta.DescribeInstanceRequest, v1beta.DescribeInstanceResponse]
	destroyInstance           *connect.Client[v1beta.DestroyInstanceRequest, emptypb.Empty]
	listInstances             *connect.Client[v1beta.ListInstancesRequest, v1beta.ListInstancesResponse]
	suspendInstance           *connect.Client[v1beta.SuspendInstanceRequest, emptypb.Empty]
	wakeInstance              *connect.Client[v1beta.WakeInstanceRequest, emptypb.Empty]
	createIngress             *connect.Client[v1beta.CreateIngressRequest, v1beta.CreateIngressResponse]
	listIngresses             *connect.Client[v1beta.ListIngressesRequest, v1beta.ListIngressesResponse]
	getKubernetesConfig       *connect.Client[v1beta.GetKubernetesConfigRequest, v1beta.GetKubernetesConfigResponse]
	getInstanceMetrics        *connect.Client[v1beta.GetInstanceMetricsRequest, v1beta.GetInstanceMetricsResponse]
	getNetworkConfiguration   *connect.Client[v1beta.GetNetworkConfigurationRequest, v1beta.GetNetworkConfigurationResponse]
	getSSHConfig              *connect.Client[v1beta.GetSSHConfigRequest, v1beta.GetSSHConfigResponse]
	getVNCConfig              *connect.Client[v1beta.GetVNCConfigRequest, v1beta.GetVNCConfigResponse]
	releaseUniqueTag          *connect.Client[v1beta.ReleaseUniqueTagRequest, v1beta.ReleaseUniqueTagResponse]
	optimizeImage             *connect.Client[v1beta.OptimizeImageRequest, v1beta.OptimizeImageProgress]
	listInstanceNotifications *connect.Client[v1beta.ListInstanceNotificationsRequest, v1beta.ListInstanceNotificationsResponse]
}

// CreateInstance calls namespace.cloud.compute.v1beta.ComputeService.CreateInstance.
func (c *computeServiceClient) CreateInstance(ctx context.Context, req *connect.Request[v1beta.CreateInstanceRequest]) (*connect.Response[v1beta.DescribeInstanceResponse], error) {
	return c.createInstance.CallUnary(ctx, req)
}

// WaitInstance calls namespace.cloud.compute.v1beta.ComputeService.WaitInstance.
func (c *computeServiceClient) WaitInstance(ctx context.Context, req *connect.Request[v1beta.WaitInstanceRequest]) (*connect.ServerStreamForClient[v1beta.WaitInstanceResponse], error) {
	return c.waitInstance.CallServerStream(ctx, req)
}

// WaitInstanceSync calls namespace.cloud.compute.v1beta.ComputeService.WaitInstanceSync.
func (c *computeServiceClient) WaitInstanceSync(ctx context.Context, req *connect.Request[v1beta.WaitInstanceRequest]) (*connect.Response[v1beta.WaitInstanceResponse], error) {
	return c.waitInstanceSync.CallUnary(ctx, req)
}

// ExtendInstance calls namespace.cloud.compute.v1beta.ComputeService.ExtendInstance.
func (c *computeServiceClient) ExtendInstance(ctx context.Context, req *connect.Request[v1beta.ExtendInstanceRequest]) (*connect.Response[v1beta.ExtendInstanceResponse], error) {
	return c.extendInstance.CallUnary(ctx, req)
}

// StartContainers calls namespace.cloud.compute.v1beta.ComputeService.StartContainers.
func (c *computeServiceClient) StartContainers(ctx context.Context, req *connect.Request[v1beta.StartContainersRequest]) (*connect.Response[v1beta.StartContainersResponse], error) {
	return c.startContainers.CallUnary(ctx, req)
}

// DescribeInstance calls namespace.cloud.compute.v1beta.ComputeService.DescribeInstance.
func (c *computeServiceClient) DescribeInstance(ctx context.Context, req *connect.Request[v1beta.DescribeInstanceRequest]) (*connect.Response[v1beta.DescribeInstanceResponse], error) {
	return c.describeInstance.CallUnary(ctx, req)
}

// DestroyInstance calls namespace.cloud.compute.v1beta.ComputeService.DestroyInstance.
func (c *computeServiceClient) DestroyInstance(ctx context.Context, req *connect.Request[v1beta.DestroyInstanceRequest]) (*connect.Response[emptypb.Empty], error) {
	return c.destroyInstance.CallUnary(ctx, req)
}

// ListInstances calls namespace.cloud.compute.v1beta.ComputeService.ListInstances.
func (c *computeServiceClient) ListInstances(ctx context.Context, req *connect.Request[v1beta.ListInstancesRequest]) (*connect.Response[v1beta.ListInstancesResponse], error) {
	return c.listInstances.CallUnary(ctx, req)
}

// SuspendInstance calls namespace.cloud.compute.v1beta.ComputeService.SuspendInstance.
func (c *computeServiceClient) SuspendInstance(ctx context.Context, req *connect.Request[v1beta.SuspendInstanceRequest]) (*connect.Response[emptypb.Empty], error) {
	return c.suspendInstance.CallUnary(ctx, req)
}

// WakeInstance calls namespace.cloud.compute.v1beta.ComputeService.WakeInstance.
func (c *computeServiceClient) WakeInstance(ctx context.Context, req *connect.Request[v1beta.WakeInstanceRequest]) (*connect.Response[emptypb.Empty], error) {
	return c.wakeInstance.CallUnary(ctx, req)
}

// CreateIngress calls namespace.cloud.compute.v1beta.ComputeService.CreateIngress.
func (c *computeServiceClient) CreateIngress(ctx context.Context, req *connect.Request[v1beta.CreateIngressRequest]) (*connect.Response[v1beta.CreateIngressResponse], error) {
	return c.createIngress.CallUnary(ctx, req)
}

// ListIngresses calls namespace.cloud.compute.v1beta.ComputeService.ListIngresses.
func (c *computeServiceClient) ListIngresses(ctx context.Context, req *connect.Request[v1beta.ListIngressesRequest]) (*connect.Response[v1beta.ListIngressesResponse], error) {
	return c.listIngresses.CallUnary(ctx, req)
}

// GetKubernetesConfig calls namespace.cloud.compute.v1beta.ComputeService.GetKubernetesConfig.
func (c *computeServiceClient) GetKubernetesConfig(ctx context.Context, req *connect.Request[v1beta.GetKubernetesConfigRequest]) (*connect.Response[v1beta.GetKubernetesConfigResponse], error) {
	return c.getKubernetesConfig.CallUnary(ctx, req)
}

// GetInstanceMetrics calls namespace.cloud.compute.v1beta.ComputeService.GetInstanceMetrics.
func (c *computeServiceClient) GetInstanceMetrics(ctx context.Context, req *connect.Request[v1beta.GetInstanceMetricsRequest]) (*connect.Response[v1beta.GetInstanceMetricsResponse], error) {
	return c.getInstanceMetrics.CallUnary(ctx, req)
}

// GetNetworkConfiguration calls
// namespace.cloud.compute.v1beta.ComputeService.GetNetworkConfiguration.
func (c *computeServiceClient) GetNetworkConfiguration(ctx context.Context, req *connect.Request[v1beta.GetNetworkConfigurationRequest]) (*connect.Response[v1beta.GetNetworkConfigurationResponse], error) {
	return c.getNetworkConfiguration.CallUnary(ctx, req)
}

// GetSSHConfig calls namespace.cloud.compute.v1beta.ComputeService.GetSSHConfig.
func (c *computeServiceClient) GetSSHConfig(ctx context.Context, req *connect.Request[v1beta.GetSSHConfigRequest]) (*connect.Response[v1beta.GetSSHConfigResponse], error) {
	return c.getSSHConfig.CallUnary(ctx, req)
}

// GetVNCConfig calls namespace.cloud.compute.v1beta.ComputeService.GetVNCConfig.
func (c *computeServiceClient) GetVNCConfig(ctx context.Context, req *connect.Request[v1beta.GetVNCConfigRequest]) (*connect.Response[v1beta.GetVNCConfigResponse], error) {
	return c.getVNCConfig.CallUnary(ctx, req)
}

// ReleaseUniqueTag calls namespace.cloud.compute.v1beta.ComputeService.ReleaseUniqueTag.
func (c *computeServiceClient) ReleaseUniqueTag(ctx context.Context, req *connect.Request[v1beta.ReleaseUniqueTagRequest]) (*connect.Response[v1beta.ReleaseUniqueTagResponse], error) {
	return c.releaseUniqueTag.CallUnary(ctx, req)
}

// OptimizeImage calls namespace.cloud.compute.v1beta.ComputeService.OptimizeImage.
func (c *computeServiceClient) OptimizeImage(ctx context.Context, req *connect.Request[v1beta.OptimizeImageRequest]) (*connect.ServerStreamForClient[v1beta.OptimizeImageProgress], error) {
	return c.optimizeImage.CallServerStream(ctx, req)
}

// ListInstanceNotifications calls
// namespace.cloud.compute.v1beta.ComputeService.ListInstanceNotifications.
func (c *computeServiceClient) ListInstanceNotifications(ctx context.Context, req *connect.Request[v1beta.ListInstanceNotificationsRequest]) (*connect.Response[v1beta.ListInstanceNotificationsResponse], error) {
	return c.listInstanceNotifications.CallUnary(ctx, req)
}

// ComputeServiceHandler is an implementation of the namespace.cloud.compute.v1beta.ComputeService
// service.
type ComputeServiceHandler interface {
	// Creates a new instance. Instances are micro-vm backed environments which
	// are optimized to run containers. Each instance is deployed with
	// `containerd`, and with optionally `dockerd` and Kubernetes.
	//
	// Instances can run one or more containers. Containers can be started using
	// one of two mechanisms:
	//   - Namespace managed containers: containers are specified at creation time
	//     via the `containers` field, or at runtime via the `StartContainers`
	//     method. Managed containers have logs and metrics automatically
	//     collected, and Namespace's infrastructure optimizes future startup time
	//     of repeated use of the same containers. These containers are handled as
	//     "critical" and their lifetime is tied to the VMs -- if they fail,
	//     either due to early exit, OOM, etc, the instance also fails. Namespace
	//     managed containers are always run on containerd directly, in the
	//     `default` namespace.
	//
	//   - User-managed containers: after an instance is created, you can use the
	//     containerd or Docker APIs to create and manage containers yourself.
	//     These containers are not marked required, so it's up to a user to take
	//     action to terminate a VM on container failure.
	//
	// Instances that are running can be accessed via the region ingress.
	// Endpoints per exposed service are returned as part of the instance
	// creation. For example, proxies are exposed that allow direct access to
	// `containerd`, `docker`, etc services which are usually only exposed over
	// Unix sockets.
	//
	// The creation of an instance produces a set of metadata: InstanceMetadata
	// is also available in ListInstances requests, but the remainder of
	// metadata (e.g. extended metadata) is only available at creation time, or
	// if DescribeInstance is called.
	//
	// Instance creation is non-blocking. After an instance is created call
	// WaitInstance to observe the states instance creation goes through.
	//
	// ### Errors
	//   - If the workspace is out of resources, a `ResourceExhausted` status is
	//     returned.
	//   - If the request refers to an invalid argument, e.g. a non-existing
	//     region, an `InvalidArgument` status is returned.
	CreateInstance(context.Context, *connect.Request[v1beta.CreateInstanceRequest]) (*connect.Response[v1beta.DescribeInstanceResponse], error)
	// Waits until an instance reaches the RUNNING state. Intermediate updates,
	// such as state progressions, or service state changes, are sent as
	// individual metadata updates.
	//
	// When the instance reaches the RUNNING state, the server terminates the
	// stream.
	//
	// If the instance was already in the RUNNING state when WaitInstance is
	// called, a single InstanceMetadata is returned and the stream is closed
	// immediately.
	//
	// ### Errors
	//   - If the instance does not exist, a `NotFound` status is returned.
	//   - If instance creation is unsuccessful, `Internal` error is returned.
	//     Refer to the InstanceMetadata.status in the last response for detailed
	//     status.
	WaitInstance(context.Context, *connect.Request[v1beta.WaitInstanceRequest], *connect.ServerStream[v1beta.WaitInstanceResponse]) error
	// Waits until an instance reaches the RUNNING state and returns the
	// instance metadata.
	//
	// To receive intermediate state updates during instance creation process
	// use the streaming version of this method — `WaitInstance`.
	//
	// ### Errors
	// - If the instance does not exist, a `NotFound` status is returned.
	WaitInstanceSync(context.Context, *connect.Request[v1beta.WaitInstanceRequest]) (*connect.Response[v1beta.WaitInstanceResponse], error)
	// Extend the lifetime of an instance by the provided duration.
	//
	// ### Errors
	// - If the instance does not exist, a `NotFound` status is returned.
	ExtendInstance(context.Context, *connect.Request[v1beta.ExtendInstanceRequest]) (*connect.Response[v1beta.ExtendInstanceResponse], error)
	// Adds the specified set of containers to a running instance.
	//
	// ### Errors
	// - If the instance does not exist, a `NotFound` status is returned.
	StartContainers(context.Context, *connect.Request[v1beta.StartContainersRequest]) (*connect.Response[v1beta.StartContainersResponse], error)
	// Obtains the metadata (including extra metadata) of a previously created
	// instance.
	//
	// ### Errors
	// - If the instance does not exist, a `NotFound` status is returned.
	DescribeInstance(context.Context, *connect.Request[v1beta.DescribeInstanceRequest]) (*connect.Response[v1beta.DescribeInstanceResponse], error)
	// Destroys a previously created instance.
	//
	// ### Errors
	// - If the instance does not exist, a `NotFound` status is returned.
	DestroyInstance(context.Context, *connect.Request[v1beta.DestroyInstanceRequest]) (*connect.Response[emptypb.Empty], error)
	// Returns a list of all instances that match the specified filter.
	ListInstances(context.Context, *connect.Request[v1beta.ListInstancesRequest]) (*connect.Response[v1beta.ListInstancesResponse], error)
	// Request that the specified instance be suspended, i.e. it's execution is
	// stopped and RAM and disks snapshotted in a way that can be restored
	// without the instance being restarted.
	//
	// See WakeInstance for the counterpart.
	//
	// ### Errors
	// - If the instance does not exist, a `NotFound` status is returned.
	SuspendInstance(context.Context, *connect.Request[v1beta.SuspendInstanceRequest]) (*connect.Response[emptypb.Empty], error)
	// Wakes up a suspended instance. Is a no-op if it is already running.
	//
	// ### Errors
	// - If the instance does not exist, a `NotFound` status is returned.
	// - If the instance is not suspended, an `FailedPrecondition` status is returned.
	WakeInstance(context.Context, *connect.Request[v1beta.WakeInstanceRequest]) (*connect.Response[emptypb.Empty], error)
	// Exposes a backend within the instance to the public internet. Typically
	// used to serve public HTTPS-termination ingress that is backed by a
	// container running inside the instance.
	// See https://namespace.so/docs/architecture/networking/ingress for details.
	//
	// ### Errors
	// - If the instance does not exist, a `NotFound` status is returned.
	CreateIngress(context.Context, *connect.Request[v1beta.CreateIngressRequest]) (*connect.Response[v1beta.CreateIngressResponse], error)
	// Returns the list of backends exposed from the instance to the public
	// internet. This includes ingresses created using `CreateIngress` above
	// or ingresses declaratively exposed using FEATURE_KUBERNETES_INGRESS_MANAGER
	// feature.
	//
	// ### Errors
	//   - If the instance does not exist, a `NotFound` status is returned.
	//   - If the instance is already terminated, a `FailedPrecondition`
	//     status is returned.
	ListIngresses(context.Context, *connect.Request[v1beta.ListIngressesRequest]) (*connect.Response[v1beta.ListIngressesResponse], error)
	// Returns a configuration that can be used by `kubectl` to access
	// Kubernetes inside the specified instance.
	//
	// ### Errors
	//   - If the instance does not exist, a `NotFound` status is returned.
	//   - If the instance is not running Kubernetes, an `FailedPrecondition`
	//     status is returned.
	GetKubernetesConfig(context.Context, *connect.Request[v1beta.GetKubernetesConfigRequest]) (*connect.Response[v1beta.GetKubernetesConfigResponse], error)
	// Returns metrics that represent resource usage by the specified instance.
	// Metrics can also be queried from instances that are still running.
	// See https://namespace.so/docs/architecture/compute/observability for details.
	//
	// ### Errors
	// - If the instance does not exist, a `NotFound` status is returned.
	GetInstanceMetrics(context.Context, *connect.Request[v1beta.GetInstanceMetricsRequest]) (*connect.Response[v1beta.GetInstanceMetricsResponse], error)
	// Returns the network configuration used within the target workspace.
	// See https://namespace.so/docs/architecture/networking for details.
	GetNetworkConfiguration(context.Context, *connect.Request[v1beta.GetNetworkConfigurationRequest]) (*connect.Response[v1beta.GetNetworkConfigurationResponse], error)
	// Returns a configuration that can be used to access the instance with SSH.
	// See https://namespace.so/docs/architecture/compute/ssh-remote-display for details.
	//
	// ### Errors
	// - If the instance does not exist, a `NotFound` status is returned.
	GetSSHConfig(context.Context, *connect.Request[v1beta.GetSSHConfigRequest]) (*connect.Response[v1beta.GetSSHConfigResponse], error)
	// Returns a configuration that can be used to access the instance's remote display using VNC.
	// The caller's authentication token must also grant access to the instance ingress when connecting to the returned endpoint.
	//
	// ### Errors
	// - If the instance does not exist, a `NotFound` status is returned.
	// - If the instance does not expose a VNC service, a `FailedPrecondition` status is returned.
	GetVNCConfig(context.Context, *connect.Request[v1beta.GetVNCConfigRequest]) (*connect.Response[v1beta.GetVNCConfigResponse], error)
	// Release the currently associated instance ID from a unique tag.
	//
	// Tags are only unique per region. Make sure to select the correct ComputeService endpoint.
	// When calling this service from within an instance, `NSC_ENDPOINT` will point to the ComputeService endpoint for the current region.
	// Our [SDK](https://github.com/namespacelabs/integrations?tab=readme-ov-file#namespace-integrations) handles this automatically.
	//
	// ### Errors
	// - If the unique tag does not exist, a `NotFound` status is returned.
	ReleaseUniqueTag(context.Context, *connect.Request[v1beta.ReleaseUniqueTagRequest]) (*connect.Response[v1beta.ReleaseUniqueTagResponse], error)
	// Triggers an internal process to optimize an image. This is not always
	// needed and is used for internal purposes.
	OptimizeImage(context.Context, *connect.Request[v1beta.OptimizeImageRequest], *connect.ServerStream[v1beta.OptimizeImageProgress]) error
	// Returns a list of instance notification events. Each instance has at most one event
	// in the response, representing its most recent state change. Events can
	// be filtered by instance ID.
	ListInstanceNotifications(context.Context, *connect.Request[v1beta.ListInstanceNotificationsRequest]) (*connect.Response[v1beta.ListInstanceNotificationsResponse], error)
}

// NewComputeServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewComputeServiceHandler(svc ComputeServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	computeServiceCreateInstanceHandler := connect.NewUnaryHandler(
		ComputeServiceCreateInstanceProcedure,
		svc.CreateInstance,
		connect.WithSchema(computeServiceCreateInstanceMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	computeServiceWaitInstanceHandler := connect.NewServerStreamHandler(
		ComputeServiceWaitInstanceProcedure,
		svc.WaitInstance,
		connect.WithSchema(computeServiceWaitInstanceMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	computeServiceWaitInstanceSyncHandler := connect.NewUnaryHandler(
		ComputeServiceWaitInstanceSyncProcedure,
		svc.WaitInstanceSync,
		connect.WithSchema(computeServiceWaitInstanceSyncMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	computeServiceExtendInstanceHandler := connect.NewUnaryHandler(
		ComputeServiceExtendInstanceProcedure,
		svc.ExtendInstance,
		connect.WithSchema(computeServiceExtendInstanceMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	computeServiceStartContainersHandler := connect.NewUnaryHandler(
		ComputeServiceStartContainersProcedure,
		svc.StartContainers,
		connect.WithSchema(computeServiceStartContainersMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	computeServiceDescribeInstanceHandler := connect.NewUnaryHandler(
		ComputeServiceDescribeInstanceProcedure,
		svc.DescribeInstance,
		connect.WithSchema(computeServiceDescribeInstanceMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	computeServiceDestroyInstanceHandler := connect.NewUnaryHandler(
		ComputeServiceDestroyInstanceProcedure,
		svc.DestroyInstance,
		connect.WithSchema(computeServiceDestroyInstanceMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	computeServiceListInstancesHandler := connect.NewUnaryHandler(
		ComputeServiceListInstancesProcedure,
		svc.ListInstances,
		connect.WithSchema(computeServiceListInstancesMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	computeServiceSuspendInstanceHandler := connect.NewUnaryHandler(
		ComputeServiceSuspendInstanceProcedure,
		svc.SuspendInstance,
		connect.WithSchema(computeServiceSuspendInstanceMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	computeServiceWakeInstanceHandler := connect.NewUnaryHandler(
		ComputeServiceWakeInstanceProcedure,
		svc.WakeInstance,
		connect.WithSchema(computeServiceWakeInstanceMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	computeServiceCreateIngressHandler := connect.NewUnaryHandler(
		ComputeServiceCreateIngressProcedure,
		svc.CreateIngress,
		connect.WithSchema(computeServiceCreateIngressMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	computeServiceListIngressesHandler := connect.NewUnaryHandler(
		ComputeServiceListIngressesProcedure,
		svc.ListIngresses,
		connect.WithSchema(computeServiceListIngressesMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	computeServiceGetKubernetesConfigHandler := connect.NewUnaryHandler(
		ComputeServiceGetKubernetesConfigProcedure,
		svc.GetKubernetesConfig,
		connect.WithSchema(computeServiceGetKubernetesConfigMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	computeServiceGetInstanceMetricsHandler := connect.NewUnaryHandler(
		ComputeServiceGetInstanceMetricsProcedure,
		svc.GetInstanceMetrics,
		connect.WithSchema(computeServiceGetInstanceMetricsMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	computeServiceGetNetworkConfigurationHandler := connect.NewUnaryHandler(
		ComputeServiceGetNetworkConfigurationProcedure,
		svc.GetNetworkConfiguration,
		connect.WithSchema(computeServiceGetNetworkConfigurationMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	computeServiceGetSSHConfigHandler := connect.NewUnaryHandler(
		ComputeServiceGetSSHConfigProcedure,
		svc.GetSSHConfig,
		connect.WithSchema(computeServiceGetSSHConfigMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	computeServiceGetVNCConfigHandler := connect.NewUnaryHandler(
		ComputeServiceGetVNCConfigProcedure,
		svc.GetVNCConfig,
		connect.WithSchema(computeServiceGetVNCConfigMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	computeServiceReleaseUniqueTagHandler := connect.NewUnaryHandler(
		ComputeServiceReleaseUniqueTagProcedure,
		svc.ReleaseUniqueTag,
		connect.WithSchema(computeServiceReleaseUniqueTagMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	computeServiceOptimizeImageHandler := connect.NewServerStreamHandler(
		ComputeServiceOptimizeImageProcedure,
		svc.OptimizeImage,
		connect.WithSchema(computeServiceOptimizeImageMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	computeServiceListInstanceNotificationsHandler := connect.NewUnaryHandler(
		ComputeServiceListInstanceNotificationsProcedure,
		svc.ListInstanceNotifications,
		connect.WithSchema(computeServiceListInstanceNotificationsMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	return "/namespace.cloud.compute.v1beta.ComputeService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case ComputeServiceCreateInstanceProcedure:
			computeServiceCreateInstanceHandler.ServeHTTP(w, r)
		case ComputeServiceWaitInstanceProcedure:
			computeServiceWaitInstanceHandler.ServeHTTP(w, r)
		case ComputeServiceWaitInstanceSyncProcedure:
			computeServiceWaitInstanceSyncHandler.ServeHTTP(w, r)
		case ComputeServiceExtendInstanceProcedure:
			computeServiceExtendInstanceHandler.ServeHTTP(w, r)
		case ComputeServiceStartContainersProcedure:
			computeServiceStartContainersHandler.ServeHTTP(w, r)
		case ComputeServiceDescribeInstanceProcedure:
			computeServiceDescribeInstanceHandler.ServeHTTP(w, r)
		case ComputeServiceDestroyInstanceProcedure:
			computeServiceDestroyInstanceHandler.ServeHTTP(w, r)
		case ComputeServiceListInstancesProcedure:
			computeServiceListInstancesHandler.ServeHTTP(w, r)
		case ComputeServiceSuspendInstanceProcedure:
			computeServiceSuspendInstanceHandler.ServeHTTP(w, r)
		case ComputeServiceWakeInstanceProcedure:
			computeServiceWakeInstanceHandler.ServeHTTP(w, r)
		case ComputeServiceCreateIngressProcedure:
			computeServiceCreateIngressHandler.ServeHTTP(w, r)
		case ComputeServiceListIngressesProcedure:
			computeServiceListIngressesHandler.ServeHTTP(w, r)
		case ComputeServiceGetKubernetesConfigProcedure:
			computeServiceGetKubernetesConfigHandler.ServeHTTP(w, r)
		case ComputeServiceGetInstanceMetricsProcedure:
			computeServiceGetInstanceMetricsHandler.ServeHTTP(w, r)
		case ComputeServiceGetNetworkConfigurationProcedure:
			computeServiceGetNetworkConfigurationHandler.ServeHTTP(w, r)
		case ComputeServiceGetSSHConfigProcedure:
			computeServiceGetSSHConfigHandler.ServeHTTP(w, r)
		case ComputeServiceGetVNCConfigProcedure:
			computeServiceGetVNCConfigHandler.ServeHTTP(w, r)
		case ComputeServiceReleaseUniqueTagProcedure:
			computeServiceReleaseUniqueTagHandler.ServeHTTP(w, r)
		case ComputeServiceOptimizeImageProcedure:
			computeServiceOptimizeImageHandler.ServeHTTP(w, r)
		case ComputeServiceListInstanceNotificationsProcedure:
			computeServiceListInstanceNotificationsHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedComputeServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedComputeServiceHandler struct{}

func (UnimplementedComputeServiceHandler) CreateInstance(context.Context, *connect.Request[v1beta.CreateInstanceRequest]) (*connect.Response[v1beta.DescribeInstanceResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("namespace.cloud.compute.v1beta.ComputeService.CreateInstance is not implemented"))
}

func (UnimplementedComputeServiceHandler) WaitInstance(context.Context, *connect.Request[v1beta.WaitInstanceRequest], *connect.ServerStream[v1beta.WaitInstanceResponse]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("namespace.cloud.compute.v1beta.ComputeService.WaitInstance is not implemented"))
}

func (UnimplementedComputeServiceHandler) WaitInstanceSync(context.Context, *connect.Request[v1beta.WaitInstanceRequest]) (*connect.Response[v1beta.WaitInstanceResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("namespace.cloud.compute.v1beta.ComputeService.WaitInstanceSync is not implemented"))
}

func (UnimplementedComputeServiceHandler) ExtendInstance(context.Context, *connect.Request[v1beta.ExtendInstanceRequest]) (*connect.Response[v1beta.ExtendInstanceResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("namespace.cloud.compute.v1beta.ComputeService.ExtendInstance is not implemented"))
}

func (UnimplementedComputeServiceHandler) StartContainers(context.Context, *connect.Request[v1beta.StartContainersRequest]) (*connect.Response[v1beta.StartContainersResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("namespace.cloud.compute.v1beta.ComputeService.StartContainers is not implemented"))
}

func (UnimplementedComputeServiceHandler) DescribeInstance(context.Context, *connect.Request[v1beta.DescribeInstanceRequest]) (*connect.Response[v1beta.DescribeInstanceResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("namespace.cloud.compute.v1beta.ComputeService.DescribeInstance is not implemented"))
}

func (UnimplementedComputeServiceHandler) DestroyInstance(context.Context, *connect.Request[v1beta.DestroyInstanceRequest]) (*connect.Response[emptypb.Empty], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("namespace.cloud.compute.v1beta.ComputeService.DestroyInstance is not implemented"))
}

func (UnimplementedComputeServiceHandler) ListInstances(context.Context, *connect.Request[v1beta.ListInstancesRequest]) (*connect.Response[v1beta.ListInstancesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("namespace.cloud.compute.v1beta.ComputeService.ListInstances is not implemented"))
}

func (UnimplementedComputeServiceHandler) SuspendInstance(context.Context, *connect.Request[v1beta.SuspendInstanceRequest]) (*connect.Response[emptypb.Empty], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("namespace.cloud.compute.v1beta.ComputeService.SuspendInstance is not implemented"))
}

func (UnimplementedComputeServiceHandler) WakeInstance(context.Context, *connect.Request[v1beta.WakeInstanceRequest]) (*connect.Response[emptypb.Empty], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("namespace.cloud.compute.v1beta.ComputeService.WakeInstance is not implemented"))
}

func (UnimplementedComputeServiceHandler) CreateIngress(context.Context, *connect.Request[v1beta.CreateIngressRequest]) (*connect.Response[v1beta.CreateIngressResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("namespace.cloud.compute.v1beta.ComputeService.CreateIngress is not implemented"))
}

func (UnimplementedComputeServiceHandler) ListIngresses(context.Context, *connect.Request[v1beta.ListIngressesRequest]) (*connect.Response[v1beta.ListIngressesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("namespace.cloud.compute.v1beta.ComputeService.ListIngresses is not implemented"))
}

func (UnimplementedComputeServiceHandler) GetKubernetesConfig(context.Context, *connect.Request[v1beta.GetKubernetesConfigRequest]) (*connect.Response[v1beta.GetKubernetesConfigResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("namespace.cloud.compute.v1beta.ComputeService.GetKubernetesConfig is not implemented"))
}

func (UnimplementedComputeServiceHandler) GetInstanceMetrics(context.Context, *connect.Request[v1beta.GetInstanceMetricsRequest]) (*connect.Response[v1beta.GetInstanceMetricsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("namespace.cloud.compute.v1beta.ComputeService.GetInstanceMetrics is not implemented"))
}

func (UnimplementedComputeServiceHandler) GetNetworkConfiguration(context.Context, *connect.Request[v1beta.GetNetworkConfigurationRequest]) (*connect.Response[v1beta.GetNetworkConfigurationResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("namespace.cloud.compute.v1beta.ComputeService.GetNetworkConfiguration is not implemented"))
}

func (UnimplementedComputeServiceHandler) GetSSHConfig(context.Context, *connect.Request[v1beta.GetSSHConfigRequest]) (*connect.Response[v1beta.GetSSHConfigResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("namespace.cloud.compute.v1beta.ComputeService.GetSSHConfig is not implemented"))
}

func (UnimplementedComputeServiceHandler) GetVNCConfig(context.Context, *connect.Request[v1beta.GetVNCConfigRequest]) (*connect.Response[v1beta.GetVNCConfigResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("namespace.cloud.compute.v1beta.ComputeService.GetVNCConfig is not implemented"))
}

func (UnimplementedComputeServiceHandler) ReleaseUniqueTag(context.Context, *connect.Request[v1beta.ReleaseUniqueTagRequest]) (*connect.Response[v1beta.ReleaseUniqueTagResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("namespace.cloud.compute.v1beta.ComputeService.ReleaseUniqueTag is not implemented"))
}

func (UnimplementedComputeServiceHandler) OptimizeImage(context.Context, *connect.Request[v1beta.OptimizeImageRequest], *connect.ServerStream[v1beta.OptimizeImageProgress]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("namespace.cloud.compute.v1beta.ComputeService.OptimizeImage is not implemented"))
}

func (UnimplementedComputeServiceHandler) ListInstanceNotifications(context.Context, *connect.Request[v1beta.ListInstanceNotificationsRequest]) (*connect.Response[v1beta.ListInstanceNotificationsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("namespace.cloud.compute.v1beta.ComputeService.ListInstanceNotifications is not implemented"))
}
