// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: proto/namespace/cloud/registry/v1beta/registry.proto

package registryv1beta

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	stdlib "namespacelabs.dev/integrations/proto/namespace/stdlib"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Visibility int32

const (
	Visibility_UNKNOWN_VISIBILITY Visibility = 0
	// Anyone can access the shared image provided they have access to the shared image reference.
	Visibility_PUBLIC Visibility = 1
	// Share the image with all tenants of the partner account of the tenant that owns the image.
	Visibility_PARTNER Visibility = 2
)

// Enum value maps for Visibility.
var (
	Visibility_name = map[int32]string{
		0: "UNKNOWN_VISIBILITY",
		1: "PUBLIC",
		2: "PARTNER",
	}
	Visibility_value = map[string]int32{
		"UNKNOWN_VISIBILITY": 0,
		"PUBLIC":             1,
		"PARTNER":            2,
	}
)

func (x Visibility) Enum() *Visibility {
	p := new(Visibility)
	*p = x
	return p
}

func (x Visibility) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Visibility) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_namespace_cloud_registry_v1beta_registry_proto_enumTypes[0].Descriptor()
}

func (Visibility) Type() protoreflect.EnumType {
	return &file_proto_namespace_cloud_registry_v1beta_registry_proto_enumTypes[0]
}

func (x Visibility) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Visibility.Descriptor instead.
func (Visibility) EnumDescriptor() ([]byte, []int) {
	return file_proto_namespace_cloud_registry_v1beta_registry_proto_rawDescGZIP(), []int{0}
}

// Controls whether image expiration is enforced.
type ExpirationEnforcement int32

const (
	// Default behavior for backwards compatibility:
	// - If an expiration duration is set, it is enforced.
	// - If no expiration duration is set, images do not expire (same as EXPIRATION_ENFORCEMENT_DO_NOT_ENFORCE).
	// Prefer setting an explicit enforcement value over this.
	ExpirationEnforcement_EXPIRATION_ENFORCEMENT_UNKNOWN ExpirationEnforcement = 0
	// Expiration is enforced. An expiration duration must be set.
	ExpirationEnforcement_EXPIRATION_ENFORCEMENT_ENFORCE ExpirationEnforcement = 1
	// Images do not expire, regardless of the expiration duration.
	ExpirationEnforcement_EXPIRATION_ENFORCEMENT_DO_NOT_ENFORCE ExpirationEnforcement = 2
)

// Enum value maps for ExpirationEnforcement.
var (
	ExpirationEnforcement_name = map[int32]string{
		0: "EXPIRATION_ENFORCEMENT_UNKNOWN",
		1: "EXPIRATION_ENFORCEMENT_ENFORCE",
		2: "EXPIRATION_ENFORCEMENT_DO_NOT_ENFORCE",
	}
	ExpirationEnforcement_value = map[string]int32{
		"EXPIRATION_ENFORCEMENT_UNKNOWN":        0,
		"EXPIRATION_ENFORCEMENT_ENFORCE":        1,
		"EXPIRATION_ENFORCEMENT_DO_NOT_ENFORCE": 2,
	}
)

func (x ExpirationEnforcement) Enum() *ExpirationEnforcement {
	p := new(ExpirationEnforcement)
	*p = x
	return p
}

func (x ExpirationEnforcement) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ExpirationEnforcement) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_namespace_cloud_registry_v1beta_registry_proto_enumTypes[1].Descriptor()
}

func (ExpirationEnforcement) Type() protoreflect.EnumType {
	return &file_proto_namespace_cloud_registry_v1beta_registry_proto_enumTypes[1]
}

func (x ExpirationEnforcement) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ExpirationEnforcement.Descriptor instead.
func (ExpirationEnforcement) EnumDescriptor() ([]byte, []int) {
	return file_proto_namespace_cloud_registry_v1beta_registry_proto_rawDescGZIP(), []int{1}
}

type ShareImageRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The repository that contains the image to be shared.
	Repository string `protobuf:"bytes,1,opt,name=repository,proto3" json:"repository,omitempty"`
	// The digest of the image to be shared.
	Digest string `protobuf:"bytes,2,opt,name=digest,proto3" json:"digest,omitempty"`
	// When the shared image should expire. Not setting this results in indefinitely shared images.
	ExpiresAt *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	// Defines who can access this shared image.
	Visibility Visibility `protobuf:"varint,4,opt,name=visibility,proto3,enum=namespace.cloud.registry.v1beta.Visibility" json:"visibility,omitempty"`
	// The optional suffix does not have a practical purpose apart from making the image more operationally distinct.
	// The resulting image reference will, for example, be: public.nscr.io/{meaningful_id}/{suffix}
	Suffix        string `protobuf:"bytes,5,opt,name=suffix,proto3" json:"suffix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShareImageRequest) Reset() {
	*x = ShareImageRequest{}
	mi := &file_proto_namespace_cloud_registry_v1beta_registry_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShareImageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShareImageRequest) ProtoMessage() {}

func (x *ShareImageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_namespace_cloud_registry_v1beta_registry_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShareImageRequest.ProtoReflect.Descriptor instead.
func (*ShareImageRequest) Descriptor() ([]byte, []int) {
	return file_proto_namespace_cloud_registry_v1beta_registry_proto_rawDescGZIP(), []int{0}
}

func (x *ShareImageRequest) GetRepository() string {
	if x != nil {
		return x.Repository
	}
	return ""
}

func (x *ShareImageRequest) GetDigest() string {
	if x != nil {
		return x.Digest
	}
	return ""
}

func (x *ShareImageRequest) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *ShareImageRequest) GetVisibility() Visibility {
	if x != nil {
		return x.Visibility
	}
	return Visibility_UNKNOWN_VISIBILITY
}

func (x *ShareImageRequest) GetSuffix() string {
	if x != nil {
		return x.Suffix
	}
	return ""
}

type UnshareImageRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The unique identifier of the shared image to unshare.
	Id            string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnshareImageRequest) Reset() {
	*x = UnshareImageRequest{}
	mi := &file_proto_namespace_cloud_registry_v1beta_registry_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnshareImageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnshareImageRequest) ProtoMessage() {}

func (x *UnshareImageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_namespace_cloud_registry_v1beta_registry_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnshareImageRequest.ProtoReflect.Descriptor instead.
func (*UnshareImageRequest) Descriptor() ([]byte, []int) {
	return file_proto_namespace_cloud_registry_v1beta_registry_proto_rawDescGZIP(), []int{1}
}

func (x *UnshareImageRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListSharedImagesRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	MatchRepositories *stdlib.StringMatcher  `protobuf:"bytes,1,opt,name=match_repositories,json=matchRepositories,proto3" json:"match_repositories,omitempty"`
	// If set to UNKNOWN_VISIBILITY any image is returned.
	MatchVisibility Visibility `protobuf:"varint,2,opt,name=match_visibility,json=matchVisibility,proto3,enum=namespace.cloud.registry.v1beta.Visibility" json:"match_visibility,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ListSharedImagesRequest) Reset() {
	*x = ListSharedImagesRequest{}
	mi := &file_proto_namespace_cloud_registry_v1beta_registry_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSharedImagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSharedImagesRequest) ProtoMessage() {}

func (x *ListSharedImagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_namespace_cloud_registry_v1beta_registry_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSharedImagesRequest.ProtoReflect.Descriptor instead.
func (*ListSharedImagesRequest) Descriptor() ([]byte, []int) {
	return file_proto_namespace_cloud_registry_v1beta_registry_proto_rawDescGZIP(), []int{2}
}

func (x *ListSharedImagesRequest) GetMatchRepositories() *stdlib.StringMatcher {
	if x != nil {
		return x.MatchRepositories
	}
	return nil
}

func (x *ListSharedImagesRequest) GetMatchVisibility() Visibility {
	if x != nil {
		return x.MatchVisibility
	}
	return Visibility_UNKNOWN_VISIBILITY
}

type ListSharedImagesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SharedImages  []*SharedImage         `protobuf:"bytes,1,rep,name=shared_images,json=sharedImages,proto3" json:"shared_images,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSharedImagesResponse) Reset() {
	*x = ListSharedImagesResponse{}
	mi := &file_proto_namespace_cloud_registry_v1beta_registry_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSharedImagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSharedImagesResponse) ProtoMessage() {}

func (x *ListSharedImagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_namespace_cloud_registry_v1beta_registry_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSharedImagesResponse.ProtoReflect.Descriptor instead.
func (*ListSharedImagesResponse) Descriptor() ([]byte, []int) {
	return file_proto_namespace_cloud_registry_v1beta_registry_proto_rawDescGZIP(), []int{3}
}

func (x *ListSharedImagesResponse) GetSharedImages() []*SharedImage {
	if x != nil {
		return x.SharedImages
	}
	return nil
}

type SharedImage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The unique identifier of this shared image.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// The repository that contains the shared image.
	SharedRepository string `protobuf:"bytes,2,opt,name=shared_repository,json=sharedRepository,proto3" json:"shared_repository,omitempty"`
	// The digest of the shared image.
	SharedDigest string `protobuf:"bytes,3,opt,name=shared_digest,json=sharedDigest,proto3" json:"shared_digest,omitempty"`
	// When this shared image expires.
	ExpiresAt *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	// The image reference used to access the shared image.
	ImageRef   string     `protobuf:"bytes,5,opt,name=image_ref,json=imageRef,proto3" json:"image_ref,omitempty"`
	Visibility Visibility `protobuf:"varint,6,opt,name=visibility,proto3,enum=namespace.cloud.registry.v1beta.Visibility" json:"visibility,omitempty"`
	// The suffix that was provided when the shared image got created.
	Suffix        string `protobuf:"bytes,7,opt,name=suffix,proto3" json:"suffix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SharedImage) Reset() {
	*x = SharedImage{}
	mi := &file_proto_namespace_cloud_registry_v1beta_registry_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SharedImage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SharedImage) ProtoMessage() {}

func (x *SharedImage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_namespace_cloud_registry_v1beta_registry_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SharedImage.ProtoReflect.Descriptor instead.
func (*SharedImage) Descriptor() ([]byte, []int) {
	return file_proto_namespace_cloud_registry_v1beta_registry_proto_rawDescGZIP(), []int{4}
}

func (x *SharedImage) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SharedImage) GetSharedRepository() string {
	if x != nil {
		return x.SharedRepository
	}
	return ""
}

func (x *SharedImage) GetSharedDigest() string {
	if x != nil {
		return x.SharedDigest
	}
	return ""
}

func (x *SharedImage) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *SharedImage) GetImageRef() string {
	if x != nil {
		return x.ImageRef
	}
	return ""
}

func (x *SharedImage) GetVisibility() Visibility {
	if x != nil {
		return x.Visibility
	}
	return Visibility_UNKNOWN_VISIBILITY
}

func (x *SharedImage) GetSuffix() string {
	if x != nil {
		return x.Suffix
	}
	return ""
}

type ListImagesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// If a previous response returned a `pagination_cursor`, it can be
	// specified to continue reading results with the same arguments as the
	// original call.
	PaginationCursor []byte `protobuf:"bytes,1,opt,name=pagination_cursor,json=paginationCursor,proto3" json:"pagination_cursor,omitempty"`
	// The maximum number of entries to return as part of this ListImages
	// request. A maximum number of entries may also be specified when
	// `pagination_cursor` is set.
	//
	// We won't return more than `max_entries`, but may return fewer.
	MaxEntries int64 `protobuf:"varint,2,opt,name=max_entries,json=maxEntries,proto3" json:"max_entries,omitempty"`
	// Filter images by repository name. If not specified, images from all repositories are returned.
	MatchRepository *stdlib.StringMatcher `protobuf:"bytes,3,opt,name=match_repository,json=matchRepository,proto3" json:"match_repository,omitempty"`
	// Filter images by creation timestamp range.
	CreatedAt     *stdlib.TimestampRange `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListImagesRequest) Reset() {
	*x = ListImagesRequest{}
	mi := &file_proto_namespace_cloud_registry_v1beta_registry_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListImagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListImagesRequest) ProtoMessage() {}

func (x *ListImagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_namespace_cloud_registry_v1beta_registry_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListImagesRequest.ProtoReflect.Descriptor instead.
func (*ListImagesRequest) Descriptor() ([]byte, []int) {
	return file_proto_namespace_cloud_registry_v1beta_registry_proto_rawDescGZIP(), []int{5}
}

func (x *ListImagesRequest) GetPaginationCursor() []byte {
	if x != nil {
		return x.PaginationCursor
	}
	return nil
}

func (x *ListImagesRequest) GetMaxEntries() int64 {
	if x != nil {
		return x.MaxEntries
	}
	return 0
}

func (x *ListImagesRequest) GetMatchRepository() *stdlib.StringMatcher {
	if x != nil {
		return x.MatchRepository
	}
	return nil
}

func (x *ListImagesRequest) GetCreatedAt() *stdlib.TimestampRange {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type ListImagesResponse struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Images []*Image               `protobuf:"bytes,1,rep,name=images,proto3" json:"images,omitempty"`
	// If set, there are additional results. Pass the same cursor to a
	// subsequent ListImages call to continue fetching results.
	PaginationCursor []byte `protobuf:"bytes,2,opt,name=pagination_cursor,json=paginationCursor,proto3" json:"pagination_cursor,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ListImagesResponse) Reset() {
	*x = ListImagesResponse{}
	mi := &file_proto_namespace_cloud_registry_v1beta_registry_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListImagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListImagesResponse) ProtoMessage() {}

func (x *ListImagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_namespace_cloud_registry_v1beta_registry_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListImagesResponse.ProtoReflect.Descriptor instead.
func (*ListImagesResponse) Descriptor() ([]byte, []int) {
	return file_proto_namespace_cloud_registry_v1beta_registry_proto_rawDescGZIP(), []int{6}
}

func (x *ListImagesResponse) GetImages() []*Image {
	if x != nil {
		return x.Images
	}
	return nil
}

func (x *ListImagesResponse) GetPaginationCursor() []byte {
	if x != nil {
		return x.PaginationCursor
	}
	return nil
}

type ListRepositoriesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// If a previous response returned a `pagination_cursor`, it can be
	// specified to continue reading results with the same arguments as the
	// original call.
	PaginationCursor []byte `protobuf:"bytes,1,opt,name=pagination_cursor,json=paginationCursor,proto3" json:"pagination_cursor,omitempty"`
	// The maximum number of entries to return as part of this ListRepositories
	// request. A maximum number of entries may also be specified when
	// `pagination_cursor` is set.
	//
	// We won't return more than `max_entries`, but may return fewer.
	MaxEntries    int64 `protobuf:"varint,2,opt,name=max_entries,json=maxEntries,proto3" json:"max_entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRepositoriesRequest) Reset() {
	*x = ListRepositoriesRequest{}
	mi := &file_proto_namespace_cloud_registry_v1beta_registry_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRepositoriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRepositoriesRequest) ProtoMessage() {}

func (x *ListRepositoriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_namespace_cloud_registry_v1beta_registry_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRepositoriesRequest.ProtoReflect.Descriptor instead.
func (*ListRepositoriesRequest) Descriptor() ([]byte, []int) {
	return file_proto_namespace_cloud_registry_v1beta_registry_proto_rawDescGZIP(), []int{7}
}

func (x *ListRepositoriesRequest) GetPaginationCursor() []byte {
	if x != nil {
		return x.PaginationCursor
	}
	return nil
}

func (x *ListRepositoriesRequest) GetMaxEntries() int64 {
	if x != nil {
		return x.MaxEntries
	}
	return 0
}

type ListRepositoriesResponse struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	Repositories []*Repository          `protobuf:"bytes,1,rep,name=repositories,proto3" json:"repositories,omitempty"`
	// If set, there are additional results. Pass the same cursor to a
	// subsequent ListRepositories call to continue fetching results.
	PaginationCursor []byte `protobuf:"bytes,2,opt,name=pagination_cursor,json=paginationCursor,proto3" json:"pagination_cursor,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ListRepositoriesResponse) Reset() {
	*x = ListRepositoriesResponse{}
	mi := &file_proto_namespace_cloud_registry_v1beta_registry_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRepositoriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRepositoriesResponse) ProtoMessage() {}

func (x *ListRepositoriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_namespace_cloud_registry_v1beta_registry_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRepositoriesResponse.ProtoReflect.Descriptor instead.
func (*ListRepositoriesResponse) Descriptor() ([]byte, []int) {
	return file_proto_namespace_cloud_registry_v1beta_registry_proto_rawDescGZIP(), []int{8}
}

func (x *ListRepositoriesResponse) GetRepositories() []*Repository {
	if x != nil {
		return x.Repositories
	}
	return nil
}

func (x *ListRepositoriesResponse) GetPaginationCursor() []byte {
	if x != nil {
		return x.PaginationCursor
	}
	return nil
}

type Repository struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The name of the repository.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// The timestamp of the last push to this repository.
	LastPush      *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=last_push,json=lastPush,proto3" json:"last_push,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Repository) Reset() {
	*x = Repository{}
	mi := &file_proto_namespace_cloud_registry_v1beta_registry_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Repository) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Repository) ProtoMessage() {}

func (x *Repository) ProtoReflect() protoreflect.Message {
	mi := &file_proto_namespace_cloud_registry_v1beta_registry_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Repository.ProtoReflect.Descriptor instead.
func (*Repository) Descriptor() ([]byte, []int) {
	return file_proto_namespace_cloud_registry_v1beta_registry_proto_rawDescGZIP(), []int{9}
}

func (x *Repository) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Repository) GetLastPush() *timestamppb.Timestamp {
	if x != nil {
		return x.LastPush
	}
	return nil
}

type ListTagsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// If a previous response returned a `pagination_cursor`, it can be
	// specified to continue reading results with the same arguments as the
	// original call.
	PaginationCursor []byte `protobuf:"bytes,1,opt,name=pagination_cursor,json=paginationCursor,proto3" json:"pagination_cursor,omitempty"`
	// The maximum number of entries to return as part of this ListTags
	// request. A maximum number of entries may also be specified when
	// `pagination_cursor` is set.
	//
	// We won't return more than `max_entries`, but may return fewer.
	MaxEntries int64 `protobuf:"varint,2,opt,name=max_entries,json=maxEntries,proto3" json:"max_entries,omitempty"`
	// The repository to list tags from.
	Repository    string `protobuf:"bytes,3,opt,name=repository,proto3" json:"repository,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTagsRequest) Reset() {
	*x = ListTagsRequest{}
	mi := &file_proto_namespace_cloud_registry_v1beta_registry_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTagsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTagsRequest) ProtoMessage() {}

func (x *ListTagsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_namespace_cloud_registry_v1beta_registry_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTagsRequest.ProtoReflect.Descriptor instead.
func (*ListTagsRequest) Descriptor() ([]byte, []int) {
	return file_proto_namespace_cloud_registry_v1beta_registry_proto_rawDescGZIP(), []int{10}
}

func (x *ListTagsRequest) GetPaginationCursor() []byte {
	if x != nil {
		return x.PaginationCursor
	}
	return nil
}

func (x *ListTagsRequest) GetMaxEntries() int64 {
	if x != nil {
		return x.MaxEntries
	}
	return 0
}

func (x *ListTagsRequest) GetRepository() string {
	if x != nil {
		return x.Repository
	}
	return ""
}

type ListTagsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Tags  []*Tag                 `protobuf:"bytes,1,rep,name=tags,proto3" json:"tags,omitempty"`
	// If set, there are additional results. Pass the same cursor to a
	// subsequent ListTags call to continue fetching results.
	PaginationCursor []byte `protobuf:"bytes,2,opt,name=pagination_cursor,json=paginationCursor,proto3" json:"pagination_cursor,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ListTagsResponse) Reset() {
	*x = ListTagsResponse{}
	mi := &file_proto_namespace_cloud_registry_v1beta_registry_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTagsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTagsResponse) ProtoMessage() {}

func (x *ListTagsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_namespace_cloud_registry_v1beta_registry_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTagsResponse.ProtoReflect.Descriptor instead.
func (*ListTagsResponse) Descriptor() ([]byte, []int) {
	return file_proto_namespace_cloud_registry_v1beta_registry_proto_rawDescGZIP(), []int{11}
}

func (x *ListTagsResponse) GetTags() []*Tag {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *ListTagsResponse) GetPaginationCursor() []byte {
	if x != nil {
		return x.PaginationCursor
	}
	return nil
}

type ListTagVersionsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// If a previous response returned a `pagination_cursor`, it can be
	// specified to continue reading results with the same arguments as the
	// original call.
	PaginationCursor []byte `protobuf:"bytes,1,opt,name=pagination_cursor,json=paginationCursor,proto3" json:"pagination_cursor,omitempty"`
	// The maximum number of entries to return as part of this ListTagVersions
	// request. A maximum number of entries may also be specified when
	// `pagination_cursor` is set.
	//
	// We won't return more than `max_entries`, but may return fewer.
	MaxEntries int64 `protobuf:"varint,2,opt,name=max_entries,json=maxEntries,proto3" json:"max_entries,omitempty"`
	// The repository containing the tag.
	Repository string `protobuf:"bytes,3,opt,name=repository,proto3" json:"repository,omitempty"`
	// The tag to list versions for.
	Tag           string `protobuf:"bytes,4,opt,name=tag,proto3" json:"tag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTagVersionsRequest) Reset() {
	*x = ListTagVersionsRequest{}
	mi := &file_proto_namespace_cloud_registry_v1beta_registry_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTagVersionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTagVersionsRequest) ProtoMessage() {}

func (x *ListTagVersionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_namespace_cloud_registry_v1beta_registry_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTagVersionsRequest.ProtoReflect.Descriptor instead.
func (*ListTagVersionsRequest) Descriptor() ([]byte, []int) {
	return file_proto_namespace_cloud_registry_v1beta_registry_proto_rawDescGZIP(), []int{12}
}

func (x *ListTagVersionsRequest) GetPaginationCursor() []byte {
	if x != nil {
		return x.PaginationCursor
	}
	return nil
}

func (x *ListTagVersionsRequest) GetMaxEntries() int64 {
	if x != nil {
		return x.MaxEntries
	}
	return 0
}

func (x *ListTagVersionsRequest) GetRepository() string {
	if x != nil {
		return x.Repository
	}
	return ""
}

func (x *ListTagVersionsRequest) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

type ListTagVersionsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The versions of the tag, ordered from newest to oldest.
	Versions []*Tag `protobuf:"bytes,1,rep,name=versions,proto3" json:"versions,omitempty"`
	// If set, there are additional results. Pass the same cursor to a
	// subsequent ListTagVersions call to continue fetching results.
	PaginationCursor []byte `protobuf:"bytes,2,opt,name=pagination_cursor,json=paginationCursor,proto3" json:"pagination_cursor,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ListTagVersionsResponse) Reset() {
	*x = ListTagVersionsResponse{}
	mi := &file_proto_namespace_cloud_registry_v1beta_registry_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTagVersionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTagVersionsResponse) ProtoMessage() {}

func (x *ListTagVersionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_namespace_cloud_registry_v1beta_registry_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTagVersionsResponse.ProtoReflect.Descriptor instead.
func (*ListTagVersionsResponse) Descriptor() ([]byte, []int) {
	return file_proto_namespace_cloud_registry_v1beta_registry_proto_rawDescGZIP(), []int{13}
}

func (x *ListTagVersionsResponse) GetVersions() []*Tag {
	if x != nil {
		return x.Versions
	}
	return nil
}

func (x *ListTagVersionsResponse) GetPaginationCursor() []byte {
	if x != nil {
		return x.PaginationCursor
	}
	return nil
}

type GetImageRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The repository containing the image.
	Repository string `protobuf:"bytes,1,opt,name=repository,proto3" json:"repository,omitempty"`
	// The reference to the image. Can be either a tag or a digest.
	// Digests have the form sha256:<hash>.
	Reference     string `protobuf:"bytes,2,opt,name=reference,proto3" json:"reference,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetImageRequest) Reset() {
	*x = GetImageRequest{}
	mi := &file_proto_namespace_cloud_registry_v1beta_registry_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetImageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetImageRequest) ProtoMessage() {}

func (x *GetImageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_namespace_cloud_registry_v1beta_registry_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetImageRequest.ProtoReflect.Descriptor instead.
func (*GetImageRequest) Descriptor() ([]byte, []int) {
	return file_proto_namespace_cloud_registry_v1beta_registry_proto_rawDescGZIP(), []int{14}
}

func (x *GetImageRequest) GetRepository() string {
	if x != nil {
		return x.Repository
	}
	return ""
}

func (x *GetImageRequest) GetReference() string {
	if x != nil {
		return x.Reference
	}
	return ""
}

type GetImageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Image         *Image                 `protobuf:"bytes,1,opt,name=image,proto3" json:"image,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetImageResponse) Reset() {
	*x = GetImageResponse{}
	mi := &file_proto_namespace_cloud_registry_v1beta_registry_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetImageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetImageResponse) ProtoMessage() {}

func (x *GetImageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_namespace_cloud_registry_v1beta_registry_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetImageResponse.ProtoReflect.Descriptor instead.
func (*GetImageResponse) Descriptor() ([]byte, []int) {
	return file_proto_namespace_cloud_registry_v1beta_registry_proto_rawDescGZIP(), []int{15}
}

func (x *GetImageResponse) GetImage() *Image {
	if x != nil {
		return x.Image
	}
	return nil
}

type Image struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The repository containing the image.
	Repository string `protobuf:"bytes,1,opt,name=repository,proto3" json:"repository,omitempty"`
	// The digest of the image.
	Digest string `protobuf:"bytes,2,opt,name=digest,proto3" json:"digest,omitempty"`
	// When the image was created.
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// When the image expires. Not set if the image does not expire.
	ExpiresAt *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	// Size information for the image.
	Sizes *Image_Sizes `protobuf:"bytes,5,opt,name=sizes,proto3" json:"sizes,omitempty"`
	// If the image has been deleted, when it was deleted.
	DeletedAt *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	// Labels attached to this image.
	Labels []*stdlib.Label `protobuf:"bytes,7,rep,name=labels,proto3" json:"labels,omitempty"`
	// Tags that reference this image.
	Tags          []string `protobuf:"bytes,8,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Image) Reset() {
	*x = Image{}
	mi := &file_proto_namespace_cloud_registry_v1beta_registry_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Image) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Image) ProtoMessage() {}

func (x *Image) ProtoReflect() protoreflect.Message {
	mi := &file_proto_namespace_cloud_registry_v1beta_registry_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Image.ProtoReflect.Descriptor instead.
func (*Image) Descriptor() ([]byte, []int) {
	return file_proto_namespace_cloud_registry_v1beta_registry_proto_rawDescGZIP(), []int{16}
}

func (x *Image) GetRepository() string {
	if x != nil {
		return x.Repository
	}
	return ""
}

func (x *Image) GetDigest() string {
	if x != nil {
		return x.Digest
	}
	return ""
}

func (x *Image) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Image) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *Image) GetSizes() *Image_Sizes {
	if x != nil {
		return x.Sizes
	}
	return nil
}

func (x *Image) GetDeletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DeletedAt
	}
	return nil
}

func (x *Image) GetLabels() []*stdlib.Label {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *Image) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

type Tag struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The tag name.
	Tag string `protobuf:"bytes,1,opt,name=tag,proto3" json:"tag,omitempty"`
	// The image this tag points to.
	Image *Image `protobuf:"bytes,2,opt,name=image,proto3" json:"image,omitempty"`
	// When the tag was created.
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Tag) Reset() {
	*x = Tag{}
	mi := &file_proto_namespace_cloud_registry_v1beta_registry_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tag) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tag) ProtoMessage() {}

func (x *Tag) ProtoReflect() protoreflect.Message {
	mi := &file_proto_namespace_cloud_registry_v1beta_registry_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tag.ProtoReflect.Descriptor instead.
func (*Tag) Descriptor() ([]byte, []int) {
	return file_proto_namespace_cloud_registry_v1beta_registry_proto_rawDescGZIP(), []int{17}
}

func (x *Tag) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *Tag) GetImage() *Image {
	if x != nil {
		return x.Image
	}
	return nil
}

func (x *Tag) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type UpdateImageLifetimeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The repository containing the image.
	Repository string `protobuf:"bytes,1,opt,name=repository,proto3" json:"repository,omitempty"`
	// The digest of the image of the form sha256:<hash>.
	Digest string `protobuf:"bytes,2,opt,name=digest,proto3" json:"digest,omitempty"`
	// The duration the lifetime of this image should be extended by.
	// If the image currently has no expiration then providing extend_by is not supported.
	// Can not be used in combination with new_expiry.
	//
	// Note: In JSON format, the Duration type is encoded as a string rather than an
	// object, where the string ends in the suffix "s" (indicating seconds) and
	// is preceded by the number of seconds, with nanoseconds expressed as
	// fractional seconds.
	ExtendBy *durationpb.Duration `protobuf:"bytes,3,opt,name=extend_by,json=extendBy,proto3" json:"extend_by,omitempty"`
	// The minimum remaining duration this image should be alive for.
	//
	// Note: In JSON format, the Duration type is encoded as a string rather than an
	// object, where the string ends in the suffix "s" (indicating seconds) and
	// is preceded by the number of seconds, with nanoseconds expressed as
	// fractional seconds.
	EnsureMinimumRemaining *durationpb.Duration `protobuf:"bytes,4,opt,name=ensure_minimum_remaining,json=ensureMinimumRemaining,proto3" json:"ensure_minimum_remaining,omitempty"`
	// The new expiration timestamp (in UTC) at which the image expires.
	// Can not be used in combination with extend_by.
	//
	// Note: In JSON format, the Timestamp type is encoded as a string in the
	// [RFC 3339](https://www.ietf.org/rfc/rfc3339.txt) format.
	NewExpiry     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=new_expiry,json=newExpiry,proto3" json:"new_expiry,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateImageLifetimeRequest) Reset() {
	*x = UpdateImageLifetimeRequest{}
	mi := &file_proto_namespace_cloud_registry_v1beta_registry_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateImageLifetimeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateImageLifetimeRequest) ProtoMessage() {}

func (x *UpdateImageLifetimeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_namespace_cloud_registry_v1beta_registry_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateImageLifetimeRequest.ProtoReflect.Descriptor instead.
func (*UpdateImageLifetimeRequest) Descriptor() ([]byte, []int) {
	return file_proto_namespace_cloud_registry_v1beta_registry_proto_rawDescGZIP(), []int{18}
}

func (x *UpdateImageLifetimeRequest) GetRepository() string {
	if x != nil {
		return x.Repository
	}
	return ""
}

func (x *UpdateImageLifetimeRequest) GetDigest() string {
	if x != nil {
		return x.Digest
	}
	return ""
}

func (x *UpdateImageLifetimeRequest) GetExtendBy() *durationpb.Duration {
	if x != nil {
		return x.ExtendBy
	}
	return nil
}

func (x *UpdateImageLifetimeRequest) GetEnsureMinimumRemaining() *durationpb.Duration {
	if x != nil {
		return x.EnsureMinimumRemaining
	}
	return nil
}

func (x *UpdateImageLifetimeRequest) GetNewExpiry() *timestamppb.Timestamp {
	if x != nil {
		return x.NewExpiry
	}
	return nil
}

type UpdateImageLifetimeResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// A timestamp at which the image will expire.
	NewExpiry     *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=new_expiry,json=newExpiry,proto3" json:"new_expiry,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateImageLifetimeResponse) Reset() {
	*x = UpdateImageLifetimeResponse{}
	mi := &file_proto_namespace_cloud_registry_v1beta_registry_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateImageLifetimeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateImageLifetimeResponse) ProtoMessage() {}

func (x *UpdateImageLifetimeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_namespace_cloud_registry_v1beta_registry_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateImageLifetimeResponse.ProtoReflect.Descriptor instead.
func (*UpdateImageLifetimeResponse) Descriptor() ([]byte, []int) {
	return file_proto_namespace_cloud_registry_v1beta_registry_proto_rawDescGZIP(), []int{19}
}

func (x *UpdateImageLifetimeResponse) GetNewExpiry() *timestamppb.Timestamp {
	if x != nil {
		return x.NewExpiry
	}
	return nil
}

type UpdateDefaultPolicyRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Only update if revision matches.
	Revision int64 `protobuf:"varint,1,opt,name=revision,proto3" json:"revision,omitempty"`
	// The new default expiration duration for newly created images.
	// A duration of at least 4h (=14400s) is required.
	// In order to apply the expiration retroactively to existing images reach out to `support@namespace.so`.
	//
	// Note: In JSON format, the Duration type is encoded as a string rather than an
	// object, where the string ends in the suffix "s" (indicating seconds) and
	// is preceded by the number of seconds, with nanoseconds expressed as
	// fractional seconds.
	DefaultExpiration *durationpb.Duration `protobuf:"bytes,2,opt,name=default_expiration,json=defaultExpiration,proto3" json:"default_expiration,omitempty"`
	// Controls whether expiration is enforced.
	ExpirationEnforcement ExpirationEnforcement `protobuf:"varint,3,opt,name=expiration_enforcement,json=expirationEnforcement,proto3,enum=namespace.cloud.registry.v1beta.ExpirationEnforcement" json:"expiration_enforcement,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *UpdateDefaultPolicyRequest) Reset() {
	*x = UpdateDefaultPolicyRequest{}
	mi := &file_proto_namespace_cloud_registry_v1beta_registry_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDefaultPolicyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDefaultPolicyRequest) ProtoMessage() {}

func (x *UpdateDefaultPolicyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_namespace_cloud_registry_v1beta_registry_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDefaultPolicyRequest.ProtoReflect.Descriptor instead.
func (*UpdateDefaultPolicyRequest) Descriptor() ([]byte, []int) {
	return file_proto_namespace_cloud_registry_v1beta_registry_proto_rawDescGZIP(), []int{20}
}

func (x *UpdateDefaultPolicyRequest) GetRevision() int64 {
	if x != nil {
		return x.Revision
	}
	return 0
}

func (x *UpdateDefaultPolicyRequest) GetDefaultExpiration() *durationpb.Duration {
	if x != nil {
		return x.DefaultExpiration
	}
	return nil
}

func (x *UpdateDefaultPolicyRequest) GetExpirationEnforcement() ExpirationEnforcement {
	if x != nil {
		return x.ExpirationEnforcement
	}
	return ExpirationEnforcement_EXPIRATION_ENFORCEMENT_UNKNOWN
}

type GetDefaultPolicyResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The current revision.
	Revision int64 `protobuf:"varint,1,opt,name=revision,proto3" json:"revision,omitempty"`
	// The default expiration duration that is applied to newly created images.
	// After this duration the image becomes inaccessible and the underlying blobs are deleted.
	// Not set means no default policy is configured.
	//
	// Note: In JSON format, the Duration type is encoded as a string rather than an
	// object, where the string ends in the suffix "s" (indicating seconds) and
	// is preceded by the number of seconds, with nanoseconds expressed as
	// fractional seconds.
	DefaultExpiration *durationpb.Duration `protobuf:"bytes,2,opt,name=default_expiration,json=defaultExpiration,proto3" json:"default_expiration,omitempty"`
	// Controls whether expiration is enforced.
	ExpirationEnforcement ExpirationEnforcement `protobuf:"varint,3,opt,name=expiration_enforcement,json=expirationEnforcement,proto3,enum=namespace.cloud.registry.v1beta.ExpirationEnforcement" json:"expiration_enforcement,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *GetDefaultPolicyResponse) Reset() {
	*x = GetDefaultPolicyResponse{}
	mi := &file_proto_namespace_cloud_registry_v1beta_registry_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDefaultPolicyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDefaultPolicyResponse) ProtoMessage() {}

func (x *GetDefaultPolicyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_namespace_cloud_registry_v1beta_registry_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDefaultPolicyResponse.ProtoReflect.Descriptor instead.
func (*GetDefaultPolicyResponse) Descriptor() ([]byte, []int) {
	return file_proto_namespace_cloud_registry_v1beta_registry_proto_rawDescGZIP(), []int{21}
}

func (x *GetDefaultPolicyResponse) GetRevision() int64 {
	if x != nil {
		return x.Revision
	}
	return 0
}

func (x *GetDefaultPolicyResponse) GetDefaultExpiration() *durationpb.Duration {
	if x != nil {
		return x.DefaultExpiration
	}
	return nil
}

func (x *GetDefaultPolicyResponse) GetExpirationEnforcement() ExpirationEnforcement {
	if x != nil {
		return x.ExpirationEnforcement
	}
	return ExpirationEnforcement_EXPIRATION_ENFORCEMENT_UNKNOWN
}

type UpdateRepositoryPolicyRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The repository to configure.
	Repository string `protobuf:"bytes,1,opt,name=repository,proto3" json:"repository,omitempty"`
	// Only update if revision matches.
	Revision int64 `protobuf:"varint,2,opt,name=revision,proto3" json:"revision,omitempty"`
	// The expiration duration for newly created images in this repository.
	// A duration of at least 4h (=14400s) is required.
	// If set, this overrides the default policy for images pushed to this repository.
	// If not set, the default policy is used.
	//
	// Note: In JSON format, the Duration type is encoded as a string rather than an
	// object, where the string ends in the suffix "s" (indicating seconds) and
	// is preceded by the number of seconds, with nanoseconds expressed as
	// fractional seconds.
	Expiration *durationpb.Duration `protobuf:"bytes,3,opt,name=expiration,proto3" json:"expiration,omitempty"`
	// Controls whether expiration is enforced for this repository.
	ExpirationEnforcement ExpirationEnforcement `protobuf:"varint,4,opt,name=expiration_enforcement,json=expirationEnforcement,proto3,enum=namespace.cloud.registry.v1beta.ExpirationEnforcement" json:"expiration_enforcement,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *UpdateRepositoryPolicyRequest) Reset() {
	*x = UpdateRepositoryPolicyRequest{}
	mi := &file_proto_namespace_cloud_registry_v1beta_registry_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRepositoryPolicyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRepositoryPolicyRequest) ProtoMessage() {}

func (x *UpdateRepositoryPolicyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_namespace_cloud_registry_v1beta_registry_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRepositoryPolicyRequest.ProtoReflect.Descriptor instead.
func (*UpdateRepositoryPolicyRequest) Descriptor() ([]byte, []int) {
	return file_proto_namespace_cloud_registry_v1beta_registry_proto_rawDescGZIP(), []int{22}
}

func (x *UpdateRepositoryPolicyRequest) GetRepository() string {
	if x != nil {
		return x.Repository
	}
	return ""
}

func (x *UpdateRepositoryPolicyRequest) GetRevision() int64 {
	if x != nil {
		return x.Revision
	}
	return 0
}

func (x *UpdateRepositoryPolicyRequest) GetExpiration() *durationpb.Duration {
	if x != nil {
		return x.Expiration
	}
	return nil
}

func (x *UpdateRepositoryPolicyRequest) GetExpirationEnforcement() ExpirationEnforcement {
	if x != nil {
		return x.ExpirationEnforcement
	}
	return ExpirationEnforcement_EXPIRATION_ENFORCEMENT_UNKNOWN
}

type GetRepositoryPolicyRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The repository to get the policy for.
	Repository    string `protobuf:"bytes,1,opt,name=repository,proto3" json:"repository,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRepositoryPolicyRequest) Reset() {
	*x = GetRepositoryPolicyRequest{}
	mi := &file_proto_namespace_cloud_registry_v1beta_registry_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRepositoryPolicyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRepositoryPolicyRequest) ProtoMessage() {}

func (x *GetRepositoryPolicyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_namespace_cloud_registry_v1beta_registry_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRepositoryPolicyRequest.ProtoReflect.Descriptor instead.
func (*GetRepositoryPolicyRequest) Descriptor() ([]byte, []int) {
	return file_proto_namespace_cloud_registry_v1beta_registry_proto_rawDescGZIP(), []int{23}
}

func (x *GetRepositoryPolicyRequest) GetRepository() string {
	if x != nil {
		return x.Repository
	}
	return ""
}

type GetRepositoryPolicyResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The current revision.
	Revision int64 `protobuf:"varint,1,opt,name=revision,proto3" json:"revision,omitempty"`
	// The expiration duration that is applied to newly created images in this repository.
	// Not set means the default policy is used.
	//
	// Note: In JSON format, the Duration type is encoded as a string rather than an
	// object, where the string ends in the suffix "s" (indicating seconds) and
	// is preceded by the number of seconds, with nanoseconds expressed as
	// fractional seconds.
	Expiration *durationpb.Duration `protobuf:"bytes,2,opt,name=expiration,proto3" json:"expiration,omitempty"`
	// Controls whether expiration is enforced for this repository.
	ExpirationEnforcement ExpirationEnforcement `protobuf:"varint,3,opt,name=expiration_enforcement,json=expirationEnforcement,proto3,enum=namespace.cloud.registry.v1beta.ExpirationEnforcement" json:"expiration_enforcement,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *GetRepositoryPolicyResponse) Reset() {
	*x = GetRepositoryPolicyResponse{}
	mi := &file_proto_namespace_cloud_registry_v1beta_registry_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRepositoryPolicyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRepositoryPolicyResponse) ProtoMessage() {}

func (x *GetRepositoryPolicyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_namespace_cloud_registry_v1beta_registry_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRepositoryPolicyResponse.ProtoReflect.Descriptor instead.
func (*GetRepositoryPolicyResponse) Descriptor() ([]byte, []int) {
	return file_proto_namespace_cloud_registry_v1beta_registry_proto_rawDescGZIP(), []int{24}
}

func (x *GetRepositoryPolicyResponse) GetRevision() int64 {
	if x != nil {
		return x.Revision
	}
	return 0
}

func (x *GetRepositoryPolicyResponse) GetExpiration() *durationpb.Duration {
	if x != nil {
		return x.Expiration
	}
	return nil
}

func (x *GetRepositoryPolicyResponse) GetExpirationEnforcement() ExpirationEnforcement {
	if x != nil {
		return x.ExpirationEnforcement
	}
	return ExpirationEnforcement_EXPIRATION_ENFORCEMENT_UNKNOWN
}

type Image_Sizes struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Total size of the image in bytes.
	Total int64 `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	// Size per platform in bytes. Keys are platform identifiers (e.g., "linux/amd64").
	PerPlatform   map[string]int64 `protobuf:"bytes,2,rep,name=per_platform,json=perPlatform,proto3" json:"per_platform,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Image_Sizes) Reset() {
	*x = Image_Sizes{}
	mi := &file_proto_namespace_cloud_registry_v1beta_registry_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Image_Sizes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Image_Sizes) ProtoMessage() {}

func (x *Image_Sizes) ProtoReflect() protoreflect.Message {
	mi := &file_proto_namespace_cloud_registry_v1beta_registry_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Image_Sizes.ProtoReflect.Descriptor instead.
func (*Image_Sizes) Descriptor() ([]byte, []int) {
	return file_proto_namespace_cloud_registry_v1beta_registry_proto_rawDescGZIP(), []int{16, 0}
}

func (x *Image_Sizes) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *Image_Sizes) GetPerPlatform() map[string]int64 {
	if x != nil {
		return x.PerPlatform
	}
	return nil
}

var File_proto_namespace_cloud_registry_v1beta_registry_proto protoreflect.FileDescriptor

const file_proto_namespace_cloud_registry_v1beta_registry_proto_rawDesc = "" +
	"\n" +
	"4proto/namespace/cloud/registry/v1beta/registry.proto\x12\x1fnamespace.cloud.registry.v1beta\x1a\x1egoogle/protobuf/duration.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a#proto/namespace/stdlib/labels.proto\x1a%proto/namespace/stdlib/matchers.proto\"\xeb\x01\n" +
	"\x11ShareImageRequest\x12\x1e\n" +
	"\n" +
	"repository\x18\x01 \x01(\tR\n" +
	"repository\x12\x16\n" +
	"\x06digest\x18\x02 \x01(\tR\x06digest\x129\n" +
	"\n" +
	"expires_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x12K\n" +
	"\n" +
	"visibility\x18\x04 \x01(\x0e2+.namespace.cloud.registry.v1beta.VisibilityR\n" +
	"visibility\x12\x16\n" +
	"\x06suffix\x18\x05 \x01(\tR\x06suffix\"%\n" +
	"\x13UnshareImageRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xc1\x01\n" +
	"\x17ListSharedImagesRequest\x12N\n" +
	"\x12match_repositories\x18\x01 \x01(\v2\x1f.namespace.stdlib.StringMatcherR\x11matchRepositories\x12V\n" +
	"\x10match_visibility\x18\x02 \x01(\x0e2+.namespace.cloud.registry.v1beta.VisibilityR\x0fmatchVisibility\"m\n" +
	"\x18ListSharedImagesResponse\x12Q\n" +
	"\rshared_images\x18\x01 \x03(\v2,.namespace.cloud.registry.v1beta.SharedImageR\fsharedImages\"\xac\x02\n" +
	"\vSharedImage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12+\n" +
	"\x11shared_repository\x18\x02 \x01(\tR\x10sharedRepository\x12#\n" +
	"\rshared_digest\x18\x03 \x01(\tR\fsharedDigest\x129\n" +
	"\n" +
	"expires_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x12\x1b\n" +
	"\timage_ref\x18\x05 \x01(\tR\bimageRef\x12K\n" +
	"\n" +
	"visibility\x18\x06 \x01(\x0e2+.namespace.cloud.registry.v1beta.VisibilityR\n" +
	"visibility\x12\x16\n" +
	"\x06suffix\x18\a \x01(\tR\x06suffix\"\xee\x01\n" +
	"\x11ListImagesRequest\x12+\n" +
	"\x11pagination_cursor\x18\x01 \x01(\fR\x10paginationCursor\x12\x1f\n" +
	"\vmax_entries\x18\x02 \x01(\x03R\n" +
	"maxEntries\x12J\n" +
	"\x10match_repository\x18\x03 \x01(\v2\x1f.namespace.stdlib.StringMatcherR\x0fmatchRepository\x12?\n" +
	"\n" +
	"created_at\x18\x04 \x01(\v2 .namespace.stdlib.TimestampRangeR\tcreatedAt\"\x81\x01\n" +
	"\x12ListImagesResponse\x12>\n" +
	"\x06images\x18\x01 \x03(\v2&.namespace.cloud.registry.v1beta.ImageR\x06images\x12+\n" +
	"\x11pagination_cursor\x18\x02 \x01(\fR\x10paginationCursor\"g\n" +
	"\x17ListRepositoriesRequest\x12+\n" +
	"\x11pagination_cursor\x18\x01 \x01(\fR\x10paginationCursor\x12\x1f\n" +
	"\vmax_entries\x18\x02 \x01(\x03R\n" +
	"maxEntries\"\x98\x01\n" +
	"\x18ListRepositoriesResponse\x12O\n" +
	"\frepositories\x18\x01 \x03(\v2+.namespace.cloud.registry.v1beta.RepositoryR\frepositories\x12+\n" +
	"\x11pagination_cursor\x18\x02 \x01(\fR\x10paginationCursor\"Y\n" +
	"\n" +
	"Repository\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x127\n" +
	"\tlast_push\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\blastPush\"\x7f\n" +
	"\x0fListTagsRequest\x12+\n" +
	"\x11pagination_cursor\x18\x01 \x01(\fR\x10paginationCursor\x12\x1f\n" +
	"\vmax_entries\x18\x02 \x01(\x03R\n" +
	"maxEntries\x12\x1e\n" +
	"\n" +
	"repository\x18\x03 \x01(\tR\n" +
	"repository\"y\n" +
	"\x10ListTagsResponse\x128\n" +
	"\x04tags\x18\x01 \x03(\v2$.namespace.cloud.registry.v1beta.TagR\x04tags\x12+\n" +
	"\x11pagination_cursor\x18\x02 \x01(\fR\x10paginationCursor\"\x98\x01\n" +
	"\x16ListTagVersionsRequest\x12+\n" +
	"\x11pagination_cursor\x18\x01 \x01(\fR\x10paginationCursor\x12\x1f\n" +
	"\vmax_entries\x18\x02 \x01(\x03R\n" +
	"maxEntries\x12\x1e\n" +
	"\n" +
	"repository\x18\x03 \x01(\tR\n" +
	"repository\x12\x10\n" +
	"\x03tag\x18\x04 \x01(\tR\x03tag\"\x88\x01\n" +
	"\x17ListTagVersionsResponse\x12@\n" +
	"\bversions\x18\x01 \x03(\v2$.namespace.cloud.registry.v1beta.TagR\bversions\x12+\n" +
	"\x11pagination_cursor\x18\x02 \x01(\fR\x10paginationCursor\"O\n" +
	"\x0fGetImageRequest\x12\x1e\n" +
	"\n" +
	"repository\x18\x01 \x01(\tR\n" +
	"repository\x12\x1c\n" +
	"\treference\x18\x02 \x01(\tR\treference\"P\n" +
	"\x10GetImageResponse\x12<\n" +
	"\x05image\x18\x01 \x01(\v2&.namespace.cloud.registry.v1beta.ImageR\x05image\"\xbb\x04\n" +
	"\x05Image\x12\x1e\n" +
	"\n" +
	"repository\x18\x01 \x01(\tR\n" +
	"repository\x12\x16\n" +
	"\x06digest\x18\x02 \x01(\tR\x06digest\x129\n" +
	"\n" +
	"created_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"expires_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x12B\n" +
	"\x05sizes\x18\x05 \x01(\v2,.namespace.cloud.registry.v1beta.Image.SizesR\x05sizes\x129\n" +
	"\n" +
	"deleted_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tdeletedAt\x12/\n" +
	"\x06labels\x18\a \x03(\v2\x17.namespace.stdlib.LabelR\x06labels\x12\x12\n" +
	"\x04tags\x18\b \x03(\tR\x04tags\x1a\xbf\x01\n" +
	"\x05Sizes\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x03R\x05total\x12`\n" +
	"\fper_platform\x18\x02 \x03(\v2=.namespace.cloud.registry.v1beta.Image.Sizes.PerPlatformEntryR\vperPlatform\x1a>\n" +
	"\x10PerPlatformEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\"\x90\x01\n" +
	"\x03Tag\x12\x10\n" +
	"\x03tag\x18\x01 \x01(\tR\x03tag\x12<\n" +
	"\x05image\x18\x02 \x01(\v2&.namespace.cloud.registry.v1beta.ImageR\x05image\x129\n" +
	"\n" +
	"created_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\x9c\x02\n" +
	"\x1aUpdateImageLifetimeRequest\x12\x1e\n" +
	"\n" +
	"repository\x18\x01 \x01(\tR\n" +
	"repository\x12\x16\n" +
	"\x06digest\x18\x02 \x01(\tR\x06digest\x126\n" +
	"\textend_by\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\bextendBy\x12S\n" +
	"\x18ensure_minimum_remaining\x18\x04 \x01(\v2\x19.google.protobuf.DurationR\x16ensureMinimumRemaining\x129\n" +
	"\n" +
	"new_expiry\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tnewExpiry\"X\n" +
	"\x1bUpdateImageLifetimeResponse\x129\n" +
	"\n" +
	"new_expiry\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\tnewExpiry\"\xf1\x01\n" +
	"\x1aUpdateDefaultPolicyRequest\x12\x1a\n" +
	"\brevision\x18\x01 \x01(\x03R\brevision\x12H\n" +
	"\x12default_expiration\x18\x02 \x01(\v2\x19.google.protobuf.DurationR\x11defaultExpiration\x12m\n" +
	"\x16expiration_enforcement\x18\x03 \x01(\x0e26.namespace.cloud.registry.v1beta.ExpirationEnforcementR\x15expirationEnforcement\"\xef\x01\n" +
	"\x18GetDefaultPolicyResponse\x12\x1a\n" +
	"\brevision\x18\x01 \x01(\x03R\brevision\x12H\n" +
	"\x12default_expiration\x18\x02 \x01(\v2\x19.google.protobuf.DurationR\x11defaultExpiration\x12m\n" +
	"\x16expiration_enforcement\x18\x03 \x01(\x0e26.namespace.cloud.registry.v1beta.ExpirationEnforcementR\x15expirationEnforcement\"\x85\x02\n" +
	"\x1dUpdateRepositoryPolicyRequest\x12\x1e\n" +
	"\n" +
	"repository\x18\x01 \x01(\tR\n" +
	"repository\x12\x1a\n" +
	"\brevision\x18\x02 \x01(\x03R\brevision\x129\n" +
	"\n" +
	"expiration\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\n" +
	"expiration\x12m\n" +
	"\x16expiration_enforcement\x18\x04 \x01(\x0e26.namespace.cloud.registry.v1beta.ExpirationEnforcementR\x15expirationEnforcement\"<\n" +
	"\x1aGetRepositoryPolicyRequest\x12\x1e\n" +
	"\n" +
	"repository\x18\x01 \x01(\tR\n" +
	"repository\"\xe3\x01\n" +
	"\x1bGetRepositoryPolicyResponse\x12\x1a\n" +
	"\brevision\x18\x01 \x01(\x03R\brevision\x129\n" +
	"\n" +
	"expiration\x18\x02 \x01(\v2\x19.google.protobuf.DurationR\n" +
	"expiration\x12m\n" +
	"\x16expiration_enforcement\x18\x03 \x01(\x0e26.namespace.cloud.registry.v1beta.ExpirationEnforcementR\x15expirationEnforcement*=\n" +
	"\n" +
	"Visibility\x12\x16\n" +
	"\x12UNKNOWN_VISIBILITY\x10\x00\x12\n" +
	"\n" +
	"\x06PUBLIC\x10\x01\x12\v\n" +
	"\aPARTNER\x10\x02*\x8a\x01\n" +
	"\x15ExpirationEnforcement\x12\"\n" +
	"\x1eEXPIRATION_ENFORCEMENT_UNKNOWN\x10\x00\x12\"\n" +
	"\x1eEXPIRATION_ENFORCEMENT_ENFORCE\x10\x01\x12)\n" +
	"%EXPIRATION_ENFORCEMENT_DO_NOT_ENFORCE\x10\x022\xc7\f\n" +
	"\x18ContainerRegistryService\x12o\n" +
	"\bGetImage\x120.namespace.cloud.registry.v1beta.GetImageRequest\x1a1.namespace.cloud.registry.v1beta.GetImageResponse\x12u\n" +
	"\n" +
	"ListImages\x122.namespace.cloud.registry.v1beta.ListImagesRequest\x1a3.namespace.cloud.registry.v1beta.ListImagesResponse\x12\x87\x01\n" +
	"\x10ListRepositories\x128.namespace.cloud.registry.v1beta.ListRepositoriesRequest\x1a9.namespace.cloud.registry.v1beta.ListRepositoriesResponse\x12o\n" +
	"\bListTags\x120.namespace.cloud.registry.v1beta.ListTagsRequest\x1a1.namespace.cloud.registry.v1beta.ListTagsResponse\x12\x84\x01\n" +
	"\x0fListTagVersions\x127.namespace.cloud.registry.v1beta.ListTagVersionsRequest\x1a8.namespace.cloud.registry.v1beta.ListTagVersionsResponse\x12n\n" +
	"\n" +
	"ShareImage\x122.namespace.cloud.registry.v1beta.ShareImageRequest\x1a,.namespace.cloud.registry.v1beta.SharedImage\x12\\\n" +
	"\fUnshareImage\x124.namespace.cloud.registry.v1beta.UnshareImageRequest\x1a\x16.google.protobuf.Empty\x12\x87\x01\n" +
	"\x10ListSharedImages\x128.namespace.cloud.registry.v1beta.ListSharedImagesRequest\x1a9.namespace.cloud.registry.v1beta.ListSharedImagesResponse\x12\x90\x01\n" +
	"\x13UpdateImageLifetime\x12;.namespace.cloud.registry.v1beta.UpdateImageLifetimeRequest\x1a<.namespace.cloud.registry.v1beta.UpdateImageLifetimeResponse\x12j\n" +
	"\x13UpdateDefaultPolicy\x12;.namespace.cloud.registry.v1beta.UpdateDefaultPolicyRequest\x1a\x16.google.protobuf.Empty\x12e\n" +
	"\x10GetDefaultPolicy\x12\x16.google.protobuf.Empty\x1a9.namespace.cloud.registry.v1beta.GetDefaultPolicyResponse\x12p\n" +
	"\x16UpdateRepositoryPolicy\x12>.namespace.cloud.registry.v1beta.UpdateRepositoryPolicyRequest\x1a\x16.google.protobuf.Empty\x12\x90\x01\n" +
	"\x13GetRepositoryPolicy\x12;.namespace.cloud.registry.v1beta.GetRepositoryPolicyRequest\x1a<.namespace.cloud.registry.v1beta.GetRepositoryPolicyResponseB\xaa\x02\n" +
	"#com.namespace.cloud.registry.v1betaB\rRegistryProtoP\x01ZSnamespacelabs.dev/integrations/proto/namespace/cloud/registry/v1beta;registryv1beta\xa2\x02\x03NCR\xaa\x02\x1fNamespace.Cloud.Registry.V1beta\xca\x02 Namespace_\\Cloud\\Registry\\V1beta\xe2\x02,Namespace_\\Cloud\\Registry\\V1beta\\GPBMetadata\xea\x02\"Namespace::Cloud::Registry::V1betab\x06proto3"

var (
	file_proto_namespace_cloud_registry_v1beta_registry_proto_rawDescOnce sync.Once
	file_proto_namespace_cloud_registry_v1beta_registry_proto_rawDescData []byte
)

func file_proto_namespace_cloud_registry_v1beta_registry_proto_rawDescGZIP() []byte {
	file_proto_namespace_cloud_registry_v1beta_registry_proto_rawDescOnce.Do(func() {
		file_proto_namespace_cloud_registry_v1beta_registry_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_namespace_cloud_registry_v1beta_registry_proto_rawDesc), len(file_proto_namespace_cloud_registry_v1beta_registry_proto_rawDesc)))
	})
	return file_proto_namespace_cloud_registry_v1beta_registry_proto_rawDescData
}

var file_proto_namespace_cloud_registry_v1beta_registry_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_namespace_cloud_registry_v1beta_registry_proto_msgTypes = make([]protoimpl.MessageInfo, 27)
var file_proto_namespace_cloud_registry_v1beta_registry_proto_goTypes = []any{
	(Visibility)(0),                       // 0: namespace.cloud.registry.v1beta.Visibility
	(ExpirationEnforcement)(0),            // 1: namespace.cloud.registry.v1beta.ExpirationEnforcement
	(*ShareImageRequest)(nil),             // 2: namespace.cloud.registry.v1beta.ShareImageRequest
	(*UnshareImageRequest)(nil),           // 3: namespace.cloud.registry.v1beta.UnshareImageRequest
	(*ListSharedImagesRequest)(nil),       // 4: namespace.cloud.registry.v1beta.ListSharedImagesRequest
	(*ListSharedImagesResponse)(nil),      // 5: namespace.cloud.registry.v1beta.ListSharedImagesResponse
	(*SharedImage)(nil),                   // 6: namespace.cloud.registry.v1beta.SharedImage
	(*ListImagesRequest)(nil),             // 7: namespace.cloud.registry.v1beta.ListImagesRequest
	(*ListImagesResponse)(nil),            // 8: namespace.cloud.registry.v1beta.ListImagesResponse
	(*ListRepositoriesRequest)(nil),       // 9: namespace.cloud.registry.v1beta.ListRepositoriesRequest
	(*ListRepositoriesResponse)(nil),      // 10: namespace.cloud.registry.v1beta.ListRepositoriesResponse
	(*Repository)(nil),                    // 11: namespace.cloud.registry.v1beta.Repository
	(*ListTagsRequest)(nil),               // 12: namespace.cloud.registry.v1beta.ListTagsRequest
	(*ListTagsResponse)(nil),              // 13: namespace.cloud.registry.v1beta.ListTagsResponse
	(*ListTagVersionsRequest)(nil),        // 14: namespace.cloud.registry.v1beta.ListTagVersionsRequest
	(*ListTagVersionsResponse)(nil),       // 15: namespace.cloud.registry.v1beta.ListTagVersionsResponse
	(*GetImageRequest)(nil),               // 16: namespace.cloud.registry.v1beta.GetImageRequest
	(*GetImageResponse)(nil),              // 17: namespace.cloud.registry.v1beta.GetImageResponse
	(*Image)(nil),                         // 18: namespace.cloud.registry.v1beta.Image
	(*Tag)(nil),                           // 19: namespace.cloud.registry.v1beta.Tag
	(*UpdateImageLifetimeRequest)(nil),    // 20: namespace.cloud.registry.v1beta.UpdateImageLifetimeRequest
	(*UpdateImageLifetimeResponse)(nil),   // 21: namespace.cloud.registry.v1beta.UpdateImageLifetimeResponse
	(*UpdateDefaultPolicyRequest)(nil),    // 22: namespace.cloud.registry.v1beta.UpdateDefaultPolicyRequest
	(*GetDefaultPolicyResponse)(nil),      // 23: namespace.cloud.registry.v1beta.GetDefaultPolicyResponse
	(*UpdateRepositoryPolicyRequest)(nil), // 24: namespace.cloud.registry.v1beta.UpdateRepositoryPolicyRequest
	(*GetRepositoryPolicyRequest)(nil),    // 25: namespace.cloud.registry.v1beta.GetRepositoryPolicyRequest
	(*GetRepositoryPolicyResponse)(nil),   // 26: namespace.cloud.registry.v1beta.GetRepositoryPolicyResponse
	(*Image_Sizes)(nil),                   // 27: namespace.cloud.registry.v1beta.Image.Sizes
	nil,                                   // 28: namespace.cloud.registry.v1beta.Image.Sizes.PerPlatformEntry
	(*timestamppb.Timestamp)(nil),         // 29: google.protobuf.Timestamp
	(*stdlib.StringMatcher)(nil),          // 30: namespace.stdlib.StringMatcher
	(*stdlib.TimestampRange)(nil),         // 31: namespace.stdlib.TimestampRange
	(*stdlib.Label)(nil),                  // 32: namespace.stdlib.Label
	(*durationpb.Duration)(nil),           // 33: google.protobuf.Duration
	(*emptypb.Empty)(nil),                 // 34: google.protobuf.Empty
}
var file_proto_namespace_cloud_registry_v1beta_registry_proto_depIdxs = []int32{
	29, // 0: namespace.cloud.registry.v1beta.ShareImageRequest.expires_at:type_name -> google.protobuf.Timestamp
	0,  // 1: namespace.cloud.registry.v1beta.ShareImageRequest.visibility:type_name -> namespace.cloud.registry.v1beta.Visibility
	30, // 2: namespace.cloud.registry.v1beta.ListSharedImagesRequest.match_repositories:type_name -> namespace.stdlib.StringMatcher
	0,  // 3: namespace.cloud.registry.v1beta.ListSharedImagesRequest.match_visibility:type_name -> namespace.cloud.registry.v1beta.Visibility
	6,  // 4: namespace.cloud.registry.v1beta.ListSharedImagesResponse.shared_images:type_name -> namespace.cloud.registry.v1beta.SharedImage
	29, // 5: namespace.cloud.registry.v1beta.SharedImage.expires_at:type_name -> google.protobuf.Timestamp
	0,  // 6: namespace.cloud.registry.v1beta.SharedImage.visibility:type_name -> namespace.cloud.registry.v1beta.Visibility
	30, // 7: namespace.cloud.registry.v1beta.ListImagesRequest.match_repository:type_name -> namespace.stdlib.StringMatcher
	31, // 8: namespace.cloud.registry.v1beta.ListImagesRequest.created_at:type_name -> namespace.stdlib.TimestampRange
	18, // 9: namespace.cloud.registry.v1beta.ListImagesResponse.images:type_name -> namespace.cloud.registry.v1beta.Image
	11, // 10: namespace.cloud.registry.v1beta.ListRepositoriesResponse.repositories:type_name -> namespace.cloud.registry.v1beta.Repository
	29, // 11: namespace.cloud.registry.v1beta.Repository.last_push:type_name -> google.protobuf.Timestamp
	19, // 12: namespace.cloud.registry.v1beta.ListTagsResponse.tags:type_name -> namespace.cloud.registry.v1beta.Tag
	19, // 13: namespace.cloud.registry.v1beta.ListTagVersionsResponse.versions:type_name -> namespace.cloud.registry.v1beta.Tag
	18, // 14: namespace.cloud.registry.v1beta.GetImageResponse.image:type_name -> namespace.cloud.registry.v1beta.Image
	29, // 15: namespace.cloud.registry.v1beta.Image.created_at:type_name -> google.protobuf.Timestamp
	29, // 16: namespace.cloud.registry.v1beta.Image.expires_at:type_name -> google.protobuf.Timestamp
	27, // 17: namespace.cloud.registry.v1beta.Image.sizes:type_name -> namespace.cloud.registry.v1beta.Image.Sizes
	29, // 18: namespace.cloud.registry.v1beta.Image.deleted_at:type_name -> google.protobuf.Timestamp
	32, // 19: namespace.cloud.registry.v1beta.Image.labels:type_name -> namespace.stdlib.Label
	18, // 20: namespace.cloud.registry.v1beta.Tag.image:type_name -> namespace.cloud.registry.v1beta.Image
	29, // 21: namespace.cloud.registry.v1beta.Tag.created_at:type_name -> google.protobuf.Timestamp
	33, // 22: namespace.cloud.registry.v1beta.UpdateImageLifetimeRequest.extend_by:type_name -> google.protobuf.Duration
	33, // 23: namespace.cloud.registry.v1beta.UpdateImageLifetimeRequest.ensure_minimum_remaining:type_name -> google.protobuf.Duration
	29, // 24: namespace.cloud.registry.v1beta.UpdateImageLifetimeRequest.new_expiry:type_name -> google.protobuf.Timestamp
	29, // 25: namespace.cloud.registry.v1beta.UpdateImageLifetimeResponse.new_expiry:type_name -> google.protobuf.Timestamp
	33, // 26: namespace.cloud.registry.v1beta.UpdateDefaultPolicyRequest.default_expiration:type_name -> google.protobuf.Duration
	1,  // 27: namespace.cloud.registry.v1beta.UpdateDefaultPolicyRequest.expiration_enforcement:type_name -> namespace.cloud.registry.v1beta.ExpirationEnforcement
	33, // 28: namespace.cloud.registry.v1beta.GetDefaultPolicyResponse.default_expiration:type_name -> google.protobuf.Duration
	1,  // 29: namespace.cloud.registry.v1beta.GetDefaultPolicyResponse.expiration_enforcement:type_name -> namespace.cloud.registry.v1beta.ExpirationEnforcement
	33, // 30: namespace.cloud.registry.v1beta.UpdateRepositoryPolicyRequest.expiration:type_name -> google.protobuf.Duration
	1,  // 31: namespace.cloud.registry.v1beta.UpdateRepositoryPolicyRequest.expiration_enforcement:type_name -> namespace.cloud.registry.v1beta.ExpirationEnforcement
	33, // 32: namespace.cloud.registry.v1beta.GetRepositoryPolicyResponse.expiration:type_name -> google.protobuf.Duration
	1,  // 33: namespace.cloud.registry.v1beta.GetRepositoryPolicyResponse.expiration_enforcement:type_name -> namespace.cloud.registry.v1beta.ExpirationEnforcement
	28, // 34: namespace.cloud.registry.v1beta.Image.Sizes.per_platform:type_name -> namespace.cloud.registry.v1beta.Image.Sizes.PerPlatformEntry
	16, // 35: namespace.cloud.registry.v1beta.ContainerRegistryService.GetImage:input_type -> namespace.cloud.registry.v1beta.GetImageRequest
	7,  // 36: namespace.cloud.registry.v1beta.ContainerRegistryService.ListImages:input_type -> namespace.cloud.registry.v1beta.ListImagesRequest
	9,  // 37: namespace.cloud.registry.v1beta.ContainerRegistryService.ListRepositories:input_type -> namespace.cloud.registry.v1beta.ListRepositoriesRequest
	12, // 38: namespace.cloud.registry.v1beta.ContainerRegistryService.ListTags:input_type -> namespace.cloud.registry.v1beta.ListTagsRequest
	14, // 39: namespace.cloud.registry.v1beta.ContainerRegistryService.ListTagVersions:input_type -> namespace.cloud.registry.v1beta.ListTagVersionsRequest
	2,  // 40: namespace.cloud.registry.v1beta.ContainerRegistryService.ShareImage:input_type -> namespace.cloud.registry.v1beta.ShareImageRequest
	3,  // 41: namespace.cloud.registry.v1beta.ContainerRegistryService.UnshareImage:input_type -> namespace.cloud.registry.v1beta.UnshareImageRequest
	4,  // 42: namespace.cloud.registry.v1beta.ContainerRegistryService.ListSharedImages:input_type -> namespace.cloud.registry.v1beta.ListSharedImagesRequest
	20, // 43: namespace.cloud.registry.v1beta.ContainerRegistryService.UpdateImageLifetime:input_type -> namespace.cloud.registry.v1beta.UpdateImageLifetimeRequest
	22, // 44: namespace.cloud.registry.v1beta.ContainerRegistryService.UpdateDefaultPolicy:input_type -> namespace.cloud.registry.v1beta.UpdateDefaultPolicyRequest
	34, // 45: namespace.cloud.registry.v1beta.ContainerRegistryService.GetDefaultPolicy:input_type -> google.protobuf.Empty
	24, // 46: namespace.cloud.registry.v1beta.ContainerRegistryService.UpdateRepositoryPolicy:input_type -> namespace.cloud.registry.v1beta.UpdateRepositoryPolicyRequest
	25, // 47: namespace.cloud.registry.v1beta.ContainerRegistryService.GetRepositoryPolicy:input_type -> namespace.cloud.registry.v1beta.GetRepositoryPolicyRequest
	17, // 48: namespace.cloud.registry.v1beta.ContainerRegistryService.GetImage:output_type -> namespace.cloud.registry.v1beta.GetImageResponse
	8,  // 49: namespace.cloud.registry.v1beta.ContainerRegistryService.ListImages:output_type -> namespace.cloud.registry.v1beta.ListImagesResponse
	10, // 50: namespace.cloud.registry.v1beta.ContainerRegistryService.ListRepositories:output_type -> namespace.cloud.registry.v1beta.ListRepositoriesResponse
	13, // 51: namespace.cloud.registry.v1beta.ContainerRegistryService.ListTags:output_type -> namespace.cloud.registry.v1beta.ListTagsResponse
	15, // 52: namespace.cloud.registry.v1beta.ContainerRegistryService.ListTagVersions:output_type -> namespace.cloud.registry.v1beta.ListTagVersionsResponse
	6,  // 53: namespace.cloud.registry.v1beta.ContainerRegistryService.ShareImage:output_type -> namespace.cloud.registry.v1beta.SharedImage
	34, // 54: namespace.cloud.registry.v1beta.ContainerRegistryService.UnshareImage:output_type -> google.protobuf.Empty
	5,  // 55: namespace.cloud.registry.v1beta.ContainerRegistryService.ListSharedImages:output_type -> namespace.cloud.registry.v1beta.ListSharedImagesResponse
	21, // 56: namespace.cloud.registry.v1beta.ContainerRegistryService.UpdateImageLifetime:output_type -> namespace.cloud.registry.v1beta.UpdateImageLifetimeResponse
	34, // 57: namespace.cloud.registry.v1beta.ContainerRegistryService.UpdateDefaultPolicy:output_type -> google.protobuf.Empty
	23, // 58: namespace.cloud.registry.v1beta.ContainerRegistryService.GetDefaultPolicy:output_type -> namespace.cloud.registry.v1beta.GetDefaultPolicyResponse
	34, // 59: namespace.cloud.registry.v1beta.ContainerRegistryService.UpdateRepositoryPolicy:output_type -> google.protobuf.Empty
	26, // 60: namespace.cloud.registry.v1beta.ContainerRegistryService.GetRepositoryPolicy:output_type -> namespace.cloud.registry.v1beta.GetRepositoryPolicyResponse
	48, // [48:61] is the sub-list for method output_type
	35, // [35:48] is the sub-list for method input_type
	35, // [35:35] is the sub-list for extension type_name
	35, // [35:35] is the sub-list for extension extendee
	0,  // [0:35] is the sub-list for field type_name
}

func init() { file_proto_namespace_cloud_registry_v1beta_registry_proto_init() }
func file_proto_namespace_cloud_registry_v1beta_registry_proto_init() {
	if File_proto_namespace_cloud_registry_v1beta_registry_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_namespace_cloud_registry_v1beta_registry_proto_rawDesc), len(file_proto_namespace_cloud_registry_v1beta_registry_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   27,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_namespace_cloud_registry_v1beta_registry_proto_goTypes,
		DependencyIndexes: file_proto_namespace_cloud_registry_v1beta_registry_proto_depIdxs,
		EnumInfos:         file_proto_namespace_cloud_registry_v1beta_registry_proto_enumTypes,
		MessageInfos:      file_proto_namespace_cloud_registry_v1beta_registry_proto_msgTypes,
	}.Build()
	File_proto_namespace_cloud_registry_v1beta_registry_proto = out.File
	file_proto_namespace_cloud_registry_v1beta_registry_proto_goTypes = nil
	file_proto_namespace_cloud_registry_v1beta_registry_proto_depIdxs = nil
}
