// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: proto/namespace/cloud/registry/v1beta/registry.proto

package registryv1beta

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ContainerRegistryService_GetImage_FullMethodName               = "/namespace.cloud.registry.v1beta.ContainerRegistryService/GetImage"
	ContainerRegistryService_ListImages_FullMethodName             = "/namespace.cloud.registry.v1beta.ContainerRegistryService/ListImages"
	ContainerRegistryService_ListRepositories_FullMethodName       = "/namespace.cloud.registry.v1beta.ContainerRegistryService/ListRepositories"
	ContainerRegistryService_ListTags_FullMethodName               = "/namespace.cloud.registry.v1beta.ContainerRegistryService/ListTags"
	ContainerRegistryService_ListTagVersions_FullMethodName        = "/namespace.cloud.registry.v1beta.ContainerRegistryService/ListTagVersions"
	ContainerRegistryService_ShareImage_FullMethodName             = "/namespace.cloud.registry.v1beta.ContainerRegistryService/ShareImage"
	ContainerRegistryService_UnshareImage_FullMethodName           = "/namespace.cloud.registry.v1beta.ContainerRegistryService/UnshareImage"
	ContainerRegistryService_ListSharedImages_FullMethodName       = "/namespace.cloud.registry.v1beta.ContainerRegistryService/ListSharedImages"
	ContainerRegistryService_UpdateImageLifetime_FullMethodName    = "/namespace.cloud.registry.v1beta.ContainerRegistryService/UpdateImageLifetime"
	ContainerRegistryService_UpdateDefaultPolicy_FullMethodName    = "/namespace.cloud.registry.v1beta.ContainerRegistryService/UpdateDefaultPolicy"
	ContainerRegistryService_GetDefaultPolicy_FullMethodName       = "/namespace.cloud.registry.v1beta.ContainerRegistryService/GetDefaultPolicy"
	ContainerRegistryService_UpdateRepositoryPolicy_FullMethodName = "/namespace.cloud.registry.v1beta.ContainerRegistryService/UpdateRepositoryPolicy"
	ContainerRegistryService_GetRepositoryPolicy_FullMethodName    = "/namespace.cloud.registry.v1beta.ContainerRegistryService/GetRepositoryPolicy"
)

// ContainerRegistryServiceClient is the client API for ContainerRegistryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ContainerRegistryService allows the management of container images stored in
// the workspace's private container registry (`nscr.io`). It supports listing
// images and repositories, managing tags, sharing images publicly or with
// partner accounts, and configuring image expiration policies.
//
// See https://namespace.so/docs/architecture/storage/container-registry for an overview.
//
// ## Access
//
// ContainerRegistryService is a global service that can be accessed at:
//
// ```
// https://global.namespaceapis.com:443
// ```
//
// ## Authentication
//
// Calls to the ContainerRegistryService require a *tenant token* passed as a Bearer token as
// part of each call. These are always required.
//
// A *tenant token* identifies both the workspace that the call operates on, but
// may also constrain the set of actions that the caller may do.
//
// A *tenant token* can be obtained using the
// [IAM API](https://buf.build/namespace/cloud/docs/main:namespace.cloud.iam.v1beta).
type ContainerRegistryServiceClient interface {
	// Retrieves a specific image by repository and reference (tag or digest).
	//
	// ### Errors
	// - If the image does not exist, a `NotFound` status is returned.
	GetImage(ctx context.Context, in *GetImageRequest, opts ...grpc.CallOption) (*GetImageResponse, error)
	// Lists images in the registry that match the specified criteria.
	ListImages(ctx context.Context, in *ListImagesRequest, opts ...grpc.CallOption) (*ListImagesResponse, error)
	// Lists all repositories in the registry.
	ListRepositories(ctx context.Context, in *ListRepositoriesRequest, opts ...grpc.CallOption) (*ListRepositoriesResponse, error)
	// Lists all tags for a specific repository.
	ListTags(ctx context.Context, in *ListTagsRequest, opts ...grpc.CallOption) (*ListTagsResponse, error)
	// Lists all versions of a specific tag in a repository, ordered from newest
	// to oldest. A tag can point to different images over time as it is
	// overwritten by new pushes.
	ListTagVersions(ctx context.Context, in *ListTagVersionsRequest, opts ...grpc.CallOption) (*ListTagVersionsResponse, error)
	// Shares an image either publicly or with tenants of partner accounts.
	// Returns the shared image metadata, including the public image reference
	// that can be used to pull the image.
	//
	// ### Errors
	// - If the image does not exist, a `NotFound` status is returned.
	ShareImage(ctx context.Context, in *ShareImageRequest, opts ...grpc.CallOption) (*SharedImage, error)
	// Removes an existing share, making the shared image reference inaccessible.
	//
	// ### Errors
	// - If the share does not exist, a `NotFound` status is returned.
	UnshareImage(ctx context.Context, in *UnshareImageRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Lists shared images, optionally filtered by repository and visibility.
	ListSharedImages(ctx context.Context, in *ListSharedImagesRequest, opts ...grpc.CallOption) (*ListSharedImagesResponse, error)
	// Extends or updates the expiration of a single image.
	//
	// ### Errors
	// - If the image does not exist, a `NotFound` status is returned.
	UpdateImageLifetime(ctx context.Context, in *UpdateImageLifetimeRequest, opts ...grpc.CallOption) (*UpdateImageLifetimeResponse, error)
	// Updates the default image expiration policy for the workspace.
	// The policy applies to newly created images only.
	UpdateDefaultPolicy(ctx context.Context, in *UpdateDefaultPolicyRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Returns the current default image expiration policy.
	GetDefaultPolicy(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetDefaultPolicyResponse, error)
	// Updates the image expiration policy for a specific repository.
	// Repository-level policies override the default policy.
	UpdateRepositoryPolicy(ctx context.Context, in *UpdateRepositoryPolicyRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Returns the current image expiration policy for a specific repository.
	GetRepositoryPolicy(ctx context.Context, in *GetRepositoryPolicyRequest, opts ...grpc.CallOption) (*GetRepositoryPolicyResponse, error)
}

type containerRegistryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewContainerRegistryServiceClient(cc grpc.ClientConnInterface) ContainerRegistryServiceClient {
	return &containerRegistryServiceClient{cc}
}

func (c *containerRegistryServiceClient) GetImage(ctx context.Context, in *GetImageRequest, opts ...grpc.CallOption) (*GetImageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetImageResponse)
	err := c.cc.Invoke(ctx, ContainerRegistryService_GetImage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *containerRegistryServiceClient) ListImages(ctx context.Context, in *ListImagesRequest, opts ...grpc.CallOption) (*ListImagesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListImagesResponse)
	err := c.cc.Invoke(ctx, ContainerRegistryService_ListImages_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *containerRegistryServiceClient) ListRepositories(ctx context.Context, in *ListRepositoriesRequest, opts ...grpc.CallOption) (*ListRepositoriesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListRepositoriesResponse)
	err := c.cc.Invoke(ctx, ContainerRegistryService_ListRepositories_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *containerRegistryServiceClient) ListTags(ctx context.Context, in *ListTagsRequest, opts ...grpc.CallOption) (*ListTagsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListTagsResponse)
	err := c.cc.Invoke(ctx, ContainerRegistryService_ListTags_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *containerRegistryServiceClient) ListTagVersions(ctx context.Context, in *ListTagVersionsRequest, opts ...grpc.CallOption) (*ListTagVersionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListTagVersionsResponse)
	err := c.cc.Invoke(ctx, ContainerRegistryService_ListTagVersions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *containerRegistryServiceClient) ShareImage(ctx context.Context, in *ShareImageRequest, opts ...grpc.CallOption) (*SharedImage, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SharedImage)
	err := c.cc.Invoke(ctx, ContainerRegistryService_ShareImage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *containerRegistryServiceClient) UnshareImage(ctx context.Context, in *UnshareImageRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, ContainerRegistryService_UnshareImage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *containerRegistryServiceClient) ListSharedImages(ctx context.Context, in *ListSharedImagesRequest, opts ...grpc.CallOption) (*ListSharedImagesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSharedImagesResponse)
	err := c.cc.Invoke(ctx, ContainerRegistryService_ListSharedImages_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *containerRegistryServiceClient) UpdateImageLifetime(ctx context.Context, in *UpdateImageLifetimeRequest, opts ...grpc.CallOption) (*UpdateImageLifetimeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateImageLifetimeResponse)
	err := c.cc.Invoke(ctx, ContainerRegistryService_UpdateImageLifetime_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *containerRegistryServiceClient) UpdateDefaultPolicy(ctx context.Context, in *UpdateDefaultPolicyRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, ContainerRegistryService_UpdateDefaultPolicy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *containerRegistryServiceClient) GetDefaultPolicy(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetDefaultPolicyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDefaultPolicyResponse)
	err := c.cc.Invoke(ctx, ContainerRegistryService_GetDefaultPolicy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *containerRegistryServiceClient) UpdateRepositoryPolicy(ctx context.Context, in *UpdateRepositoryPolicyRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, ContainerRegistryService_UpdateRepositoryPolicy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *containerRegistryServiceClient) GetRepositoryPolicy(ctx context.Context, in *GetRepositoryPolicyRequest, opts ...grpc.CallOption) (*GetRepositoryPolicyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRepositoryPolicyResponse)
	err := c.cc.Invoke(ctx, ContainerRegistryService_GetRepositoryPolicy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ContainerRegistryServiceServer is the server API for ContainerRegistryService service.
// All implementations must embed UnimplementedContainerRegistryServiceServer
// for forward compatibility.
//
// ContainerRegistryService allows the management of container images stored in
// the workspace's private container registry (`nscr.io`). It supports listing
// images and repositories, managing tags, sharing images publicly or with
// partner accounts, and configuring image expiration policies.
//
// See https://namespace.so/docs/architecture/storage/container-registry for an overview.
//
// ## Access
//
// ContainerRegistryService is a global service that can be accessed at:
//
// ```
// https://global.namespaceapis.com:443
// ```
//
// ## Authentication
//
// Calls to the ContainerRegistryService require a *tenant token* passed as a Bearer token as
// part of each call. These are always required.
//
// A *tenant token* identifies both the workspace that the call operates on, but
// may also constrain the set of actions that the caller may do.
//
// A *tenant token* can be obtained using the
// [IAM API](https://buf.build/namespace/cloud/docs/main:namespace.cloud.iam.v1beta).
type ContainerRegistryServiceServer interface {
	// Retrieves a specific image by repository and reference (tag or digest).
	//
	// ### Errors
	// - If the image does not exist, a `NotFound` status is returned.
	GetImage(context.Context, *GetImageRequest) (*GetImageResponse, error)
	// Lists images in the registry that match the specified criteria.
	ListImages(context.Context, *ListImagesRequest) (*ListImagesResponse, error)
	// Lists all repositories in the registry.
	ListRepositories(context.Context, *ListRepositoriesRequest) (*ListRepositoriesResponse, error)
	// Lists all tags for a specific repository.
	ListTags(context.Context, *ListTagsRequest) (*ListTagsResponse, error)
	// Lists all versions of a specific tag in a repository, ordered from newest
	// to oldest. A tag can point to different images over time as it is
	// overwritten by new pushes.
	ListTagVersions(context.Context, *ListTagVersionsRequest) (*ListTagVersionsResponse, error)
	// Shares an image either publicly or with tenants of partner accounts.
	// Returns the shared image metadata, including the public image reference
	// that can be used to pull the image.
	//
	// ### Errors
	// - If the image does not exist, a `NotFound` status is returned.
	ShareImage(context.Context, *ShareImageRequest) (*SharedImage, error)
	// Removes an existing share, making the shared image reference inaccessible.
	//
	// ### Errors
	// - If the share does not exist, a `NotFound` status is returned.
	UnshareImage(context.Context, *UnshareImageRequest) (*emptypb.Empty, error)
	// Lists shared images, optionally filtered by repository and visibility.
	ListSharedImages(context.Context, *ListSharedImagesRequest) (*ListSharedImagesResponse, error)
	// Extends or updates the expiration of a single image.
	//
	// ### Errors
	// - If the image does not exist, a `NotFound` status is returned.
	UpdateImageLifetime(context.Context, *UpdateImageLifetimeRequest) (*UpdateImageLifetimeResponse, error)
	// Updates the default image expiration policy for the workspace.
	// The policy applies to newly created images only.
	UpdateDefaultPolicy(context.Context, *UpdateDefaultPolicyRequest) (*emptypb.Empty, error)
	// Returns the current default image expiration policy.
	GetDefaultPolicy(context.Context, *emptypb.Empty) (*GetDefaultPolicyResponse, error)
	// Updates the image expiration policy for a specific repository.
	// Repository-level policies override the default policy.
	UpdateRepositoryPolicy(context.Context, *UpdateRepositoryPolicyRequest) (*emptypb.Empty, error)
	// Returns the current image expiration policy for a specific repository.
	GetRepositoryPolicy(context.Context, *GetRepositoryPolicyRequest) (*GetRepositoryPolicyResponse, error)
	mustEmbedUnimplementedContainerRegistryServiceServer()
}

// UnimplementedContainerRegistryServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedContainerRegistryServiceServer struct{}

func (UnimplementedContainerRegistryServiceServer) GetImage(context.Context, *GetImageRequest) (*GetImageResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetImage not implemented")
}
func (UnimplementedContainerRegistryServiceServer) ListImages(context.Context, *ListImagesRequest) (*ListImagesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListImages not implemented")
}
func (UnimplementedContainerRegistryServiceServer) ListRepositories(context.Context, *ListRepositoriesRequest) (*ListRepositoriesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListRepositories not implemented")
}
func (UnimplementedContainerRegistryServiceServer) ListTags(context.Context, *ListTagsRequest) (*ListTagsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListTags not implemented")
}
func (UnimplementedContainerRegistryServiceServer) ListTagVersions(context.Context, *ListTagVersionsRequest) (*ListTagVersionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListTagVersions not implemented")
}
func (UnimplementedContainerRegistryServiceServer) ShareImage(context.Context, *ShareImageRequest) (*SharedImage, error) {
	return nil, status.Error(codes.Unimplemented, "method ShareImage not implemented")
}
func (UnimplementedContainerRegistryServiceServer) UnshareImage(context.Context, *UnshareImageRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method UnshareImage not implemented")
}
func (UnimplementedContainerRegistryServiceServer) ListSharedImages(context.Context, *ListSharedImagesRequest) (*ListSharedImagesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListSharedImages not implemented")
}
func (UnimplementedContainerRegistryServiceServer) UpdateImageLifetime(context.Context, *UpdateImageLifetimeRequest) (*UpdateImageLifetimeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateImageLifetime not implemented")
}
func (UnimplementedContainerRegistryServiceServer) UpdateDefaultPolicy(context.Context, *UpdateDefaultPolicyRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateDefaultPolicy not implemented")
}
func (UnimplementedContainerRegistryServiceServer) GetDefaultPolicy(context.Context, *emptypb.Empty) (*GetDefaultPolicyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDefaultPolicy not implemented")
}
func (UnimplementedContainerRegistryServiceServer) UpdateRepositoryPolicy(context.Context, *UpdateRepositoryPolicyRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateRepositoryPolicy not implemented")
}
func (UnimplementedContainerRegistryServiceServer) GetRepositoryPolicy(context.Context, *GetRepositoryPolicyRequest) (*GetRepositoryPolicyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRepositoryPolicy not implemented")
}
func (UnimplementedContainerRegistryServiceServer) mustEmbedUnimplementedContainerRegistryServiceServer() {
}
func (UnimplementedContainerRegistryServiceServer) testEmbeddedByValue() {}

// UnsafeContainerRegistryServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ContainerRegistryServiceServer will
// result in compilation errors.
type UnsafeContainerRegistryServiceServer interface {
	mustEmbedUnimplementedContainerRegistryServiceServer()
}

func RegisterContainerRegistryServiceServer(s grpc.ServiceRegistrar, srv ContainerRegistryServiceServer) {
	// If the following call panics, it indicates UnimplementedContainerRegistryServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ContainerRegistryService_ServiceDesc, srv)
}

func _ContainerRegistryService_GetImage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetImageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContainerRegistryServiceServer).GetImage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ContainerRegistryService_GetImage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContainerRegistryServiceServer).GetImage(ctx, req.(*GetImageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContainerRegistryService_ListImages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListImagesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContainerRegistryServiceServer).ListImages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ContainerRegistryService_ListImages_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContainerRegistryServiceServer).ListImages(ctx, req.(*ListImagesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContainerRegistryService_ListRepositories_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRepositoriesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContainerRegistryServiceServer).ListRepositories(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ContainerRegistryService_ListRepositories_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContainerRegistryServiceServer).ListRepositories(ctx, req.(*ListRepositoriesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContainerRegistryService_ListTags_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTagsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContainerRegistryServiceServer).ListTags(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ContainerRegistryService_ListTags_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContainerRegistryServiceServer).ListTags(ctx, req.(*ListTagsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContainerRegistryService_ListTagVersions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTagVersionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContainerRegistryServiceServer).ListTagVersions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ContainerRegistryService_ListTagVersions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContainerRegistryServiceServer).ListTagVersions(ctx, req.(*ListTagVersionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContainerRegistryService_ShareImage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShareImageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContainerRegistryServiceServer).ShareImage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ContainerRegistryService_ShareImage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContainerRegistryServiceServer).ShareImage(ctx, req.(*ShareImageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContainerRegistryService_UnshareImage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnshareImageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContainerRegistryServiceServer).UnshareImage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ContainerRegistryService_UnshareImage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContainerRegistryServiceServer).UnshareImage(ctx, req.(*UnshareImageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContainerRegistryService_ListSharedImages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSharedImagesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContainerRegistryServiceServer).ListSharedImages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ContainerRegistryService_ListSharedImages_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContainerRegistryServiceServer).ListSharedImages(ctx, req.(*ListSharedImagesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContainerRegistryService_UpdateImageLifetime_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateImageLifetimeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContainerRegistryServiceServer).UpdateImageLifetime(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ContainerRegistryService_UpdateImageLifetime_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContainerRegistryServiceServer).UpdateImageLifetime(ctx, req.(*UpdateImageLifetimeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContainerRegistryService_UpdateDefaultPolicy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateDefaultPolicyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContainerRegistryServiceServer).UpdateDefaultPolicy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ContainerRegistryService_UpdateDefaultPolicy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContainerRegistryServiceServer).UpdateDefaultPolicy(ctx, req.(*UpdateDefaultPolicyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContainerRegistryService_GetDefaultPolicy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContainerRegistryServiceServer).GetDefaultPolicy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ContainerRegistryService_GetDefaultPolicy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContainerRegistryServiceServer).GetDefaultPolicy(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContainerRegistryService_UpdateRepositoryPolicy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRepositoryPolicyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContainerRegistryServiceServer).UpdateRepositoryPolicy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ContainerRegistryService_UpdateRepositoryPolicy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContainerRegistryServiceServer).UpdateRepositoryPolicy(ctx, req.(*UpdateRepositoryPolicyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContainerRegistryService_GetRepositoryPolicy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRepositoryPolicyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContainerRegistryServiceServer).GetRepositoryPolicy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ContainerRegistryService_GetRepositoryPolicy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContainerRegistryServiceServer).GetRepositoryPolicy(ctx, req.(*GetRepositoryPolicyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ContainerRegistryService_ServiceDesc is the grpc.ServiceDesc for ContainerRegistryService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ContainerRegistryService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "namespace.cloud.registry.v1beta.ContainerRegistryService",
	HandlerType: (*ContainerRegistryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetImage",
			Handler:    _ContainerRegistryService_GetImage_Handler,
		},
		{
			MethodName: "ListImages",
			Handler:    _ContainerRegistryService_ListImages_Handler,
		},
		{
			MethodName: "ListRepositories",
			Handler:    _ContainerRegistryService_ListRepositories_Handler,
		},
		{
			MethodName: "ListTags",
			Handler:    _ContainerRegistryService_ListTags_Handler,
		},
		{
			MethodName: "ListTagVersions",
			Handler:    _ContainerRegistryService_ListTagVersions_Handler,
		},
		{
			MethodName: "ShareImage",
			Handler:    _ContainerRegistryService_ShareImage_Handler,
		},
		{
			MethodName: "UnshareImage",
			Handler:    _ContainerRegistryService_UnshareImage_Handler,
		},
		{
			MethodName: "ListSharedImages",
			Handler:    _ContainerRegistryService_ListSharedImages_Handler,
		},
		{
			MethodName: "UpdateImageLifetime",
			Handler:    _ContainerRegistryService_UpdateImageLifetime_Handler,
		},
		{
			MethodName: "UpdateDefaultPolicy",
			Handler:    _ContainerRegistryService_UpdateDefaultPolicy_Handler,
		},
		{
			MethodName: "GetDefaultPolicy",
			Handler:    _ContainerRegistryService_GetDefaultPolicy_Handler,
		},
		{
			MethodName: "UpdateRepositoryPolicy",
			Handler:    _ContainerRegistryService_UpdateRepositoryPolicy_Handler,
		},
		{
			MethodName: "GetRepositoryPolicy",
			Handler:    _ContainerRegistryService_GetRepositoryPolicy_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/namespace/cloud/registry/v1beta/registry.proto",
}
